import vm from 'node:vm';import fs from 'node:fs';import assert from 'node:assert/strict';
const source=fs.readFileSync(new URL('../dist/game.js',import.meta.url),'utf8').replace(/boot\(\);\s*$/,'');
function harness(path='/'){const elements={},storage=new Map(),events={};let stored=null;const c={console,location:{pathname:path},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},document:{getElementById(id){return elements[id]??=( {innerHTML:'',textContent:'',hidden:false,showModal(){this.open=true},close(){this.open=false}})},addEventListener(){}},window:{scrollTo(){},addEventListener(k,fn){events[k]=fn}},setTimeout(){return 1},clearTimeout(){},fetch:async(u,o={})=>({ok:true,status:200,json:async()=>o.method==='PUT'?(stored=JSON.parse(o.body),{etag:'test'}):({save:stored,etag:stored?'test':null})}),FormData:class{constructor(v){this.v=v}get(k){return this.v[k]??null}getAll(k){return this.v[k]||[]}}};vm.createContext(c);vm.runInContext(source,c);return {run:x=>vm.runInContext(x,c),c,events,elements,storage}}


const h=harness('/');await h.run('boot()');assert.equal(h.run('tourHasPlayed()'),false);h.run('markTourSeen()');assert.equal(h.run('tourHasPlayed()'),true);h.run('s=fresh();render()');assert.equal(h.run('tourHasPlayed()'),false);h.run('tourOffer()');assert.ok(h.elements.modal.innerHTML.includes('Skip and play'));h.run("$('modal').close();go('Create');go('Guide');goBack()");assert.equal(h.run('tab'),'Create');h.run("go('Home');routeTrail=[];lastRoute=routeSnapshot();goBack()");assert.equal(h.run('titleVisible'),true);h.run("titleVisible=false;go('Guide')");assert.ok(h.elements.app.innerHTML.includes('Guide ?'));assert.ok(h.elements.app.innerHTML.includes('← Back'));
const before=h.run('JSON.stringify([s.cash,s.energy,s.songs,s.draft])');for(let i=0;i<h.run('gameplayTour.length');i++)h.run(`openTour(${i})`);h.run('endTour()');assert.equal(h.run('JSON.stringify([s.cash,s.energy,s.songs,s.draft])'),before);
const x=harness('/sandbox');await x.run('boot()');x.run('migrateCollection();globalThis.drop=currentDrops()[0];reviewDrop(drop.id);globalThis.funds=s.cash;confirmDrop();globalThis.owned=s.empire.assets.at(-1).id');assert.equal(x.run('s.empire.assets.length'),1);assert.ok(x.run('s.cash<funds'));x.run('confirmDrop();reviewDrop(drop.id);confirmDrop()');assert.equal(x.run('s.empire.assets.length'),1);x.run('reviewDrop(currentDrops()[1].id);s.empire.month++;globalThis.moneyBefore=s.cash;confirmDrop()');assert.equal(x.run('s.cash'),x.run('moneyBefore'));assert.equal(x.run('s.empire.assets[0].id'),x.run('owned'));
x.run(`createMerch({preventDefault(){},target:{qty:'10',price:'30',look:'2'}},'tee');confirmMerch()`);assert.equal(x.run('s.empire.merch[0].look'),2);x.run('validateBundle(saveBundle())');x.run('globalThis.bad=saveBundle();bad.state.empire.merch[0].look=9');assert.throws(()=>x.run('validateBundle(bad)'));
// Activity during a calendar month should prevent the month-end inactivity loss.
x.run(`s.social.followers=10000;s.social.posts=[];s.week=1;s.social.lastWeek=0;publishPulse({preventDefault(){},target:{format:'clip',caption:'Hello',song:''}});globalThis.followers=s.social.followers;for(let w=1;w<=4;w++){s.week=w;finishSocialWeek()}`);assert.equal(x.run('s.social.followers'),x.run('followers'));
x.run(`s.week=5;s.expansion.marketingActions=[{week:5,channel:marketingChannels[0].id,target:'all',estimate:.2,boost:.2}];s.week=8`);assert.equal(x.run('marketingActions().length'),1);x.run('s.week=9');assert.equal(x.run('marketingActions().length'),0);
// Stress 104 weekly advances: two full 52-week years / 24 calendar months.
const z=harness('/sandbox');await z.run('boot()');for(let i=0;i<104;i++){z.run('advance(true)');assert.equal(z.run('s.empire.month'),z.run('calendarMonthAtWeek(s.week)'));assert.ok(z.run('Number.isFinite(s.cash)&&Number.isFinite(s.finance.reserve)'));z.run('validateBundle(saveBundle())')};assert.equal(z.run('s.week'),105);assert.equal(z.run('s.empire.month'),24);assert.equal(z.run('careerDate()'),'January 2028');
console.log('PASS per-save onboarding, guide/back paths, no-cost tour, duplicate/expired limited offers, permanent ownership, merch artwork persistence/import rejection, calendar-month social activity/campaigns and 104-week / 24-month save-finance stress.');