import vm from 'node:vm';import fs from 'node:fs';import assert from 'node:assert/strict';
const source=fs.readFileSync(new URL('../dist/game.js',import.meta.url),'utf8').replace(/boot\(\);\s*$/,'');
function harness(path='/'){const elements={},storage=new Map(),events={};let stored=null;const c={console,location:{pathname:path},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},document:{getElementById(id){return elements[id]??=( {innerHTML:'',textContent:'',hidden:false,showModal(){this.open=true},close(){this.open=false}})},addEventListener(){}},window:{scrollTo(){},addEventListener(k,fn){events[k]=fn}},setTimeout(){return 1},clearTimeout(){},fetch:async(u,o={})=>({ok:true,status:200,json:async()=>o.method==='PUT'?(stored=JSON.parse(o.body),{etag:'test'}):({save:stored,etag:stored?'test':null})}),FormData:class{constructor(v){this.v=v}get(k){return this.v[k]??null}getAll(k){return this.v[k]||[]}}};vm.createContext(c);vm.runInContext(source,c);return {run:x=>vm.runInContext(x,c),c,events,elements,storage}}

const h=harness('/sandbox');await h.run('boot()');h.run(`sandboxEditor();globalThis.form={cash:'1234567890123456789.12',fans:'5000000',energy:'99',ap:'5',reputation:'80',loyalty:'75'};Object.keys(developmentInfo).forEach(k=>form['stat_'+k]='37');s.world.forEach(a=>form['relation_'+a.id]=String(a.id%2?100:-100));applySandboxEdits({preventDefault(){},target:form})`);assert.equal(h.run('s.walletCents'),'123456789012345678912');assert.equal(h.run('level("writing")'),37);assert.equal(h.run('s.world[0].relation'),-100);await h.run('saveNow()');await h.run('boot()');assert.equal(h.run('s.fans'),5000000);assert.equal(h.run('s.world[1].relation'),100);const before=h.run('JSON.stringify(s)');h.run(`form.fans='-1';applySandboxEdits({preventDefault(){},target:form})`);assert.equal(h.run('JSON.stringify(s)'),before);
const normal=harness();await normal.run('boot()');const original=normal.run('JSON.stringify(s)');normal.run(`applySandboxEdits({preventDefault(){},target:{}});sandboxEditor()`);assert.equal(normal.run('JSON.stringify(s)'),original);
for(const kind of ['artist','song','album']){const result=h.run(`Array.from({length:500},()=>generate('${kind}'))`);assert.equal(new Set(result).size,500)}
assert.ok(h.run(`nameInput('songtitle','song').includes('title-dial')`));h.run(`validateBundle(saveBundle())`);
console.log('PASS sandbox edit/save/reload, normal-mode guard, invalid edit atomicity, 500 unique results per naming category, import validation and dial markup.');
h.run(`$('songtitle').value='Custom title';$('songtitle').closest=()=>({songtitle:$('songtitle').value,mood:'Personal / storytelling',package:'0'});$('dial-songtitle').style={setProperty(){}};$('dial-songtitle').setAttribute=function(k,v){this[k]=v};prepareTitleDial('songtitle','song');if($('songtitle').value!=='Custom title')throw Error('Custom title overwritten');keyTitleDial({key:'ArrowRight',preventDefault(){}},'songtitle');if(titleDials.songtitle.index!==1||s.studioIdea.title!==$('songtitle').value)throw Error('Dial selection not saved');turnTitleDial('songtitle',-1);turnTitleDial('songtitle',-1);if(titleDials.songtitle.index!==39)throw Error('Dial wrap');`);console.log('PASS rotary keyboard selection, wrapping, custom-title preservation and saved title.');
