import vm from 'node:vm';import fs from 'node:fs';import assert from 'node:assert/strict';
const source=fs.readFileSync(new URL('../dist/game.js',import.meta.url),'utf8').replace(/boot\(\);\s*$/,'');
function harness(path='/'){const elements={},storage=new Map(),events={};let stored=null;const c={console,location:{pathname:path},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},document:{getElementById(id){return elements[id]??=( {innerHTML:'',textContent:'',hidden:false,showModal(){this.open=true},close(){this.open=false}})},addEventListener(){}},window:{scrollTo(){},addEventListener(k,fn){events[k]=fn}},setTimeout(){return 1},clearTimeout(){},fetch:async(u,o={})=>({ok:true,status:200,json:async()=>o.method==='PUT'?(stored=JSON.parse(o.body),{etag:'test'}):({save:stored,etag:stored?'test':null})}),FormData:class{constructor(v){this.v=v}get(k){return this.v[k]??null}getAll(k){return this.v[k]||[]}}};vm.createContext(c);vm.runInContext(source,c);return {run:x=>vm.runInContext(x,c),c,events,elements,storage}}


const h=harness('/sandbox');await h.run('boot()');
for(const view of ['menuPage','marketPage','pulsePage','locationPage','agencyPage','labelLeaguePage','studio'])assert.ok(h.run(view+'()').length>200,view);
h.run(`executeTrade('index','buy',2,100);executeTrade('index','buy',2,200);globalThis.beforeTax=s.finance.week.investment||0;executeTrade('index','sell',3,300)`);assert.equal(h.run('marketPosition("index").qty'),1);assert.ok(Math.abs(h.run('s.finance.week.investment-beforeTax')-498.7)<.02);h.run('validateBundle(saveBundle())');
h.run(`reviewTrade({preventDefault(){},target:{qty:'1',type:'market',limit:'100'}},'index','buy');s.market.quotes.index.price+=1;globalThis.beforeQty=marketPosition('index').qty;confirmTrade()`);assert.equal(h.run('marketPosition("index").qty'),h.run('beforeQty'));
h.run(`reviewTrade({preventDefault(){},target:{qty:'0.5',type:'limit',limit:'100000'}},'index','buy');confirmTrade();tickMarket()`);assert.equal(h.run('s.market.orders[0].status'),'filled');assert.equal(h.run('marketPosition("index").qty'),1.5);h.run('validateBundle(saveBundle())');
h.run(`publishPulse({preventDefault(){},target:{format:'clip',caption:'A new era',song:''}});globalThis.key=Object.keys(s.conversations.threads).find(k=>k.startsWith('mine-'));sendPulseReply({preventDefault(){},target:{text:'<img src=x onerror=alert(1)> Thanks for listening!',parent:''}},key);flushSocialReplies(true);openPulseThread(key)`);assert.ok(h.elements.modal.innerHTML.includes('&lt;img'));assert.ok(!h.elements.modal.innerHTML.includes('<img src=x'));assert.equal(h.run('socialThread(key).comments.length'),3);const loyalty=h.run('s.loyalty');h.run(`sendPulseReply({preventDefault(){},target:{text:'More music soon',parent:''}},key);flushSocialReplies(true)`);assert.equal(h.run('s.loyalty'),loyalty);h.run('validateBundle(saveBundle())');
h.run(`s.energy=200;localShow();discoverAgents();globalThis.local=s.scene.localFans;localShow()`);assert.equal(h.run('s.scene.localFans'),h.run('local'));h.run(`counterAgent({preventDefault(){},target:{commission:'1',months:'6'}},'maya');signAgent('maya',true);globalThis.rate=s.agency.contract.commission;globalThis.fee=agentCommission(1000)`);assert.equal(h.run('fee'),h.run('rate*10'));assert.ok(h.run('agentReach()>0'));h.run(`s.agency.incidents.push({id:123,title:'Test withdrawal',text:'Review',stolen:1000,resolved:false});globalThis.cash=s.cash;auditAgent(123);auditAgent(123)`);assert.equal(h.run('s.cash-cash'),750);
h.run(`s.energy=200;newSong({preventDefault(){},target:{songtitle:'Sessions',mood:'Personal / storytelling',package:'0',brief:'anthem'}});performSession('polished');performSession('radio')`);assert.equal(h.run('s.draft.steps'),3);assert.equal(h.run('s.draft.sessionPlan.a'),9);h.run('validateBundle(saveBundle())');
h.run(`globalThis.ids=s.draft.id;advance(true)`);assert.equal(h.run('s.draft.id'),h.run('ids'));assert.equal(h.run('s.week'),2);assert.equal(h.run('s.empire.month'),0);h.run('validateBundle(saveBundle())');
for(const mutation of ["bad.state.market.quotes.index.price=-1","bad.state.market.orders[0].qty=-1","bad.state.scene.city='invalid'","bad.state.agency.contract.commission=101","bad.state.labelLeague.contracts[0].label=100","bad.state.conversations.threads[key].key=\"bad'code\""]){h.run('globalThis.bad=saveBundle();'+mutation);assert.throws(()=>h.run('validateBundle(bad)'),mutation)}
for(const id of ['Create','Social','Stats','Industry','Artists','Market','Wealth','Properties','Agency','Location','League','Releases','Labels','Finances'])h.run(`openDestination('${id}')`);
assert.equal(h.run('Object.keys(ASSET_PHOTOS).length'),13);assert.ok(h.run('wealthInventory()').includes('class="asset-photo"'));
// Rival offer while already signed must pay an affordable buyout exactly once.
h.run(`s.energy=200;s.expansion.contract={name:'Old company',share:.2,type:'record',advance:1000,recovered:0,lift:.2,started:s.week,ends:s.week+26,weeks:27};createLabelOffer(0,'Rival');globalThis.offer=s.labelBusiness.offers.find(o=>o.label===0&&!o.used);globalThis.cost=rightsQuote('contract');if(s.cash<cost+1000000)changeCash(cost+1000000-s.cash);globalThis.cash=s.cash;globalThis.advancePay=offer.proposal.advance;signNegotiatedOffer(offer.id,true)`);assert.ok(Math.abs(h.run('s.cash-cash')-h.run('advancePay-cost'))<.02);const cash=h.run('s.cash');h.run('signNegotiatedOffer(offer.id,true)');assert.equal(h.run('s.cash'),cash);h.run('validateBundle(saveBundle())');
console.log('PASS exchange FIFO gains, fractional holdings, stale quotes, limit execution, typed escaped replies, NPC responses, bounded relationship rewards, locations, agent negotiation/fees/disputes, studio decisions, weekly advance preservation, rival buyouts, migration, all new screens and invalid imports.');