import vm from 'node:vm';import fs from 'node:fs';import assert from 'node:assert/strict';
const source=fs.readFileSync(new URL('../dist/game.js',import.meta.url),'utf8').replace(/boot\(\);\s*$/,'');
function harness(path='/'){const elements={},storage=new Map(),events={};let stored=null;const c={console,location:{pathname:path},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},document:{getElementById(id){return elements[id]??=( {innerHTML:'',textContent:'',hidden:false,showModal(){this.open=true},close(){this.open=false}})},addEventListener(){}},window:{scrollTo(){},addEventListener(k,fn){events[k]=fn}},setTimeout(){return 1},clearTimeout(){},fetch:async(u,o={})=>({ok:true,status:200,json:async()=>o.method==='PUT'?(stored=JSON.parse(o.body),{etag:'test'}):({save:stored,etag:stored?'test':null})}),FormData:class{constructor(v){this.v=v}get(k){return this.v[k]??null}getAll(k){return this.v[k]||[]}}};vm.createContext(c);vm.runInContext(source,c);return {run:x=>vm.runInContext(x,c),c,events,elements,storage}}


const h=harness('/sandbox');await h.run('boot()');assert.equal(h.run('s.energy'),200);assert.equal(h.run('s.ap'),undefined);
h.run(`for(let i=0;i<10;i++)action('work')`);assert.equal(h.run('s.energy'),50);h.run(`action('rest')`);assert.equal(h.run('s.energy'),90);h.run(`action('rest')`);assert.equal(h.run('s.energy'),90);h.run('advance(true)');assert.equal(h.run('s.energy'),200);
h.run(`s.energy=20;s.energyVersion=1;s.ap=0;migrateEnergy()`);assert.equal(h.run('s.energy'),200);h.run('s.energy=123;migrateEnergy()');assert.equal(h.run('s.energy'),123);
h.run(`createLabelOffer(0,'Test');globalThis.id=s.labelBusiness.offers[0].id;reviewArtistOffer(id);counterArtistOffer({preventDefault(){},target:{type:s.labelBusiness.offers[0].proposal.type,share:'1',weeks:'17',advance:'999999999'}},id)`);assert.equal(h.run('s.labelBusiness.offers[0].rounds'),1);assert.equal(h.run('s.labelBusiness.offers[0].proposal.weeks'),17);assert.ok(h.run('s.labelBusiness.offers[0].proposal.share>.01'));assert.ok(h.run('s.labelBusiness.offers[0].proposal.advance<999999999'));assert.equal(h.run('s.expansion.contract'),null);h.run(`signNegotiatedOffer(id)`);assert.equal(h.run('s.expansion.contract'),null);h.run(`signNegotiatedOffer(id,true)`);assert.equal(h.run('s.expansion.contract.ends'),h.run('s.week+16'));const cash=h.run('s.cash');h.run(`signNegotiatedOffer(id,true)`);assert.equal(h.run('s.cash'),cash);h.run('validateBundle(saveBundle())');await h.run('saveNow()');await h.run('boot()');assert.equal(h.run('s.expansion.contract.weeks'),17);
const n=harness('/sandbox');await n.run('boot()');assert.equal(n.run('labelDeals.length'),8);n.run(`submitDemo({preventDefault(){},target:{song:s.songs[0].id}},7);globalThis.id=s.labelBusiness.offers[0].id;counterArtistOffer({preventDefault(){},target:{type:'distribution',share:'12.5',weeks:'9',advance:'0'}},id)`);assert.equal(n.run('s.labelBusiness.offers[0].proposal.weeks'),9);n.run('signNegotiatedOffer(id,true)');assert.equal(n.run('s.expansion.contract.type'),'distribution');n.run('s.finance.week.albumSales=200;s.finance.week.live=100');assert.equal(n.run('artistLabelCut(1000)'),150);
const z=harness('/sandbox');await z.run('boot()');z.run(`foundLabel({preventDefault(){},target:{name:'Custom Records'}});globalThis.a=s.world[23];globalThis.ask=rosterTerms(a,'360',.235,37).minimum;reviewRosterOffer({preventDefault(){},target:{type:'360',share:'23.5',weeks:'37',advance:String(ask)}},23);confirmRosterOffer();validateBundle(saveBundle());`);assert.equal(z.run('ownerContracts()[0].share'),.235);assert.equal(z.run('ownerContracts()[0].weeks'),37);assert.equal(z.run('ownerContracts()[0].ends'),37);
const before=z.run('s.cash');z.run(`s.energy=0;action('work');`);assert.equal(z.run('s.cash'),before);z.run('advance(true)');assert.equal(z.run('s.energy'),200);
console.log('PASS energy-only >6 actions, once-weekly rest, 200 refill, one-time migration, 8 labels, genuine counteroffers, confirmation/duplicate protection, arbitrary percentages/terms, distribution scope and save/reload.');
