import assert from 'node:assert/strict';
import {harness} from './harness.mjs';
const h=harness();await h.run('boot()');h.run('migrateTouring()');
assert.equal(h.run("tourDistance('austin','austin')"),0);
assert.ok(h.run("tourDistance('austin','houston')<tourDistance('austin','nyc')"));
assert.equal(h.run("tourDistance('austin','nyc')"),h.run("tourDistance('nyc','austin')"));
h.run(`saveTourStop({preventDefault(){},target:{city:'austin',week:1,venue:0,price:35,vip:30,production:1,security:2,opener:'0'}});reviewWorldTour();confirmWorldTour();settleWorldTour();globalThis.report=s.liveTour.route[0].report`);
assert.equal(h.run('report.tiers.standard+report.tiers.premium'),h.run('report.tickets'));
assert.equal(h.run('report.gross'),h.run('cents(report.tiers.standard*35+report.tiers.premium*61.25)'));
assert.ok(h.run('report.tiers.standard<=350&&report.tiers.premium<=150'));
assert.ok(h.run('s.world[0].liveHistory.length===1'));
assert.ok(h.run('socialThread(report.pulseThread).comments.length>0'));
assert.ok(h.run("tourPage().includes('Read PULSE reactions')"));
h.run('validateBundle(saveBundle())');
assert.equal(h.run('tourOpenerReadiness(0,s.week).ready'),false);
h.run('s.world[1].relation=-50');assert.equal(h.run('tourOpenerReadiness(1,s.week+1).ready'),false);
h.run(`globalThis.safe=JSON.stringify(s);s.touring.draft.route=[{...s.liveTour.route[0],status:'scheduled',report:undefined},{...s.liveTour.route[0],status:'scheduled',report:undefined}]`);assert.throws(()=>h.run('validateWorldTour()'));
h.run('s=JSON.parse(safe);s.liveTour.route[0].report.tiers.premium=9999');assert.throws(()=>h.run('validateWorldTour()'));
h.run('s=JSON.parse(safe);s.touring.archive=[{id:1,name:"Corrupt",played:1,gross:0,production:0,ended:1,route:[{city:"missing"}]}]');assert.throws(()=>h.run('validateWorldTour()'));
console.log('PASS travel distance, ticket-tier accounting, opener availability, shared history, PULSE reactions and corrupt save rejection.');
