import vm from 'node:vm';import fs from 'node:fs';import assert from 'node:assert/strict';
const source=fs.readFileSync(new URL('../dist/game.js',import.meta.url),'utf8').replace(/boot\(\);\s*$/,'');
function harness(path='/sandbox'){const elements={},storage=new Map(),events={};let stored=null;const c={console,location:{pathname:path},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},document:{documentElement:{dataset:{}},body:{classList:{add(){},remove(){},toggle(){}}},getElementById(id){return elements[id]??=({innerHTML:'',textContent:'',hidden:false,open:false,className:'',style:{},showModal(){this.open=true},close(){this.open=false},querySelectorAll(){return[]},querySelector(){return null}})},addEventListener(){},querySelectorAll(){return[]},querySelector(){return null},createElement(){return {className:'',dataset:{},textContent:'',before(){},style:{}}},visibilityState:'visible'},window:{scrollTo(){},addEventListener(k,fn){events[k]=fn}},setTimeout(){return 1},clearTimeout(){},setInterval(){return 1},clearInterval(){},fetch:async(u,o={})=>({ok:true,status:200,json:async()=>o.method==='PUT'?(stored=JSON.parse(o.body),{etag:'test'}):({save:stored,etag:stored?'test':null})}),FormData:class{constructor(v){this.v=v}get(k){return this.v?.[k]??null}getAll(k){return this.v?.[k]||[]}}};vm.createContext(c);vm.runInContext(source,c);return {run:x=>vm.runInContext(x,c),c,elements}}
const h=harness();await h.run('boot()');
assert.equal(h.run('GAME_VERSION'),'0.8.1-beta.1');
h.run('migrateV081()');assert.equal(h.run('s.v081.version'),1);
assert.ok(h.run("V080_destinations.some(d=>d[2]==='Creative')"));assert.ok(h.run("V080_destinations.some(d=>d[2]==='Sports')"));
h.run("assetDetail('watch')");assert.ok(h.run("$('modal').innerHTML.includes('All-in cost')"));assert.ok(h.run("$('modal').innerHTML.includes('Estimated annual value range')"));
h.run("migrateMarket();marketSelected='growth';globalThis.marketHTML=marketPage()");assert.ok(h.run("marketHTML.includes('INVESTMENT INTELLIGENCE')"));assert.ok(h.run("marketHTML.includes('Technology')"));assert.ok(h.run("marketHTML.includes('Volatility')"));
h.run("V080_catalogBuyForm(0)");assert.ok(h.run("$('modal').innerHTML.includes('Estimated annual catalog value range')"));
h.run("s.cash=1e12;s.reputation=90;s.labelBusiness.company={name:'Test Label',started:1,staff:{manager:false,marketing:false,ar:false},contracts:[],receipts:0,last:null,preparedWeek:0,settledWeek:0};globalThis.ra=s.world[5];ra.relation=40;globalThis.low=V081_rosterInterest(ra,{type:'360',share:.5,weeks:104,advance:1000});globalThis.high=V081_rosterInterest(ra,{type:'record',share:.1,weeks:26,advance:10000000})");assert.ok(h.run('high.score>low.score'));assert.ok(h.run('low.walk>high.walk'));
h.run("V081_upgradeLabel('equipment',true)");assert.equal(h.run('s.v081.label.upgrades.equipment'),1);h.run("globalThis.dev=V081_artistDev(ra)");assert.ok(h.run('dev.skills.writing>=0'));
h.run('s.empire.month=3;s.v081.creative.lastGeneratedMonth=-1;s.v081.creative.songMarketMonth=-1;V081_generateCreativeOffers();V081_generateSongMarket()');assert.ok(h.run('s.v081.creative.offers.length>=2'));assert.equal(h.run('s.v081.creative.songMarket.length'),12);
h.run("V081_featureAccessFilter='Available';featurePicker();globalThis.availableHTML=$('modal').innerHTML");assert.ok(h.run("availableHTML.includes('Available')&&availableHTML.includes('Locked')"));
h.run('s.cash=1e12;globalThis.team=s.v081.sports.teams[0];globalThis.beforeSports=s.cash;V081_buySports(team.id,.001,true)');assert.equal(h.run('s.v081.sports.holdings.length'),1);assert.ok(h.run('s.cash<beforeSports'));h.run('s.v081.sports.lastSettledMonth=-1;V081_settleSports()');assert.ok(h.run('s.v081.sports.teams[0].games>0'));
assert.equal(h.run("V081_rolloutDurations.join(',')"),'8,12,16');
h.run('s.fans=100000000;s.loyalty=90;globalThis.tf=V081_tourTakeHome(liveVenues[3],80,225)');assert.ok(h.run('tf.gross>0&&tf.production>0&&Number.isFinite(tf.net)'));
h.run('validateBundle(saveBundle())');
console.log('PASS ENCORE 0.8.1 label interest, roster development, creative network, investment intelligence, sports ownership, rollout depth and tour take-home forecast.');
