import vm from 'node:vm';import fs from 'node:fs';import assert from 'node:assert/strict';
const source=fs.readFileSync(new URL('../dist/game.js',import.meta.url),'utf8').replace(/boot\(\);\s*$/,'');
function harness(path='/sandbox'){const elements={},storage=new Map(),events={};let stored=null;const bodyChildren=[];const c={console,location:{pathname:path},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},document:{documentElement:{dataset:{}},body:{classList:{add(){},remove(){},toggle(){}},appendChild(x){bodyChildren.push(x)}},getElementById(id){return elements[id]??=({innerHTML:'',textContent:'',hidden:false,open:false,className:'',style:{},showModal(){this.open=true},close(){this.open=false},querySelectorAll(){return[]},querySelector(){return null}})},addEventListener(){},querySelectorAll(){return[]},querySelector(){return null},createElement(tag){return {tagName:tag,className:'',dataset:{},textContent:'',children:[],style:{setProperty(){}},appendChild(x){this.children.push(x)},setAttribute(){},before(){},remove(){}}},visibilityState:'visible'},window:{scrollTo(){},addEventListener(k,fn){events[k]=fn}},setTimeout(){return 1},clearTimeout(){},setInterval(){return 1},clearInterval(){},fetch:async(u,o={})=>({ok:true,status:200,json:async()=>o.method==='PUT'?(stored=JSON.parse(o.body),{etag:'test'}):({save:stored,etag:stored?'test':null})}),FormData:class{constructor(v){this.v=v}get(k){return this.v?.[k]??null}getAll(k){return this.v?.[k]||[]}}};vm.createContext(c);vm.runInContext(source,c);return {run:x=>vm.runInContext(x,c),c,elements,bodyChildren}}
const h=harness();await h.run('boot()');
const currentVersion=JSON.parse(fs.readFileSync(new URL('../package.json',import.meta.url),'utf8')).version;assert.equal(h.run('GAME_VERSION'),currentVersion);
h.run('migrateV083()');assert.equal(h.run('s.v083.version'),1);
assert.equal(h.run('careerDate(0)'),'January 2026');assert.equal(h.run('careerDate(11)'),'December 2026');assert.equal(h.run('careerDate(12)'),'January 2027');assert.equal(h.run('V083_weekDate(1)'),'Week 1 · January 2026');assert.equal(h.run('V083_weekDate(5)'),'Week 5 · February 2026');assert.equal(h.run('V083_weekDate(53)'),'Week 53 · January 2027');
h.run('s.week=1;s.chartWeek=1;s.empire.month=0;s.energy=50;s.v083.monthAccumulator={monthIndex:0,startWeek:1,streams:0,fans:0,royalties:0,taxes:0,cashChange:0};advance(true)');assert.equal(h.run('s.week'),2);assert.equal(h.run('s.empire.month'),0);assert.equal(h.run('s.energy'),200);
h.run('s.week=4;s.chartWeek=4;s.empire.month=0;s.energy=200;s.v083.monthAccumulator={monthIndex:0,startWeek:1,streams:0,fans:0,royalties:0,taxes:0,cashChange:0};s.v081.lastSettledMonth=-1;s.v081.sports.lastSettledMonth=-1;s.v082.lastSettledMonth=-1;advance(true)');assert.equal(h.run('s.week'),5);assert.equal(h.run('s.empire.month'),1);assert.equal(h.run('s.empire.lastMonth.monthIndex'),0);assert.equal(h.run('careerDate()'),'February 2026');
h.run('migrateV083()');assert.equal(h.run('s.v081.sports.teams.length'),10);assert.equal(h.run("new Set(s.v081.sports.teams.map(t=>t.sport)).size"),1);assert.equal(h.run('s.v081.sports.teams[0].sport'),'Basketball');assert.ok(h.run('new Set(s.v081.sports.teams.map(t=>t.value)).size>=8'));assert.ok(h.run('Math.max(...s.v081.sports.teams.map(t=>t.titles))>Math.min(...s.v081.sports.teams.map(t=>t.titles))'));assert.ok(h.run("V081_sportsPage().includes('ENCORE Pro Basketball')"));
h.run("s.energy=200;publishPulse({preventDefault(){},target:{format:'story',caption:'Just checking in with everybody.',song:''}})");assert.equal(h.run('s.social.posts.at(-1).song'),null);h.run('composePulse()');assert.ok(h.run("$('modal').innerHTML.includes('Song link')&&$('modal').innerHTML.includes('(optional)')"));
assert.equal(h.run("V083_nameGender('Mira Vale')"),'female');assert.equal(h.run("V083_nameGender('Cairo Lane')"),'male');h.run('migrateV085();globalThis.miraName=s.world[0].name;globalThis.cairoName=s.world[1].name;globalThis.miraPhoto=personPhoto(\'artist-0\',miraName);globalThis.cairoPhoto=personPhoto(\'artist-1\',cairoName)');assert.ok(h.run("miraPhoto.includes('v085-initial-portrait')"));assert.ok(h.run("cairoPhoto.includes('v085-initial-portrait')"));assert.ok(h.run("miraPhoto.includes(V088_initials(miraName))"));assert.ok(h.run("cairoPhoto.includes(V088_initials(cairoName))"));assert.equal(h.run("miraPhoto.includes('<img')"),false);assert.equal(h.run("cairoPhoto.includes('<img')"),false);assert.equal(h.run("personPhoto('artist-0',miraName)"),h.run("personPhoto('catalog-0',miraName)"));
assert.ok(h.run("V080_GUIDE_TOPICS.some(x=>x[0]==='Energy and weeks')"));h.run('validateBundle(saveBundle())');
console.log('PASS ENCORE 0.8.3 weekly advances, January 2026 calendar, monthly boundary settlement, ten-team basketball league, optional PULSE song links and stable current people identities.');
