import vm from 'node:vm';import fs from 'node:fs';import assert from 'node:assert/strict';
const source=fs.readFileSync(new URL('../dist/game.js',import.meta.url),'utf8').replace(/boot\(\);\s*$/,'');
function harness(path='/'){const elements={},storage=new Map(),events={};let stored=null;const c={console,location:{pathname:path},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},document:{getElementById(id){return elements[id]??=( {innerHTML:'',textContent:'',hidden:false,showModal(){this.open=true},close(){this.open=false}})},addEventListener(){}},window:{scrollTo(){},addEventListener(k,fn){events[k]=fn}},setTimeout(){return 1},clearTimeout(){},fetch:async(u,o={})=>({ok:true,status:200,json:async()=>o.method==='PUT'?(stored=JSON.parse(o.body),{etag:'test'}):({save:stored,etag:stored?'test':null})}),FormData:class{constructor(v){this.v=v}get(k){return this.v[k]??null}getAll(k){return this.v[k]||[]}}};vm.createContext(c);vm.runInContext(source,c);return {run:x=>vm.runInContext(x,c),c,events,elements,storage}}

const h=harness('/sandbox');await h.run('boot()');h.run("s.fans=200000000;s.loyalty=100;for(const d of Object.values(s.development))d.level=100;reconcileRegionalAudience(migrateCareerWorld())");
assert.equal(h.run('tourDemand(liveVenues[3],225,160)*225'),2223000000);
h.run("reviewWorldTour({preventDefault(){},target:{name:'Global Era',venue:'3',shows:'160',price:'225'}});confirmWorldTour()");assert.equal(h.run('s.liveTour.completed'),0);assert.equal(h.run('s.liveTour.route.length'),160);assert.ok(h.run("s.liveTour.route.every(x=>x.marketId&&x.city&&x.status==='scheduled')"));assert.ok(h.run('Object.keys(s.careerWorld.markets).includes(s.liveTour.route[0].marketId)'));
const cash=h.run('s.cash');h.run('confirmWorldTour()');assert.equal(h.run('s.cash'),cash);
h.run('settleWorldTour()');assert.ok(h.run('s.liveTour.completed>0&&s.liveTour.completed<=8'));assert.ok(h.run('s.liveTour.gross>0&&s.liveTour.production>10000000'));assert.ok(h.run('s.cash')-cash<h.run('s.liveTour.gross'));assert.ok(h.run('s.liveTour.satisfaction>0'));assert.ok(h.run("s.liveTour.route.some(x=>x.status==='completed')"));assert.ok(h.run('Object.keys(s.liveTour.completedMarkets).length>0'));

h.run("s.expansion.contract={type:'360',share:.5};s.finance.week.live=1000;s.finance.week.albumSales=0");assert.equal(h.run('artistLabelCut(0)'),500);h.run('s.expansion.contract=null;validateBundle(saveBundle())');
h.run('changeCash(-s.cash);globalThis.done=s.liveTour.completed;settleWorldTour()');assert.equal(h.run('s.liveTour.completed'),h.run('done'));assert.equal(h.run('s.liveTour.paused'),true);h.run('cancelWorldTour(true);settleWorldTour()');assert.equal(h.run('s.liveTour.completed'),h.run('done'));assert.equal(h.run('s.liveTour.cancelled'),true);h.run('validateBundle(saveBundle())');
const n=harness('/sandbox');await n.run('boot()');n.run("createLabelOffer(0,'Test');globalThis.o=s.labelBusiness.offers[0];ensureLabelProposal(o);o.proposal.type='record';globalThis.energy=s.energy;counterArtistOffer({preventDefault(){},target:{type:'360',share:'50',weeks:'26',advance:'0'}},o.id)");assert.equal(n.run('s.energy'),n.run('energy'));assert.equal(n.run('o.proposal.type'),'record');assert.ok(n.run("!contractFields(o.proposal,true).includes('<select')"));assert.ok(n.run("contractFields(o.proposal).includes('360 deal')"));
console.log('PASS Touring 2.0 regional routing, local show settlement and aftermath, stadium scale/capacity, deposit duplicate protection, gross versus production, 360 live share, funding pause, cancellation, save validation and label-proposed contract structure.');
