/* Beta support: explicit, player-controlled sharing; no automatic reports. */
const GAME_VERSION='0.3.1-beta.1';
const PUBLIC_GAME_URL='https://encore-artist-ty.tysheffield2.chatgpt.site';
const BETA_EXPORT_KEY='encore-last-export-'+(SANDBOX?'sandbox':'career')+'-'+(OFFLINE?'offline':'online');
let betaReportText='';
function betaInvitation(){return `I’m opening a small beta for ENCORE, my music career simulator!\n\nCreate your artist, write and release music, build relationships, climb the charts, and grow from local shows toward stadiums. Play in your browser—no sign-up.\n\nTry it here: ${PUBLIC_GAME_URL}\n\nStart a normal career and try your first 10 in-game weeks. Tell me what’s fun, confusing, too easy, or too hard. If something breaks, open Beta & feedback to prepare a report and send it back to me.\n\nThis is an early beta, so bugs and balance changes are expected. Back up your progress in Career → Saves. Thanks for helping shape ENCORE!`}
function betaInfo(){modal(`<span class="eyebrow">ENCORE · ${GAME_VERSION}</span><h2>Welcome to the beta.</h2><p>Help shape the game by playing a fresh career through your first ten weeks. The title screen always opens before gameplay.</p><div class="controls"><button class="primary" onclick="betaFeedback()">Report a bug / give feedback</button><button class="secondary" onclick="betaShare()">Invite a tester</button></div><h3>What to try</h3><ol><li>Create an artist and try the optional gameplay tour.</li><li>Write, record, mix and release your first song.</li><li>Train a skill, meet an artist, and advance the week.</li><li>Close and reopen the game to check your save.</li><li>Export a backup in Career → Saves.</li></ol><h3>Known limitations</h3><ul><li>Mobile layouts and long-term balance are still being tested. Tell us your device and browser if something looks wrong.</li><li>Online careers belong to this browser’s guest save. Clearing cookies can lose access. Offline careers are separate; use export/import to transfer.</li><li>Very large stream and income calculations are approximate. Extremely long careers can reach the save-size limit.</li><li>This is a solo simulation. Sandbox progress is separate from normal careers.</li></ul><h3>Protect your career</h3><p>Keep a downloaded backup before updates, switching devices, or clearing browser data. Automatic recovery is a single rotating snapshot on this device.</p>${saveReady?`<button class="secondary" onclick="exportCareer()">Export career backup</button>`:''}<details><summary>What’s new · ${GAME_VERSION}</summary><p>Beta version labels, player-controlled feedback reports, sharing tools, known issues, backup reminders and a first-session checklist. Existing careers and progression are preserved.</p></details><details><summary>Next priorities</summary><p>First: mobile controls and save reliability. Next: tune the first ten weeks and mid-career economy using tester feedback. Later: wider browser release and an installed app beta. Dates are not promised.</p></details><p class="fine">Reports are not sent automatically. Copy, download, or share yours with the person who invited you. Do not include passwords or private information.</p><button class="secondary" onclick="$('modal').close()">Back to game</button>`)}
function betaFeedback(){modal(`<span class="eyebrow">${GAME_VERSION}</span><h2>Help improve ENCORE</h2><form class="form" onsubmit="prepareBetaReport(event)"><label>Report type<select name="kind"><option>Bug</option><option>Confusing control</option><option>Balance feedback</option><option>Suggestion</option></select></label><label>What happened?<textarea name="summary" required maxlength="2000" rows="4" placeholder="Describe the issue or your feedback"></textarea></label><label>Steps to reproduce<textarea name="steps" maxlength="2000" rows="3" placeholder="What did you tap before it happened?"></textarea></label><label>What did you expect?<textarea name="expected" maxlength="1000" rows="2"></textarea></label><label>Device and browser<input name="device" maxlength="150" placeholder="For example: iPhone 15, Safari"></label><button class="primary">Prepare report</button><p class="fine">Adds version, mode, current screen, in-game week and save status. Does not attach your career, artist name, cookies, or account details. Nothing is sent automatically.</p></form>`)}
function prepareBetaReport(event){event.preventDefault();const f=new FormData(event.target),value=(key,max)=>String(f.get(key)||'').trim().slice(0,max);if(!value('summary',2000)){toast('Describe what happened first.');return}betaReportText=`ENCORE BETA FEEDBACK\nVersion: ${GAME_VERSION}\nType: ${value('kind',40)}\nMode: ${SANDBOX?'Sandbox':'Normal career'} / ${OFFLINE?'Offline':'Browser'}\nWeek: ${saveReady?s.week:'Not loaded'}\nScreen: ${titleVisible?'Title':tab+(tab==='Career'?' / '+careerTab:'')}\nSave: ${saveConflict?'Conflict':saveBusy?'Saving':saveReady?(JSON.stringify(s)===lastSaved?'Saved':'Unsaved changes'):'Not loaded'}\nDevice/browser: ${value('device',150)||'Not provided'}\n\nWhat happened:\n${value('summary',2000)}\n\nSteps:\n${value('steps',2000)||'Not provided'}\n\nExpected:\n${value('expected',1000)||'Not provided'}`;betaReportPreview()}
function betaReportPreview(){modal(`<h2>Your report is ready</h2><p>Send this to the person who invited you. Include a screenshot separately if it helps. This report has not been submitted.</p><textarea id="beta-copy" readonly rows="12">${esc(betaReportText)}</textarea><div class="controls"><button class="primary" onclick="copyBetaText()">Copy report</button><button class="secondary" onclick="shareBetaText(false)">Share report</button><button class="secondary" onclick="downloadBetaReport()">Download report</button></div><p id="beta-copy-status" role="status"></p>`)}
function betaShare(){modal(`<h2>Invite someone to ENCORE</h2><p>This invitation opens the normal game, with a separate career for each browser.</p><textarea id="beta-copy" readonly rows="12">${esc(betaInvitation())}</textarea><div class="controls"><button class="primary" onclick="shareBetaText(true)">Share invitation</button><button class="secondary" onclick="copyBetaText()">Copy invitation</button></div><p id="beta-copy-status" role="status"></p>`)}
async function copyBetaText(){const el=$('beta-copy');try{if(!globalThis.navigator?.clipboard?.writeText)throw Error('Unavailable');await navigator.clipboard.writeText(el.value);$('beta-copy-status').textContent='Copied. Paste it into your message.'}catch{el.focus?.();el.select?.();$('beta-copy-status').textContent='Select and copy the text above using your browser.'}}
async function shareBetaText(invitation){const text=invitation?betaInvitation():betaReportText;if(globalThis.navigator?.share){try{await navigator.share({title:invitation?'Try ENCORE beta':'ENCORE beta feedback',text});return}catch(e){if(e.name==='AbortError')return}}await copyBetaText()}
function downloadBetaReport(){const url=URL.createObjectURL(new Blob([betaReportText],{type:'text/plain;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='ENCORE-beta-report.txt';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);$('beta-copy-status').textContent='Download prepared. Send the saved file to your beta host.'}
function noteBetaExport(){try{localStorage.setItem(BETA_EXPORT_KEY,JSON.stringify({week:s.week,at:Date.now()}))}catch{}}
function betaHomeNotice(){let last=null;try{last=JSON.parse(localStorage.getItem(BETA_EXPORT_KEY)||'null')}catch{}const due=s.started&&(!last||s.week-last.week>=4||s.week<last.week);return `<aside class="beta-strip"><div><strong>ENCORE BETA · ${GAME_VERSION}</strong><p>${due?'Keep a downloaded career backup. Recovery snapshots stay on this device.':'Help us test your first ten weeks. Report confusing controls, bugs, or balance issues.'}</p></div><div class="controls">${due?'<button class="secondary" onclick="exportCareer()">Export backup</button>':''}<button class="secondary" onclick="betaInfo()">Beta & feedback</button></div></aside>`}
