/* Career progression: budgets, audiences, live shows, opportunities and contracts. */
const studioPackages=[{name:'Home studio',fee:0,quality:0},{name:'Professional studio',fee:1500,quality:5},{name:'Premium production',fee:25000,quality:9}];
const promotionPlans=[{name:'Grassroots',cost:50,boost:.18},{name:'Targeted campaign',cost:2500,boost:.4},{name:'National campaign',cost:50000,boost:.65}];
const venueTiers=[
{name:'Local rooms',fans:250,seats:300,ticket:8,cost:100},
{name:'Clubs',fans:5000,seats:1800,ticket:20,cost:12000},
{name:'Theaters',fans:50000,seats:9000,ticket:40,cost:140000},
{name:'Arenas',fans:500000,seats:45000,ticket:65,cost:1500000},
{name:'Stadiums',fans:5000000,seats:180000,ticket:100,cost:8500000}];
const labelDeals=[{name:'Boutique label',fans:1000,rep:15,advance:25000,share:.15,lift:.12},{name:'Major label',fans:250000,rep:45,advance:1500000,share:.3,lift:.28}];
function migrateExpansion(){if(!s.expansion)s.expansion={version:1,sinceWeek:s.week,listeners:0,inactive:0,timeline:[],opportunities:[],awards:[],albumRollout:null,contract:null,contractHistory:[],campaignWeek:0,tourWeek:0,careerPeakFans:s.fans};if(!s.walletCents)s.walletCents=decimalCents(s.cash).toString();for(const a of s.world){let next=a.nextCatalogId??(Math.max(-1,...a.catalog.map(x=>x.uid??-1))+1);for(const x of a.catalog)if(x.uid===undefined)x.uid=next++;a.nextCatalogId=next}}
function decimalCents(value){const str=String(value),m=str.match(/^(-?)(\d+)(?:\.(\d+))?(?:e([+-]?\d+))?$/i);if(!m)throw Error('Invalid money amount');let digits=BigInt(m[2]+(m[3]||'')),shift=2+Number(m[4]||0)-(m[3]||'').length;if(shift>=0)digits*=10n**BigInt(shift);else{const divisor=10n**BigInt(-shift);digits=(digits+divisor/2n)/divisor}return m[1]?-digits:digits}
function changeCash(delta){if(!s.walletCents||Number(BigInt(s.walletCents))/100!==s.cash)s.walletCents=decimalCents(s.cash).toString();s.walletCents=(BigInt(s.walletCents)+decimalCents(delta)).toString();s.cash=Number(BigInt(s.walletCents))/100;return s.cash}
function exactWallet(){migrateExpansion();const n=BigInt(s.walletCents),a=n<0n?-n:n;return (n<0n?'−':'')+'$'+(a/100n).toLocaleString('en-US')+'.'+String(a%100n).padStart(2,'0')}
function milestone(id,title,detail=''){if(s.expansion.timeline.some(x=>x.id===id))return;s.expansion.timeline.push({id,title,detail,week:s.week});s.expansion.timeline=s.expansion.timeline.slice(-200)}
function logCareerMilestones(){const released=s.songs.filter(x=>x.released);if(released.length)milestone('first-release','First release',released[0].title);if(s.songs.some(x=>x.peak))milestone('first-chart','First chart entry');if(s.songs.some(x=>x.certification))milestone('first-cert','First certified record');for(let i=1;i<thresholds.length;i++)if(s.fans>=thresholds[i])milestone('tier-'+i,tierNames[i]+' era',compact(s.fans)+' fans');s.expansion.careerPeakFans=Math.max(s.expansion.careerPeakFans,s.fans)}
function genreFit(track){const index=genres.indexOf(track.genre||s.genre);return .92+.16*(.5+.5*Math.sin(Math.floor(s.week/8)*.65+index*1.7))}
function adjustReleaseStreams(track,n){const age=s.week-track.released;const stage=age<2?'Discovery':age<8?'Peak window':age<26?'Catalog':'Legacy';track.lifecycle=stage;const recent=s.songs.filter(x=>x.released&&s.week-x.released<4).length;const fatigue=1/(1+Math.max(0,recent-2)*.08);const album=s.albums.find(a=>a.id===track.album);const albumLift=album&&s.week-album.week<4?1+(album.cohesion||0)/1000:1;const factor=genreFit(track)*fatigue*albumLift*(1+trackMarketingBoost(track))*(age>52?.97:1);n=Math.max(0,Math.round(n*factor));track.marketFit=Math.round(genreFit(track)*100);track.rolloutFactor=fatigue;return n}
function settleAudience(streams,raw){const released=s.songs.filter(x=>x.released),recent=released.some(x=>s.week-x.released<8),old=s.fans;const listeners=Math.round(streams/(2.5+Math.min(5,released.length*.12)));s.expansion.listeners=listeners;const available=Math.max(0,listeners-old*.25);const acquired=Math.round(Math.min(raw/Math.sqrt(1+Math.max(0,released.length-3)*.18),available*.05));const churn=Math.round(old*(recent?.0005:.0025)*(1-s.loyalty/150));s.expansion.inactive+=churn;s.expansion.lastAudience={acquired,churn,listeners};return acquired-churn}
function beginCareerWeek(){migrateExpansion();migrateExperience();backupCareer(false);prepareLabelWeek();resolveMarketing();const e=s.expansion;if(e.contract&&s.week<=e.contract.ends)s.boost+=e.contract.lift;if(e.albumRollout){const r=e.albumRollout;if(s.week<=r.until){const song=s.songs.find(x=>x.id===r.lead);if(song)s.boost+=r.boost}else{e.albumRollout=null;log('Your album campaign has ended.')}}}
function finishCareerWeek(){const e=s.expansion;if(e.albumRollout&&e.albumRollout.until<=s.week)e.albumRollout=null;logCareerMilestones();scoutLabels();if(e.contract&&s.week>=e.contract.ends){e.contractHistory.unshift({...e.contract,ended:s.week});e.contractHistory=e.contractHistory.slice(0,20);milestone('label-'+e.contract.started,'Contract completed',e.contract.name);log(e.contract.name+' contract ended. Your artist income returns to your independent career.');e.contract=null}if(s.week%4===0)createOpportunity();if(s.week%52===0)annualAwards();compactCareer()}
function compactCareer(){for(const a of s.world){for(const x of a.catalog)if(x.uid===undefined)x.uid=a.nextCatalogId++;if(a.catalog.length>60){const keep=a.catalog.map((x,i)=>({x,i})).slice(-60),map=new Map(keep.map((v,i)=>[v.i,i]));a.archivedStreams=(a.archivedStreams||0)+a.catalog.slice(0,-60).reduce((n,x)=>n+(x.total||0),0);for(const {x} of keep)if(x.albumIndex!==undefined)x.albumIndex=map.get(x.albumIndex)??-1;a.catalog=keep.map(v=>v.x)}}for(const kind of ['songs','albums'])for(const [key,r] of Object.entries(s.chartBook[kind].records)){r.history=r.history.slice(r.you?-52:-12);if(!r.you&&s.week-r.lastSeen>26)delete s.chartBook[kind].records[key]}s.expansion.opportunities=s.expansion.opportunities.filter(x=>x.expires>=s.week&&!x.done).slice(-6);s.expansion.awards=s.expansion.awards.slice(-50);for(const b of s.achievements.briefings)if(b.id.startsWith('catalog:')&&s.week-b.week>32){b.body=b.body.split('\n\n')[0];b.detail='Summary archived. Full lifetime records remain in Career.'}if(s.week%26===0&&JSON.stringify(s).length>1500000)addBriefing('save-size:'+s.week,'News','Back up your long career','Your save is approaching the online storage limit. Export a copy from Career → Saves. Your complete player catalog is preserved.');for(const track of s.songs)if(track.released&&s.week-track.released>52){delete track.development;delete track.variation;delete track.appeal} }
function studioPackageInput(){return `<label>Recording budget<select name="package">${studioPackages.map((x,i)=>`<option value="${i}">${x.name} · ${x.fee?money(x.fee)+' upfront · up to +'+x.quality+' quality':'standard $90 single cost'}</option>`).join('')}</select></label><p class="fine">Extra production is paid when writing starts. Skills still matter; equipment cannot guarantee a hit.</p>`}
function tourEstimate(i){const v=venueTiers[i],demand=clamp(.4+level('marketability')*.003+level('stagePresence')*.003+Math.min(1,s.fans/v.fans)*.15,0,1);const sold=Math.round(v.seats*demand);const cost=Math.round(v.cost*(1-level('touring')*.002));return {sold,cost,gross:sold*v.ticket,energy:Math.round(48-level('touring')*.15),review:Math.round(level('stagePresence')*.7+level('charisma')*.3)}}
function tourPage(){return head('Plan your next live run','On the road.')+`<p>Three shows per run. Two slots, energy, and an upfront production budget. Estimates assume your current audience and skills.</p><div class="career-options">${venueTiers.map((v,i)=>{const t=tourEstimate(i);return `<section class="card"><h2>${v.name}</h2><p>${compact(v.fans)} fans required · ${compact(v.seats)} total seats</p>${profileRows([['Projected tickets',fmt(t.sold)],['Upfront budget',money(t.cost)],['Projected gross',money(t.gross)],['Projected profit',money(t.gross-t.cost)],['Time / energy','2 slots / '+t.energy]])}<button class="primary" ${s.fans<v.fans||s.expansion.tourWeek===s.week?'disabled':''} onclick="bookRun(${i})">Review booking</button></section>`}).join('')}</div><p class="fine">One run per week. Demand varies by up to 15%; tax and career overhead apply at week close.</p>`}
function bookRun(i,confirmed=false){if(!saveReady||saveConflict||!venueTiers[i])return;migrateExpansion();const v=venueTiers[i],t=tourEstimate(i);if(s.fans<v.fans||s.expansion.tourWeek===s.week)return;if(!confirmed){modal(`<h2>${v.name}: confirm your run</h2><p>Pay ${money(t.cost)} now. Uses 2 slots and ${t.energy} energy. Projected gross ${money(t.gross)}; actual ticket sales can vary. Unsold seats can mean a loss.</p><button class="primary" onclick="bookRun(${i},true)">Book and perform</button>`);return}if(s.ap<2){toast('You need two slots.');return}if(!spend(t.energy,t.cost))return;s.ap--;const sold=Math.min(v.seats,Math.round(t.sold*rand(.85,1.15))),gross=sold*v.ticket;changeCash(gross);recordIncome('live',gross);const fans=Math.round(sold*(.01+level('stagePresence')*.0002));s.fans+=fans;s.expansion.tourWeek=s.week;s.careerRecords.liveGross+=gross;s.careerRecords.liveProfit+=gross-t.cost;s.careerRecords.tours.push({week:s.week,title:v.name+' run '+(s.careerRecords.tours.length+1),gross,profit:gross-t.cost,fans,review:clamp(t.review+Math.round(rand(-8,8))),tickets:sold});gainXP('touring',60);gainXP('stagePresence',40);milestone('venue-'+i,'Played '+v.name.toLowerCase(),fmt(sold)+' tickets');log(v.name+': '+fmt(sold)+' tickets, '+money(gross-t.cost)+' profit before weekly overhead and tax.');$('modal').close();render();toast('Run complete · '+money(gross-t.cost)+' profit')}
function marketingPage(){const r=s.expansion.albumRollout;return head('Give your next era a plan','Marketing & promotion.')+marketingStudio()+`<section class="card"><details><summary>Catalog campaign budgets</summary><p>Choose the scale of your campaign. Each uses 1 slot and 10 energy. Once per week.</p>${promotionPlans.map((p,i)=>`<div class="row"><div><strong>${p.name}</strong><p>${money(p.cost)} · +${Math.round(p.boost*100)}% reach before audience response</p></div><button class="secondary" ${s.boost>0?'disabled':''} onclick="buyPromotion(${i})">Review</button></div>`).join('')}</details></section><section class="card"><h2>Four-week album rollout</h2>${r?`<p>Active through Week ${r.until}. Lead single: ${esc(s.songs.find(x=>x.id===r.lead)?.title||'Catalog')}.</p>`:`<p>Announce your next album and choose a released lead single. The budget funds four weeks of catalog promotion. Include that lead single on the album and release during the window for +10 cohesion. Cohesion adds up to 10% streams during the album’s first four weeks.</p><form class="form" onsubmit="planRollout(event)"><label>Album campaign name<input name="name" maxlength="55" required></label><label>Lead single<select name="lead">${s.songs.filter(x=>x.released).map(x=>`<option value="${x.id}">${esc(x.title)}</option>`).join('')}</select></label><label>Budget<select name="plan"><option value="0">Grassroots · $200 · +10% each week</option><option value="1">Targeted · $10,000 · +25% each week</option><option value="2">National · $200,000 · +40% each week</option></select></label><button class="primary" ${s.songs.some(x=>x.released)?'':'disabled'}>Review rollout</button></form>`}</section>`}
function buyPromotion(i,confirmed=false){const p=promotionPlans[i];if(!p||s.boost>0)return;if(!confirmed){modal(`<h2>${p.name}</h2><p>Pay ${money(p.cost)} for +${Math.round(p.boost*100)}% catalog reach this week. Uses 1 slot and 10 energy. Results still depend on listeners.</p><button class="primary" onclick="buyPromotion(${i},true)">Launch campaign</button>`);return}if(!spend(10,p.cost))return;s.boost=p.boost;s.expansion.campaignWeek=s.week;$('modal').close();render()}
let pendingRollout=null;
function planRollout(event){event.preventDefault();const f=new FormData(event.target),i=Number(f.get('plan')),lead=Number(f.get('lead'));if(![0,1,2].includes(i)||!s.songs.some(x=>x.id===lead&&x.released))return;pendingRollout={name:String(f.get('name')).slice(0,55),lead,cost:[200,10000,200000][i],boost:[.1,.25,.4][i]};modal(`<h2>Announce ${esc(pendingRollout.name)}?</h2><p>${money(pendingRollout.cost)} upfront · 1 slot · 5 energy. Four weeks of promotion; no automatic album release.</p><button class="primary" onclick="confirmRollout()">Announce rollout</button>`)}
function confirmRollout(){if(!pendingRollout||s.expansion.albumRollout)return;const r=pendingRollout;if(!spend(5,r.cost))return;s.expansion.albumRollout={...r,started:s.week,until:s.week+3};pendingRollout=null;log('Announced '+r.name+' with a four-week rollout.');$('modal').close();render()}
function createOpportunity(){const choices=['Interview','Opening slot','Feature invitation','Festival set'];const type=choices[Math.floor(s.week/4)%choices.length],artist=s.world.filter(a=>a.fans<=Math.max(1000,s.fans*5)&&a.relation>-40).sort((a,b)=>b.fans-a.fans)[0]||s.world[s.world.length-1];const fee=Math.round(100+Math.sqrt(Math.max(1,s.fans))*12);s.expansion.opportunities.push({id:'offer-'+s.week,type,artist:artist.id,name:artist.name,fee,expires:s.week+4,week:s.week});addBriefing('offer:'+s.week,'Opportunity',type+' offer',artist.name+' has an opportunity for you. Review the payment, time, and audience effect in Career → Opportunities.')}
function opportunitiesPage(){return head('Choose your next opening','Opportunities.')+`<p>New offers arrive every four weeks. Offers expire; declining has no penalty.</p>${s.expansion.opportunities.filter(x=>!x.done&&x.expires>=s.week).map(o=>`<section class="card"><span class="eyebrow">Through Week ${o.expires}</span><h2>${esc(o.type)}</h2><p>With ${esc(o.name)} · ${esc(s.world[o.artist].genre)}</p><p>Earn ${money(o.fee)} · 1 slot · 15 energy. ${o.type==='Feature invitation'?'Build your relationship and earn a featured appearance.':'Gain audience exposure based on your charisma.'}</p><button class="primary" onclick="acceptOpportunity('${o.id}')">Review offer</button><button class="secondary" onclick="declineOpportunity('${o.id}')">Decline</button></section>`).join('')||'<section class="card"><p>No active offers. Keep building your career and check after Week '+(Math.floor(s.week/4)*4+4)+'.</p></section>'}`}
function declineOpportunity(id){if(!saveReady||saveConflict)return;const o=s.expansion.opportunities.find(x=>x.id===id);if(o)o.done=true;render()}
function acceptOpportunity(id,confirmed=false){const o=s.expansion.opportunities.find(x=>x.id===id&&!x.done&&x.expires>=s.week);if(!o)return;if(!confirmed){modal(`<h2>${esc(o.type)}</h2><p>Accept ${money(o.fee)} for 1 slot and 15 energy. Earn exposure and +5 relationship with ${esc(o.name)}. Income is included in this week’s finances.</p><button class="primary" onclick="acceptOpportunity('${o.id}',true)">Accept and complete</button>`);return}if(!spend(15))return;o.done=true;changeCash(o.fee);recordIncome('live',o.fee);s.world[o.artist].relation=clamp(s.world[o.artist].relation+5,-100,100);s.fans+=Math.round(20+Math.sqrt(s.fans)*(.1+level('charisma')*.003));if(o.type==='Feature invitation'){s.expansion.featureAppearances=(s.expansion.featureAppearances||0)+1;const a=s.world[o.artist];a.catalog.push({uid:a.nextCatalogId++,title:generate('song')+' (feat. '+s.name+')',type:'Single',week:s.week,base:a.fans*.5,streams:Math.round(a.fans*.5),total:Math.round(a.fans*.5),factor:1})}milestone(o.id,o.type+' completed',o.name);log(o.type+' with '+o.name+': '+money(o.fee)+' earned.');$('modal').close();render()}
function signLabel(i,confirmed=false){const d=labelDeals[i];if(!d||s.labelBusiness?.company||s.expansion.contract||s.fans<d.fans||s.reputation<d.rep)return;if(!confirmed){modal(`<h2>Sign with ${d.name}?</h2><p>Receive ${money(d.advance)} now. For 26 weeks, the label takes ${Math.round(d.share*100)}% of all streaming royalties and adds ${Math.round(d.lift*100)}% reach support. You cannot cancel early. The advance is taxable.</p><button class="primary" onclick="signLabel(${i},true)">Sign 26-week contract</button>`);return}if(!saveReady||saveConflict)return;s.expansion.contract={...d,started:s.week,ends:s.week+25};changeCash(d.advance);recordIncome('wages',d.advance);milestone('signed-'+s.week,'Signed with '+d.name);$('modal').close();render()}
function annualAwards(){const year=Math.ceil(s.week/52),entries=s.songs.filter(x=>x.released> s.week-52&&x.released<=s.week),best=entries.slice().sort((a,b)=>awardScore(b)-awardScore(a))[0];const score=best?awardScore(best):0;const nominated=score>=60,won=nominated&&score>=78&&Math.random()<Math.min(.85,(score-60)/40);const result={year,title:best?.title||null,score:Math.round(score),nominated,won};s.expansion.awards.push(result);s.expansion.awardNominations=(s.expansion.awardNominations||0)+(nominated?1:0);s.expansion.awardWins=(s.expansion.awardWins||0)+(won?1:0);if(nominated){milestone('award-'+year,won?'ENCORE Record Award winner':'ENCORE Record Award nominee',best.title);addBriefing('awards:'+year,'Celebration','Year '+year+' ENCORE Record Awards',best.title+(won?' won Record of the Year.':' earned a Record of the Year nomination.')+' Judged on quality, chart performance, and audience reach.')}}
function awardScore(x){return x.quality*.65+Math.min(20,Math.log10(1+(x.total||0))*2.5)+(x.peak?15*(1-(x.peak-1)/100):0)}
function legacyPage(){return head('The story behind your numbers','Legacy.')+`<section class="card"><h2>ENCORE Record Awards</h2><p>At each 52-week year end, your best song released that year is considered. Score: 65% quality, up to 20 points for lifetime reach, and up to 15 for chart peak. Nomination: 60 points. Winning eligibility: 78; the final panel vote includes chance.</p>${s.expansion.awards.map(a=>`<div class="row"><span>Year ${a.year} · ${esc(a.title||'No eligible release')}</span><strong>${a.won?'Winner':a.nominated?'Nominee':'No nomination'} · ${a.score}</strong></div>`).join('')||'<p>Your first awards season arrives at Week 52.</p>'}</section><section class="card"><h2>Career timeline</h2><p class="fine">Most recent 200 milestones. Award detail retains 50 years; lifetime win and nomination totals remain in your profile.</p>${s.expansion.timeline.slice().reverse().map(x=>`<div class="story"><small>WEEK ${x.week}</small><strong>${esc(x.title)}</strong><p>${esc(x.detail)}</p></div>`).join('')||'<p>Your next milestone starts the story.</p>'}</section>`}
function careerTools(){return `<div class="chips">${['Touring','Campaigns','Opportunities','Labels','Legacy','Saves'].map(t=>`<button class="${careerTab===t?'selected':''}" onclick="careerTab='${t}';render()">${t}</button>`).join('')}</div>`}

