/* Visual catalog identity is permanent; limited offers rotate by simulated month. */
const editionNames=['After Hours','City Lights','First Edition','Midnight Series','Studio Collection','Golden Era'];
const merchandiseLooks=['Midnight / gold soundwave','Ivory / cobalt geometry','Burgundy / botanical'];
for(const x of [{id:'roadster',name:'Vesper open-top roadster',kind:'Cars',price:165000,drift:-.009,vol:.035,icon:'car',desc:'An open-top grand tourer. A seasonal collector choice with continuing depreciation and upkeep.'},{id:'penthouse',name:'Cityline penthouse',kind:'Property',price:1750000,drift:.002,vol:.025,icon:'house',rent:8200,desc:'A city penthouse with a private terrace. Rental demand and maintenance still matter.'},{id:'sapphire',name:'Sapphire pendant',kind:'Jewelry',price:115000,drift:.001,vol:.04,icon:'gem',desc:'An original sapphire and diamond pendant. Collector premiums fluctuate.'}])if(!wealthItems.some(w=>w.id===x.id))wealthItems.push(x);
function personPhoto(key,name,large=false){const cast={'agent-maya':0,'agent-dev':4,'agent-celeste':7,'agent-roman':6,'agent-june':3,'agent-nico':2},hash=Array.from(String(key)).reduce((n,c)=>(n*31+c.charCodeAt(0))>>>0,7),index=cast[key]??hash%8;return `<span class="person-photo ${large?'portrait-large':''}" role="img" aria-label="Illustrated fictional portrait of ${esc(name)}" style="background-image:url('${CAST_ART}');background-position:${index%4*100/3}% ${index<4?0:100}%"></span>`}
function merchPhoto(id,look=0){const safe=Number.isInteger(look)&&look>=0&&look<3?look:0;return `<div class="merch-photo" role="img" aria-label="${esc(merchItems.find(m=>m[0]===id)?.[1]||'Merchandise')}: ${merchandiseLooks[safe]}" style="background-image:url('${MERCH_ART[id]||''}');background-position:${safe*50}% center"></div>`}
function merchChoices(id){return `<fieldset class="merch-choices"><legend>Choose your visual edition</legend>${merchandiseLooks.map((name,i)=>`<label class="merch-look">${merchPhoto(id,i)}<span><input type="radio" name="look" value="${i}" ${i===0?'checked':''}> ${name}</span></label>`).join('')}</fieldset><p class="fine">Three distinct visual editions per product. Artwork changes appearance, not demand or production cost.</p>`}
function migrateCollection(){s.collection??={purchased:[]}}
function currentDrops(){const items=wealthItems.filter(x=>!marketInstrument(x.id)),month=s.empire.month;return Array.from({length:6},(_,i)=>{const item=items[(month*5+i*2)%items.length],edition=editionNames[(month+i)%editionNames.length];return {id:month+'-'+i,month,item:item.id,name:item.name+' · '+edition,price:cents(item.price*(1.05+(i%3)*.04)),edition}})}
function collectionDrops(){migrateCollection();return `<section class="card collection-drop"><span class="eyebrow">CURATED RELEASE · ${careerDate()}</span><h2>This month’s limited collection</h2><p>Six rotating offers. One purchase per offer. Availability ends when you advance the month; owned editions stay in your collection. Collector premiums do not guarantee higher resale value.</p><div class="wealth-grid">${currentDrops().map(d=>{const item=wealthItems.find(x=>x.id===d.item),sold=s.collection.purchased.includes(d.id);return `<button class="asset-tile" ${sold?'disabled':''} onclick="reviewDrop('${d.id}')">${assetPhoto(item)}<small>LIMITED · THIS MONTH</small><h3>${esc(d.name)}</h3><strong>${money(d.price)}</strong><p>${sold?'Acquired':'Review purchase →'}</p></button>`}).join('')}</div></section>`}
let pendingDrop=null;
function reviewDrop(id){migrateCollection();const d=currentDrops().find(d=>d.id===id);if(!labelActive()||!d||s.collection.purchased.includes(id))return;const item=wealthItems.find(x=>x.id===d.item),tax=cents(d.price*(item.kind==='Property'?.02:.08));pendingDrop={...d,tax,total:cents(d.price+tax)};modal(`${assetPhoto(item)}<h2>${esc(d.name)}</h2>${profileRows([['Price',money(d.price)],['Purchase tax',money(tax)],['Total',money(d.price+tax)],['Availability','Ends at next month advance']])}<p>5 energy. One unit. Initial resale valuation uses the standard item price; the edition premium and purchase tax are included in cost basis. Owned items never expire.</p><button class="primary" onclick="confirmDrop()">Confirm purchase</button>`)}
function confirmDrop(){const d=pendingDrop;if(!labelActive()||!d||d.month!==s.empire.month||!currentDrops().some(x=>x.id===d.id)||s.collection.purchased.includes(d.id)){pendingDrop=null;toast('This offer is no longer available.');return}if(s.empire.assets.length>=5000){toast('Your collection has reached its holding limit.');return}if(s.cash<d.total){toast('Not enough cash.');return}if(!spend(5))return;const item=wealthItems.find(x=>x.id===d.item);changeCash(-d.total);s.empire.assets.push({id:s.empire.nextId++,item:d.item,name:d.name,kind:item.kind,qty:1,basis:d.total,value:item.price,condition:100,tenant:null,rent:item.rent||0,arrears:0,renovated:0,edition:d.edition,editionId:d.id});s.collection.purchased.push(d.id);s.collection.purchased=s.collection.purchased.slice(-120);moneyEvent('Acquired '+d.name,-d.total);pendingDrop=null;$('modal').close();render()}
