const teamCandidates=[
{id:'m1',role:'Manager',name:'Morgan Vale',salary:1200,skill:45,risk:.02,desc:'Steady guidance: adds 9% recording reach while paid.'},
{id:'m2',role:'Manager',name:'Sasha Gold',salary:5000,skill:90,risk:.015,desc:'An established network: adds 18% recording reach.'},
{id:'m3',role:'Manager',name:'Lex Royale',salary:800,skill:70,risk:.18,desc:'Big promises at a low fee. Strong reach, but a high risk of mishandling funds.'},
{id:'a1',role:'Accountant',name:'Jun Park',salary:600,skill:50,risk:.01,desc:'Cuts career operating overhead by 10%. Keeps a clear monthly ledger.'},
{id:'a2',role:'Accountant',name:'Ari Stone',salary:1800,skill:95,risk:.005,desc:'Cuts operating overhead by 19%; taxes still apply to earned profit.'},
{id:'a3',role:'Accountant',name:'Blake Rush',salary:300,skill:25,risk:.15,desc:'Budget bookkeeping with a higher risk of costly errors.'},
{id:'f1',role:'Financial adviser',name:'Noor Ellis',salary:1500,skill:70,risk:.02,desc:'Reduces monthly stock, bond and crypto volatility by 28%; cannot prevent losses.'},
{id:'f2',role:'Financial adviser',name:'Jules Fox',salary:400,skill:40,risk:.16,desc:'Reduces market volatility by 16%, with substantial handling risk.'},
{id:'s1',role:'Social manager',name:'River Lane',salary:900,skill:50,risk:.03,desc:'Adds 500 engaged followers each funded month and improves social post reach.'},
{id:'s2',role:'Social manager',name:'Remy Sun',salary:3500,skill:90,risk:.01,desc:'Adds 900 engaged followers monthly; increases post reach through better distribution.'},
{id:'security',role:'Security',name:'Shield Advisory',salary:2500,skill:90,risk:.005,desc:'Reduces the chance of an extortion attempt by 90%. Does not guarantee safety.'}
];
function teamEffect(role){const t=s.empire?.staff[role];return t?.funded?(teamCandidates.find(x=>x.id===t.id)?.skill||0):0}
function teamPage(){return head('Choose who gets access','Your team.')+`<p class="fine">One specialist per role. Salaries charge at monthly advance. Unaffordable staff pause without charging. Replacements take effect next month; all risks shown are monthly.</p>${teamCandidates.map(t=>`<section class="card staff-card"><span class="asset-art">${assetIcon(t.role==='Accountant'?'bond':t.role==='Financial adviser'?'stock':'watch')}</span><div><span class="eyebrow">${t.role}</span><h2>${t.name}</h2><p>${t.desc}</p><p>${money(t.salary)} / month · ${+(t.risk*100).toFixed(1)}% handling risk</p><button class="${s.empire.staff[t.role]?.id===t.id?'secondary':'primary'}" onclick="hireTeam('${t.id}')">${s.empire.staff[t.role]?.id===t.id?'Dismiss':'Review hire'}</button></div></section>`).join('')}<section class="card"><h2>Security desk</h2>${s.empire.threat?`<p>An anonymous party is demanding ${money(s.empire.threat.amount)}. Payment does not guarantee protection from future attempts.</p><button class="secondary" onclick="resolveThreat('report')">Report & secure accounts · $500</button><button class="secondary" onclick="resolveThreat('ignore')">Ignore the demand</button><button class="secondary" onclick="resolveThreat('pay')">Review payment</button>`:'<p>No active threat.</p>'}</section>`}
function hireTeam(id,confirmed=false){const t=teamCandidates.find(x=>x.id===id);if(!labelActive()||!t)return;const dismiss=s.empire.staff[t.role]?.id===id;if(!confirmed){modal(`<h2>${dismiss?'Dismiss':'Hire'} ${t.name}?</h2><p>${dismiss?'Future salary ends.':'Monthly salary '+money(t.salary)+'. Replaces any current '+t.role.toLowerCase()+'.'} 5 energy. Monthly handling risk ${t.risk*100}%; a bad incident can cost up to twice their salary.</p><button class="primary" onclick="hireTeam('${id}',true)">Confirm</button>`);return}if(!spend(5))return;if(dismiss)delete s.empire.staff[t.role];else s.empire.staff[t.role]={id,funded:false};$('modal').close();render()}
function settleTeam(){for(const hired of Object.values(s.empire.staff)){const t=teamCandidates.find(x=>x.id===hired.id);hired.funded=s.cash>=t.salary;if(!hired.funded){log(t.name+' paused: insufficient payroll funds.');continue}changeCash(-t.salary);s.finance.week.expenses+=t.salary;moneyEvent(t.name+' monthly salary',-t.salary);if(Math.random()<t.risk){const loss=Math.min(Math.max(0,s.cash),Math.round(t.salary*rand(.5,2)));changeCash(-loss);hired.funded=false;moneyEvent(t.name+' handling incident',-loss);addBriefing('staff:'+t.id+':'+s.week,'News','Your team needs attention',t.name+' caused a '+money(loss)+' loss and provided no benefit this month. Review this hire in Team.')}else if(t.role==='Social manager'){s.social.followers+=t.skill*10;log(t.name+' brought '+t.skill*10+' followers to PULSE.')}}}
function rollThreat(){if(s.empire.threat||s.cash<100000||Math.random()>.08*(1-teamEffect('Security')/100))return;s.empire.threat={amount:Math.min(500000,Math.round(s.cash*.015)),week:s.week};addBriefing('threat:'+s.week,'News','A demand reached your team','Review the security desk in Team. You can report, ignore or pay; no option guarantees an outcome.')}
function resolveThreat(choice,confirmed=false){const t=s.empire.threat;if(!labelActive()||!t)return;const cost=choice==='pay'?t.amount:choice==='report'?500:0;if(!confirmed){modal(`<h2>${choice==='pay'?'Pay the demand':choice==='report'?'Report & secure accounts':'Ignore the demand'}?</h2><p>${money(cost)} · 5 energy. ${choice==='report'?'Closes this incident with professional support.':choice==='ignore'?'A 25% chance of a publicity incident that loses 1% of fans.':'Closes this incident, but does not prevent future demands.'}</p><button class="primary" onclick="resolveThreat('${choice}',true)">Confirm</button>`);return}if(!['pay','report','ignore'].includes(choice)||!spend(5,cost))return;if(choice==='ignore'&&Math.random()<.25)s.fans=Math.round(s.fans*.99);s.empire.threat=null;log('Security incident resolved: '+choice+'.');$('modal').close();render()}
const merchItems=[['tee','Tour tee',12,30],['hoodie','Heavyweight hoodie',28,70],['cap','Embroidered cap',9,25],['vinyl','Collector vinyl',16,45],['poster','Signed art print',5,20],['zine','Era photo book',14,40],['tote','Canvas tote',7,22],['box','Deluxe collector box',55,150]];
function commercePage(){return head('Beyond the recording','Commerce & media.')+`<section class="card"><h2>360 coverage</h2><p>Active 360 deals share touring, merchandise and media gross at the negotiated rate. Production costs are yours. Investments and rental income are excluded.</p><button class="secondary" onclick="careerTab='Touring';render()">Tour planner</button></section><div class="wealth-grid">${merchItems.map(m=>`<button class="asset-tile" onclick="merchForm('${m[0]}')"><span class="asset-art">${assetIcon(m[0]==='poster'?'art':'gem')}</span><h2>${m[1]}</h2><p>${money(m[2])} production per unit · Suggested price ${money(m[3])}. Set your own quantity and price.</p><strong>Create product →</strong></button>`).join('')}</div><section class="card"><h2>Inventory</h2>${s.empire.merch.map(m=>`<div class="row"><span>${esc(m.name)} · ${m.stock} left · ${m.sold} sold</span><strong>${money(m.price)}</strong></div>`).join('')||'<p>No merchandise produced.</p>'}</section><section class="card"><h2>Media offers</h2>${s.empire.media.filter(o=>!o.used&&o.expires>=s.week).map(o=>`<div class="project-row"><div><strong>${esc(o.name)}</strong><small>${money(o.fee)} · 15 energy · ${o.rounds} counters</small></div><button class="primary" onclick="reviewMedia(${o.id})">Review offer</button></div>`).join('')||'<p>Build at least 1,000 fans for podcast, sponsorship, licensing and campaign opportunities.</p>'}</section>`}
function merchForm(id){const m=merchItems.find(x=>x[0]===id);if(!m)return;modal(`<h2>${m[1]}</h2><form class="form" onsubmit="createMerch(event,'${id}')"><label>Units<input name="qty" type="number" min="1" max="1000000" value="100" required></label><label>Sale price ($)<input name="price" type="number" min="1" max="100000" step="0.01" value="${m[3]}" required></label><p>${money(m[2])} per unit upfront · 10 energy. Unsold inventory persists. Higher prices lower demand; production does not guarantee sales.</p><button class="primary">Review production</button></form>`)}
let pendingMerch=null;
function createMerch(e,id){e.preventDefault();const m=merchItems.find(x=>x[0]===id),f=new FormData(e.target),qty=Number(f.get('qty')),price=Number(f.get('price'));if(!m||!Number.isInteger(qty)||qty<1||qty>1e6||!Number.isFinite(price)||price<1||price>100000)return;pendingMerch={item:id,name:m[1],stock:qty,sold:0,price,cost:qty*m[2]};modal(`<h2>Produce ${qty} ${m[1]}?</h2><p>${money(pendingMerch.cost)} upfront · 10 energy. Price ${money(price)} per unit. An active 360 share applies to sales gross.</p><button class="primary" onclick="confirmMerch()">Confirm production</button>`)}
function confirmMerch(){if(!labelActive()||!pendingMerch||!spend(10,pendingMerch.cost))return;s.empire.merch.push({...pendingMerch,id:s.empire.nextId++});pendingMerch=null;$('modal').close();render()}
function reviewMedia(id){const o=s.empire.media.find(x=>x.id===id&&!x.used&&x.expires>=s.week);if(!o)return;modal(`<h2>${esc(o.name)}</h2><p>Fee ${money(o.fee)} · 15 energy. Taxable career income; an active 360 share applies. You can request up to ${money(o.max)} based on fans, reputation and social influence.</p><form onsubmit="counterMedia(event,${id})"><label>Your requested fee<input name="fee" type="number" min="1" value="${o.fee}" required></label><button class="secondary">Send counter · 5 energy</button></form><button class="primary" onclick="acceptMedia(${id})">Accept & perform</button><button class="secondary" onclick="declineMedia(${id})">Decline</button>`)}
function counterMedia(e,id){e.preventDefault();const o=s.empire.media.find(x=>x.id===id&&!x.used&&x.expires>=s.week),fee=Number(new FormData(e.target).get('fee'));if(!o||!Number.isSafeInteger(fee)||fee<1||!spend(5))return;o.fee=Math.min(fee,o.max);o.rounds++;render();reviewMedia(id)}
function acceptMedia(id){const o=s.empire.media.find(x=>x.id===id&&!x.used&&x.expires>=s.week);if(!o||!spend(15))return;o.used=true;changeCash(o.fee);recordIncome('live',o.fee);moneyEvent(o.name+' fee',o.fee);$('modal').close();render()}
function declineMedia(id){if(!labelActive())return;const o=s.empire.media.find(x=>x.id===id);if(o)o.used=true;$('modal').close();render()}
function settleCommerce(){const active=s.empire.merch.filter(m=>m.stock>0);for(const m of active){const spec=merchItems.find(x=>x[0]===m.item),demand=Math.max(0,Math.floor(s.fans*.015/Math.max(1,active.length)*Math.pow(spec[3]/m.price,2)*rand(.6,1.3))),sold=Math.min(m.stock,demand),gross=cents(sold*m.price);m.stock-=sold;m.sold+=sold;changeCash(gross);recordIncome('live',gross);if(sold)moneyEvent(m.name+' sales',gross)}if(s.fans>=1000){const fee=Math.max(200,Math.round(s.fans*.015*(1+socialLeverage()))),o={id:s.empire.nextId++,name:pick(['Podcast appearance','Lifestyle brand campaign','Film sync licence','Festival media interview','Fashion editorial partnership']),fee,max:Math.round(fee*(1.2+s.reputation/200+socialLeverage()*.3)),rounds:0,expires:s.week+9,used:false};s.empire.media.push(o);addBriefing('media:'+o.id,'Opportunity','A media offer arrived',o.name+' offered '+money(fee)+'. Review, counter or decline in Commerce & media.')}s.empire.media=s.empire.media.filter(o=>o.expires>=s.week).slice(-20)}
