/* ENCORE Empire · career team, ethics, payroll and fictional pressure events */
const empireStaffRoles={
manager:{name:'Career Manager',salary:[2200,9500],detail:'Negotiates opportunities, protects leverage and can open doors—or steer you into bad deals.',boost:'Negotiation & opportunities'},
accountant:{name:'CPA / Tax Advisor',salary:[1800,7200],detail:'Handles books, tax planning and financial controls. High ethics matters as much as skill.',boost:'Tax efficiency & fraud detection'},
business:{name:'Business Manager',salary:[2500,10000],detail:'Coordinates cash, investments and large purchases. Weak ethics creates financial risk.',boost:'Asset costs & wealth management'},
social:{name:'Social Media Manager',salary:[1200,6500],detail:'Improves content strategy, engagement and conversion from followers into listeners.',boost:'Follower growth & engagement'},
publicist:{name:'Publicist',salary:[1800,8000],detail:'Shapes press narratives, handles crises and raises media opportunities.',boost:'Reputation & media deals'},
lawyer:{name:'Entertainment Lawyer',salary:[3000,12000],detail:'Reviews contracts, buyouts, rights and disputes. Strong lawyers improve exit terms.',boost:'Contracts & buyouts'},
security:{name:'Security Director',salary:[2200,9000],detail:'Reduces high-profile pressure events and protects the artist and team.',boost:'Risk prevention'}
};
function empireStaffCandidate(role,index){const cfg=empireStaffRoles[role],r=empireRandom(empireHash('STAFF-'+role+'-'+index)),name=pickDet(nameWords.first,r)+' '+pickDet(nameWords.last,r),skill=Math.round(48+r()*50),ethics=Math.round(35+r()*65),loyalty=Math.round(40+r()*60),connections=Math.round(30+r()*68),salary=Math.round((cfg.salary[0]+r()*(cfg.salary[1]-cfg.salary[0]))/100)*100;return {id:role+'-'+index,role,name,skill,ethics,loyalty,connections,salary}}
function empireStaffEffect(role,key='skill'){const x=s.empire?.staff?.[role];return x?Number(x[key]||0):0}
function empireWeeklyPayroll(){return Object.values(s.empire?.staff||{}).reduce((n,x)=>n+(x?.salary||0),0)}
function empireHireStaff(role,index){migrateEmpire();const c=empireStaffCandidate(role,index);if(!empireStaffRoles[role])return;s.empire.staff[role]=c;s.empire.staffHistory.unshift({week:s.week,type:'hired',role,name:c.name});log('Hired '+c.name+' as '+empireStaffRoles[role].name+'.');render()}
function empireFireStaff(role){migrateEmpire();const x=s.empire.staff[role];if(!x)return;s.empire.staffHistory.unshift({week:s.week,type:'fired',role,name:x.name});delete s.empire.staff[role];log('Ended '+x.name+'’s '+empireStaffRoles[role].name+' role.');render()}
function empireStaffWeek(){migrateEmpire();const e=s.empire;if(e.lastStaffWeek===s.week)return;e.lastStaffWeek=s.week;const payroll=empireWeeklyPayroll();if(payroll){changeCash(-payroll);s.finance.week.expenses=cents(s.finance.week.expenses+payroll);e.lastPayroll={week:s.week,total:payroll}}for(const [role,x] of Object.entries(e.staff)){if(!x)continue;if(x.ethics<55&&Math.random()<(.025+(55-x.ethics)*.0012)){const loss=Math.min(Math.max(500,Math.round(Math.max(0,s.cash)*(.0015+Math.random()*.006))),180000);if(loss>0&&s.cash>loss){changeCash(-loss);e.staffHistory.unshift({week:s.week,role,name:x.name,type:'irregularity',amount:loss});const detect=.25+empireStaffEffect('accountant')*.006;if(Math.random()<detect)addBriefing('staff-loss-'+role+'-'+s.week,'News','Financial irregularity detected',x.name+' generated '+money(loss)+' in unexplained costs.','A stronger accountant improves detection. You can dismiss staff from Career → Team.')}}}}
function empireRiskWeek(){migrateEmpire();const e=s.empire;if(e.lastRiskWeek===s.week)return;e.lastRiskWeek=s.week;const fame=Math.log10(Math.max(10,s.fans)),worth=Math.log10(Math.max(10,empireNetWorth?.()||s.cash)),security=empireStaffEffect('security')/100,chance=Math.max(0,(fame+worth-10)*.0045)*(1-security*.75);if(Math.random()>chance)return;const demand=Math.round(clamp((empireNetWorth?.()||s.cash)*.0015,2500,350000)),id='pressure-'+s.week+'-'+Date.now(),event={id,week:s.week,demand,status:'open',detail:'An unknown party is trying to pressure your team for money. This is a fictional career-risk event.'};e.pressureEvents??=[];e.pressureEvents.unshift(event);empirePushDeal({id,type:'pressure',title:'Private pressure attempt',detail:event.detail,expires:s.week+2,status:'open'})}
function empireResolvePressure(id,choice){migrateEmpire();const t=(s.empire.pressureEvents||[]).find(x=>x.id===id&&x.status==='open');if(!t)return;const lawyer=empireStaffEffect('lawyer')/100,security=empireStaffEffect('security')/100;if(choice==='pay'){if(s.cash<t.demand){toast('Not enough cash.');return}changeCash(-t.demand);t.status='paid';log('Your team paid '+money(t.demand)+' to end the pressure attempt.')}if(choice==='security'){const cost=Math.round(t.demand*.18);if(s.cash<cost){toast('Not enough cash.');return}changeCash(-cost);s.finance.week.expenses=cents(s.finance.week.expenses+cost);const success=Math.random()<.55+security*.35+lawyer*.1;t.status=success?'resolved':'public';if(!success){s.reputation=clamp(s.reputation-2);addBriefing('pressure-public-'+s.week,'News','Private dispute became public','The situation leaked into public view. Reputation −2.','Stronger legal and security staff improve future outcomes.')}}if(choice==='legal'){const cost=Math.round(t.demand*.12);if(s.cash<cost){toast('Not enough cash.');return}changeCash(-cost);s.finance.week.expenses=cents(s.finance.week.expenses+cost);t.status=Math.random()<.5+lawyer*.45?'resolved':'public';if(t.status==='public')s.reputation=clamp(s.reputation-1)}const d=s.empire.deals.find(x=>x.id===id);if(d)d.status='resolved';render()}
function empireTaxMultiplier(){const acct=empireStaffEffect('accountant');return acct?Math.max(.88,1-acct*.0012):1}
