/* ENCORE Empire UI and expanded negotiations. */
let empireTab='Overview',empireWealthCategory='Cars',universeFeaturePage=0,ownArtistFileContext=null;
try{icons.push('<path d="M4 20h16M6 20V9l6-5 6 5v11M9 20v-6h6v6M4 9h16"/>')}catch{}
function ensureEmpireStyles(){if(document.getElementById('empire-styles'))return;const el=document.createElement('style');el.id='empire-styles';el.textContent=`
.empire-hero{display:grid;grid-template-columns:1.4fr .8fr;gap:18px;padding:26px;border:1px solid var(--line);border-radius:20px;background:linear-gradient(135deg,var(--panel),#202630);margin-bottom:20px}.empire-hero strong.big{display:block;font-size:clamp(34px,7vw,62px);letter-spacing:-2px}.empire-tabs{display:flex;gap:8px;overflow:auto;padding:3px 0 18px}.empire-tabs button{white-space:nowrap}.empire-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.empire-card{background:var(--panel);border:1px solid var(--line);border-radius:16px;padding:18px}.empire-card h3{margin-top:10px}.asset-icon{width:64px;height:64px;border-radius:15px;border:1px solid var(--line);background:#24272d;padding:12px}.asset-icon svg{width:100%;height:100%;fill:none;stroke:currentColor;stroke-width:1.8;stroke-linecap:round;stroke-linejoin:round}.asset-card{display:flex;flex-direction:column;gap:7px}.asset-card .primary,.asset-card .secondary{width:100%}.asset-price{font-size:25px;font-weight:750}.offer-strip{display:flex;justify-content:space-between;gap:14px;align-items:center;border:1px solid var(--line);border-radius:13px;padding:15px;margin:10px 0}.offer-strip>div{min-width:0}.offer-strip small{display:block;color:var(--muted)}.social-platform{display:grid;grid-template-columns:58px 1fr auto;gap:15px;align-items:center}.platform-mark{height:52px;width:52px;border-radius:14px;display:grid;place-items:center;background:var(--lime);color:#172009;font-weight:900;font-size:22px}.staff-score{display:grid;grid-template-columns:repeat(3,1fr);gap:6px;margin:12px 0}.staff-score span{border:1px solid var(--line);border-radius:9px;padding:8px;text-align:center;font-size:12px}.catalog-right{display:grid;grid-template-columns:1.3fr .7fr auto;gap:14px;align-items:center}.file-cover{min-height:210px;border:1px solid var(--line);border-radius:18px;padding:25px;background:linear-gradient(160deg,#1b1d21,#272b34);display:flex;flex-direction:column;justify-content:flex-end}.file-cover .monogram{font-size:70px;font-weight:900;line-height:.8;opacity:.2}.delta-positive{color:var(--lime)}.delta-negative{color:#ff8585}.feature-stack{display:flex;gap:7px;flex-wrap:wrap;margin:9px 0}.feature-chip{border:1px solid var(--line);border-radius:999px;padding:7px 10px;font-size:12px;background:#202227}.universe-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px;max-height:58vh;overflow:auto}.universe-card{border:1px solid var(--line);border-radius:12px;padding:12px}.wealth-number{font-size:28px;font-weight:750}.mini-bar{height:7px;background:#34373d;border-radius:99px;overflow:hidden}.mini-bar i{display:block;height:100%;background:var(--lime)}
@media(max-width:800px){.empire-hero,.empire-grid{grid-template-columns:1fr}.social-platform{grid-template-columns:52px 1fr}.social-platform .controls{grid-column:1/-1}.catalog-right{grid-template-columns:1fr}.universe-grid{grid-template-columns:1fr}.offer-strip{align-items:flex-start;flex-direction:column}}
`;document.head.appendChild(el)}
function empireIcon(category){const paths={Cars:'<path d="M4 15l2-6h12l2 6v4h-2v-2H6v2H4z"/><circle cx="7" cy="15" r="1.5"/><circle cx="17" cy="15" r="1.5"/>',Jewelry:'<path d="M7 5h10l3 4-8 10L4 9z"/><path d="M4 9h16M8 5l4 14 4-14"/>',Homes:'<path d="M3 11l9-7 9 7v9h-6v-6H9v6H3z"/>',Art:'<rect x="4" y="4" width="16" height="16" rx="1"/><path d="M7 16l4-5 3 3 3-4"/><circle cx="9" cy="8" r="1"/>',Stocks:'<path d="M4 18l5-6 4 3 7-9"/><path d="M16 6h4v4"/>',Bonds:'<rect x="4" y="5" width="16" height="14" rx="2"/><path d="M7 9h10M7 13h6M7 16h8"/>',Crypto:'<circle cx="12" cy="12" r="9"/><path d="M9 7h5a3 3 0 010 6H9m0 0h6a3 3 0 010 6H9M12 5v14"/>','Real Estate':'<path d="M5 21V8h10v13M15 12h4v9M8 11h2M8 15h2M12 11h1M12 15h1"/>'};return `<div class="asset-icon"><svg viewBox="0 0 24 24" aria-hidden="true">${paths[category]||paths.Stocks}</svg></div>`}
function setEmpireTab(t){empireTab=t;render();window.scrollTo(0,0)}
function empireNav(){const tabs=['Overview','Social','Deals','Catalog','Wealth','Staff','Merch','Artist File'];return `<div class="empire-tabs">${tabs.map(t=>`<button class="${empireTab===t?'primary':'secondary'}" onclick="${t==='Artist File'?'openOwnArtistFile()':`setEmpireTab('${t}')`}">${t}</button>`).join('')}</div>`}
function empirePage(){migrateEmpire();ensureEmpireStyles();const top=head('Career, ownership & wealth','Empire.',`<span class="pill">Net worth ${money(empireNetWorth())}</span>`)+empireNav();const page={Overview:empireOverview,Social:empireSocial,Deals:empireDeals,Catalog:empireCatalog,Wealth:empireWealth,Staff:empireStaffPage,Merch:empireMerchPage,'Artist File':ownArtistFilePage}[empireTab]||empireOverview;return top+page()}
