/* Persistent help, per-career onboarding and deterministic in-game navigation. */
let routeTrail=[],lastRoute=null,routeReturning=false;
function routeSnapshot(){return {tab,careerTab,industryTab,chartKind,chartMine,filter,genreFilter}}
function rememberRoute(){const next=routeSnapshot();if(lastRoute&&JSON.stringify(next)!==JSON.stringify(lastRoute)&&!routeReturning&&tourStep<0){routeTrail.push(lastRoute);routeTrail=routeTrail.slice(-40)}lastRoute=next;routeReturning=false}
function goBack(){if(tourStep>=0){if(tourStep>0)openTour(tourStep-1);else endTour();return}if($('modal').open){$('modal').close();return}const previous=routeTrail.pop();if(previous){({tab,careerTab,industryTab,chartKind,chartMine,filter,genreFilter}=previous);routeReturning=true;render();window.scrollTo?.(0,0)}else if(tab!=='Home'){tab='Home';routeReturning=true;render()}else showTitle()}
function migrateGuidance(){s.onboarding??={version:1,seen:!!s.started};}
function screenFamily(){if(tab==='Home')return 'backstage';if(tab==='Create'||tab==='Stats')return 'studio';if(tab==='Guide'||tab==='Menu'||tab==='Artist')return 'library';if(tab==='Industry')return industryTab==='Charts'?'charts':'social';if(tab==='ArtistFile')return 'wealth';if(tab==='Career'){if(['Social','Location'].includes(careerTab))return 'social';if(['Wealth','Properties','Finances','Profile'].includes(careerTab))return 'wealth';if(careerTab==='Market')return 'exchange';if(['Deals','Labels','League','Agency','Team','Commerce','Opportunities'].includes(careerTab))return 'business';if(['Releases','Campaigns','Touring'].includes(careerTab))return 'studio';return 'library'}return 'library'}
function navigationTools(){return `<div class="navigation-tools"><button class="secondary" onclick="goBack()" aria-label="Back to previous screen">← Back</button><span class="section-identity">${screenFamily().toUpperCase()}</span><button class="secondary" onclick="go('Guide')">Guide ?</button><button class="text-button" onclick="openSettings()" aria-label="Open settings">Settings</button></div>`}
const guideTopics=[
['First steps','Home','Choose a background, genre and city. Backgrounds give different starting skills. Work shifts fund your early records; open mics build fans and Stage Presence. Your normal career and sandbox have separate saves.'],
['Energy and months','Home','You have 200 energy. Actions show their costs before you commit. Rest restores up to 40 once per month. Advance month refills energy and resolves four or five chart weeks, income, taxes, staff and rentals. Unfinished songs stay saved.'],
['Make a song','Create','Pick a title, direction, production budget and creative brief. Writing costs 10 energy plus your chosen production fee. Recording choices cost $40–$120 and 15–25 energy; mixing costs $30–$110 and 15–25 energy. A single release costs $20 and 5 energy. The minimum full route is $90 and 45 energy, before extra production and features.'],
['Features and albums','Create','Add up to six guests directly from the active project. Relationships, audience and reputation affect access and price. Park a song to work on another. Keep finished recordings for an album; an album needs at least three tracks. Select your songs and sale price before confirming.'],
['Training','Stats','Writing, Recording and Producing shape quality. Charisma and Marketability affect appeal, with Stage Presence, Touring and Viral Ability underneath Marketability. Training changes future work, not finished recordings. Elite levels require more XP.'],
['Charts and certifications','Industry','Charts resolve each internal week during a monthly advance. Movement, debut, peak and weeks charting reflect competition. Certifications use accumulated performance. Songs can enter later; good quality alone does not guarantee a hit.'],
['PULSE conversations','Social','Write posts, like artist posts and type replies. Fans and artists use simulated authored responses. You can refresh a conversation to see replies. Followers differ from true fans; engagement contributes to label discovery and bargaining.'],
['Cities and discovery','Location','Your city affects local genre fit and discovery. One showcase per month costs $50 and 20 energy and builds local connections. Relocation costs $1,000 and 20 energy and halves local connections; your fans stay.'],
['Label contracts','Deals','Labels propose recording, distribution or 360 structures. Counter the advance, share and duration, or decline; artists cannot request a different deal type. Your own label can propose all three types to its artists. Rivals can bid while you are signed. Switching can require a buyout. A 360 share covers music and live/merch/media income; investments are excluded.'],
['Agents and staff','Agency','An agent charges a negotiated commission on royalties, album sales and live income. Staff earn monthly salaries. Benefits require funded staff. Misconduct can occur; investigate agent withdrawals and review risky hires. Dismissal and investigations show costs before confirmation.'],
['Market and wealth','Market','The exchange is fictional. Quotes fluctuate while actively playing and during advances; limit orders reserve neither cash nor units. Trades have fees, and realized gains enter game taxes. Physical assets revalue monthly and may need upkeep. Prices can fall.'],
['World tours','Touring','Book 8–160 shows with custom ticket prices. Eight shows resolve per month. Fans, loyalty, performance and engaged social reach drive demand; followers are not automatically ticket buyers. Pay a launch deposit and production costs. Insufficient production funds pause shows. Ticket gross is before label/agent shares, overhead and taxes.'],
['Merchandise','Commerce','Choose a product and visual edition, enter quantity and price, then review production cost. Stock remains until sold. High prices reduce demand. Unsold stock and production costs are real risks; an active 360 share applies to gross sales.'],
['Property management','Properties','Screen tenants, compare rent and reliability, and manage renovation and maintenance. Larger buildings currently use aggregate tenancy rather than individual apartment households. Occupied properties must finish leases before sale.'],
['Saves and recovery','Saves','Autosave uses this browser’s career identity. Export a JSON backup before switching devices or clearing browser data. Imports replace only the current mode after confirmation. Recovery is one rotating snapshot; keep external exports. Offline is a separate edition with import/export.'],
['How to navigate','Menu','The bottom bar opens Studio, PULSE, Home, Stats and Menu. Menu searches every destination. Back returns through visited screens; on Home with no history it returns to the title. Dialogs have a Back arrow and a Close button. Guide is always available.'],
['Sandbox','Menu','The sandbox is a separate test career with abundant resources and an editor. Test changes there without replacing your normal career. The economy is deliberately generous at $0.50 per stream; it is not a real-world financial model.']
];
function guideResults(query=''){const q=query.toLowerCase().trim();return guideTopics.filter(t=>t.join(' ').toLowerCase().includes(q)).map(([title,id,body])=>`<details class="card guide-topic"><summary>${title}</summary><p>${body}</p><button class="secondary" onclick="${id==='Home'||id==='Menu'?"go('"+id+"')":"openDestination('"+id+"')"}">Open relevant screen →</button></details>`).join('')||'<p>No matching topics. Try “save”, “song”, “agent” or “tax”.</p>'}
function guidePage(){return head('Your permanent player handbook','The ENCORE guide.')+`<section class="card guide-intro"><h2>Learn at your own pace.</h2><p>Search a topic, take the optional screen tour, or practice a release with temporary resources. The tour never spends your energy or money.</p><div class="controls"><button class="primary" onclick="openTour(0)">Start guided tour</button><button class="secondary" onclick="startPractice()">Practice a release</button></div></section><label class="menu-search">Search the handbook<input type="search" placeholder="Songs, taxes, labels, saves…" oninput="$('guide-results').innerHTML=guideResults(this.value)"></label><div id="guide-results">${guideResults()}</div>`}

function validatePresentationState(){if(s.onboarding&&(s.onboarding.version!==1||typeof s.onboarding.seen!=='boolean'))throw Error('Invalid onboarding');if(s.collection&&(!Array.isArray(s.collection.purchased)||s.collection.purchased.length>120||new Set(s.collection.purchased).size!==s.collection.purchased.length||s.collection.purchased.some(id=>typeof id!=='string'||!/^\d+-[0-5]$/.test(id))))throw Error('Invalid collection');for(const m of s.empire.merch)if(m.look!==undefined&&(!Number.isInteger(m.look)||m.look<0||m.look>2))throw Error('Invalid merchandise artwork');for(const a of s.empire.assets)if(a.editionId!==undefined&&(typeof a.editionId!=='string'||!/^\d+-[0-5]$/.test(a.editionId)||typeof a.edition!=='string'))throw Error('Invalid edition');}
