/* Portable saves, recovery and isolated practice. */
const BACKUP_KEY='encore-recovery-v1-'+(SANDBOX?'sandbox':'career')+'-'+(OFFLINE?'offline':'online');
let pendingImport=null,practice=null;
function saveBundle(){return {format:'encore-career',schemaVersion:1,exportedAt:new Date().toISOString(),mode:SANDBOX?'sandbox':'career',state:JSON.parse(JSON.stringify(s))}}
function downloadBundle(bundle,prefix='ENCORE-save'){const url=URL.createObjectURL(new Blob([JSON.stringify(bundle,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=prefix+'-'+bundle.mode+'-week-'+bundle.state.week+'.json';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function exportCareer(){if(saveReady){downloadBundle(saveBundle());noteBetaExport();toast('Save download prepared. Keep a copy in Files.')}}
function backupCareer(manual=false){if(!saveReady||saveConflict)return false;try{localStorage.setItem(BACKUP_KEY,JSON.stringify(saveBundle()));if(manual)toast('Recovery snapshot saved on this device.');return true}catch{if(manual)toast('Recovery storage unavailable. Export your career before replacing or resetting it.');return false}}
function readRecovery(){try{return JSON.parse(localStorage.getItem(BACKUP_KEY)||'null')}catch{return null}}
function savesPage(){const b=readRecovery();return head('Keep your story safe','Saves & recovery.')+`<section class="card"><h2>Portable career saves</h2><p>Download a JSON save and import it on another device or into the offline edition. Normal and sandbox files stay separate.</p><div class="save-actions"><button class="primary" onclick="exportCareer()">Export career</button><label class="secondary">Import save<input type="file" accept=".json,application/json" onchange="readImport(this.files[0]);this.value=''" style="display:block;max-width:100%;margin-top:8px"></label></div><p class="fine">Review the artist and week before replacing progress. Keep exports private: they contain your full career.</p></section><section class="card"><h2>Recovery snapshot</h2><p>A device-local snapshot is attempted before each week advance. This is one rotating backup. Export regularly in case browser storage is cleared.</p><p>${b?esc(b.state.name)+' · Week '+b.state.week+' · '+esc(b.exportedAt):'No snapshot yet.'}</p><div class="save-actions"><button class="secondary" onclick="backupCareer(true);render()">Back up now</button>${b?`<button class="secondary" onclick="previewImport(readRecovery())">Review restore</button><button class="secondary" onclick="downloadBundle(readRecovery(),'ENCORE-recovery')">Export recovery</button>`:''}</div></section><section class="card"><h2>Practice without consequences</h2><p>Write, record, mix and release a sample song using temporary resources.</p><button class="secondary" onclick="startPractice()">Practice a release</button></section>`}
function validateBundle(bundle){
 if(!bundle||bundle.format!=='encore-career'||bundle.schemaVersion!==1||!bundle.state)throw Error('Choose an ENCORE exported save.');
 if(bundle.mode!==(SANDBOX?'sandbox':'career')||!!bundle.state.sandbox!==SANDBOX)throw Error('Wrong game mode. Open '+(bundle.mode==='sandbox'?'sandbox':'normal career')+' to import this file.');
 const state=bundle.state;if(JSON.stringify(bundle).length>8000000)throw Error('Save exceeds the safe import limit.');let nodes=0;
 function walk(v,key='',depth=0){if(++nodes>600000||depth>18)throw Error('Save is too complex.');if(typeof v==='number'&&!Number.isFinite(v))throw Error('Invalid number.');if(typeof v==='string'){if(v.length>100000)throw Error('Text is too long.');if(['id','uid','key'].includes(key)&&!/^[-\w:.]+$/.test(v))throw Error('Invalid identifier.')}if(v&&typeof v==='object')for(const [k,x] of Object.entries(v)){if(['__proto__','prototype','constructor'].includes(k))throw Error('Unsafe save structure.');walk(x,k,depth+1)}}walk(state);
 const integer=(v,min,max)=>Number.isInteger(v)&&v>=min&&v<=max,numeric=(o,ks)=>ks.every(k=>Number.isFinite(o?.[k]));
 if(!integer(state.week,1,100000)||!integer(state.energy,0,200)||!numeric(state,['cash','fans','reputation','loyalty','streams','total','boost'])||state.fans<0||typeof state.name!=='string'||state.name.length>100||!genres.includes(state.genre))throw Error('Artist data is invalid.');
 for(const k of ['songs','albums','world','feed','history'])if(!Array.isArray(state[k]))throw Error('Missing '+k+'.');
 if(state.world.length<24||state.world.length>2524)throw Error('Incomplete industry roster.');
 if(!state.development||!Object.keys(developmentInfo).every(k=>numeric(state.development[k],['level','xp'])&&integer(state.development[k].level,0,100)&&state.development[k].xp>=0))throw Error('Invalid skill records.');
 if(!numeric(state.finance,['year','weeks','revenue','expenses','reserve','taxesPaid'])||!numeric(state.finance.week,['wages','live','expenses']))throw Error('Incomplete finances.');
 if(!state.careerRecords||!Array.isArray(state.careerRecords.tours)||!numeric(state.careerRecords,['openMics','royalties','liveGross','liveProfit']))throw Error('Incomplete career history.');
 if(!state.achievements||!state.achievements.unlocked||!Array.isArray(state.achievements.briefings)||!state.chartBook)throw Error('Incomplete milestones.');
 for(const kind of ['songs','albums']){const b=state.chartBook[kind];if(!b||!Array.isArray(b.current)||!b.records||typeof b.records!=='object')throw Error('Incomplete charts.');for(const r of Object.values(b.records))if(!Array.isArray(r.history))throw Error('Invalid chart history.');}
 const ids=new Set();for(const x of state.songs){if(!numeric(x,['id','quality','streams','total'])||typeof x.title!=='string'||typeof x.mood!=='string'||ids.has(x.id)||(x.released!==null&&!integer(x.released,1,state.week)))throw Error('Invalid song.');ids.add(x.id);if(x.feature&&!integer(x.feature.id,0,state.world.length-1))throw Error('Invalid feature.');}
 for(const a of state.albums)if(!numeric(a,['id','week'])||typeof a.title!=='string'||!Array.isArray(a.tracks)||a.tracks.some(id=>!ids.has(id)))throw Error('Incomplete album.');
 state.world.forEach((a,i)=>{if(a.id!==i||!Array.isArray(a.catalog)||!numeric(a,['fans','skill','reputation','relation','nextRelease'])||typeof a.name!=='string')throw Error('Invalid industry artist.');for(const t of a.catalog)if(typeof t.title!=='string'||!numeric(t,['week','streams','total']))throw Error('Invalid industry catalog.');});
 if(state.draft&&(!numeric(state.draft,['id','steps','quality'])||!state.draft.development||typeof state.draft.title!=='string'||typeof state.draft.mood!=='string'))throw Error('Invalid unfinished song.');
 if(state.projects!==undefined){if(!Array.isArray(state.projects)||state.projects.length>1000)throw Error('Invalid project library.');const projectIds=new Set(state.songs.map(x=>x.id));if(state.draft)projectIds.add(state.draft.id);for(const p of state.projects){if(!numeric(p,['id','steps','quality'])||!integer(p.steps,1,3)||typeof p.title!=='string'||typeof p.mood!=='string'||!p.development||projectIds.has(p.id))throw Error('Invalid parked project.');projectIds.add(p.id);}}
 if(state.studioIdea&&(typeof state.studioIdea.title!=='string'||typeof state.studioIdea.mood!=='string'||typeof state.studioIdea.package!=='string'))throw Error('Invalid studio idea.');
 for(const a of state.albums){if(a.price!==undefined&&!albumPrices.some(p=>p.value===a.price))throw Error('Invalid album price.');for(const k of ['sales','salesRevenue','weeklySales'])if(a[k]!==undefined&&(!Number.isFinite(a[k])||a[k]<0))throw Error('Invalid album sales.');}
 if(state.expansion?.marketingActions!==undefined){if(!Array.isArray(state.expansion.marketingActions))throw Error('Invalid campaigns.');for(const a of state.expansion.marketingActions)if(!marketingChannels.some(c=>c.id===a.channel)||!integer(a.week,1,state.week)||!Number.isFinite(a.estimate)||a.estimate<0||a.estimate>2||(a.boost!==null&&(!Number.isFinite(a.boost)||a.boost<0||a.boost>3))||(a.target!=='all'&&!state.songs.some(x=>x.id===a.target)))throw Error('Invalid campaign record.');}
 if(state.walletCents!==undefined&&(!/^-?\d{1,310}$/.test(state.walletCents)||!Number.isFinite(Number(BigInt(state.walletCents))/100)))throw Error('Invalid cash ledger.');
 const e=state.expansion;if(e){for(const k of ['timeline','opportunities','awards','contractHistory'])if(!Array.isArray(e[k]))throw Error('Incomplete expansion records.');if(e.contract&&(!numeric(e.contract,['ends','share','lift','started'])||e.contract.share<0||e.contract.share>1))throw Error('Invalid contract.');for(const o of e.opportunities)if(!integer(o.artist,0,state.world.length-1)||!numeric(o,['fee','expires'])||o.fee<0)throw Error('Invalid opportunity.');}
 for(const b of state.achievements.briefings)if(!b||typeof b.id!=='string'||typeof b.body!=='string'||typeof b.title!=='string')throw Error('Invalid briefing.');
 for(const t of state.careerRecords.tours)if(!t||!numeric(t,['week','gross','profit','fans','review'])||typeof t.title!=='string')throw Error('Invalid tour record.');
 if(e){for(const a of e.awards)if(!a||!numeric(a,['year','score'])||typeof a.nominated!=='boolean'||typeof a.won!=='boolean')throw Error('Invalid award.');for(const m of e.timeline)if(!m||typeof m.id!=='string'||typeof m.title!=='string'||typeof m.detail!=='string'||!Number.isFinite(m.week))throw Error('Invalid milestone.');}
 const candidate=JSON.parse(JSON.stringify(state)),active=s;
 try{s=candidate;migrateCharts();migratePacing();migrateDevelopment();migrateCareerRecords();migrateFinance();migrateChartBook();migrateAchievements();migrateExpansion();migrateLabelBusiness();migrateEmpire();validateLabelBusiness();validateEmpire();validateLiving();validatePresentationState();validateWorldTour();migrateMarket();migrateConversations();migrateIndustryLife();validateLiving();for(const view of [home,studio,careerProfile,catalog,training,financeScreen,achievementsPage,certificationsPage,tourPage,marketingPage,opportunitiesPage,labelPage,legacyPage])view();}
 catch{throw Error('This save has incomplete gameplay data. Your active career was not changed.');}finally{s=active;if(s.market)syncMarketHoldings()}
 return candidate;
}
async function readImport(file){if(!file)return;try{if(file.size>8000000)throw Error('Choose a save smaller than 8 MB.');previewImport(JSON.parse(await file.text()))}catch(e){toast('Import stopped: '+e.message)}}
function previewImport(bundle){try{pendingImport=validateBundle(bundle);modal(`<h2>Import this career?</h2>${profileRows([['Artist',pendingImport.name],['Week',pendingImport.week],['Mode',SANDBOX?'Sandbox':'Normal career'],['Cash',money(pendingImport.cash)],['Songs',pendingImport.songs.length]])}<p>This replaces the active career in this mode. We first save a recovery snapshot of your current career on this device.</p><button class="secondary" onclick="pendingImport=null;$('modal').close()">Cancel</button><button class="primary" onclick="confirmImport()">Back up and import</button>`)}catch(e){pendingImport=null;toast('Import stopped: '+e.message)}}
async function confirmImport(){if(!pendingImport||!saveReady||saveConflict||saveBusy){toast('Wait for saving to finish, or reload if another tab changed this career.');return}if(!backupCareer(true))return;clearTimeout(saveTimer);s=pendingImport;pendingImport=null;migrateCharts();migratePacing();migrateDevelopment();migrateCareerRecords();migrateFinance();migrateChartBook();migrateAchievements();migrateExpansion();$('modal').close();tab='Career';careerTab='Saves';render();await saveNow();toast(lastSaved===JSON.stringify(s)?'Career imported and saved.':'Imported in this tab. Save is pending—keep this tab open and use Retry save.')}
function playTour(){careerTab='Touring';go('Career')}
function startPractice(){practice={step:0,cash:650,energy:200};practiceScreen()}
function practiceScreen(){const steps=[['Write a song','Choose a title and direction. Writing uses 10 energy.','Write · 10 energy'],['Record vocals','Recording uses your Recording skill. Pay $40, 15 energy.','Record · $40'],['Mix the record','Producing helps shape quality. Pay $30, 15 energy.','Mix · $30'],['Release the single','Publish for $20, 5 energy. The real game asks you to confirm.','Release · $20'],['Advance the week','Streams arrive at week close. Quality, promotion, and listener response all matter.','See sample results'],['Weekly report','Example: 300 streams earn $150 gross at $0.50 each. This is below the global chart floor. The real report also shows label shares, expenses, overhead and tax reserves.','Finish practice']];const t=steps[practice.step];modal(`<span class="eyebrow">ISOLATED PRACTICE · ${practice.step+1}/6</span><h2>${t[0]}</h2><p>${t[1]}</p><div class="practice-meter">${money(practice.cash)} · ${practice.energy}/200 energy</div><p class="fine">Your saved career is unchanged.</p><button class="primary" onclick="practiceNext()">${t[2]}</button><button class="secondary" onclick="practice=null;$('modal').close()">Leave practice</button>`)}
function practiceNext(){if(!practice)return;const costs=[[0,10],[40,15],[30,15],[20,5]];if(practice.step<4){practice.cash-=costs[practice.step][0];practice.energy-=costs[practice.step][1]}else if(practice.step===4){practice.cash+=150;practice.energy=200}else{practice=null;$('modal').close();return}practice.step++;practiceScreen()}
window.addEventListener('pageshow',e=>{if(e.persisted&&saveReady){endTour();$('modal').close();showTitle()}});

