/* ENCORE 0.8 implementation layer.
   Loaded after the recovered 0.7.1 modules so it can migrate old careers and
   override selected UI/economy behavior without resetting existing saves. */

const V080_SCHEMA=1;
let V080_inboxFilter='Unread',V080_offerFilter='All',V080_catalogFilter='Marketplace';

function migrateV080(){
  if(!s.v080)s.v080={version:V080_SCHEMA,inbox:{pinned:[]},commercial:{offers:[],contracts:[],nextId:1,lastGeneratedMonth:-1},catalog:{holdings:[],payouts:[],history:[],nextId:1},awards:{ceremonies:[]},offerMigrationDone:false};
  const v=s.v080;
  v.version=V080_SCHEMA;
  v.inbox??={pinned:[]};v.inbox.pinned??=[];
  v.commercial??={offers:[],contracts:[],nextId:1,lastGeneratedMonth:-1};v.commercial.offers??=[];v.commercial.contracts??=[];v.commercial.nextId??=1;v.commercial.lastGeneratedMonth??=-1;
  v.catalog??={holdings:[],payouts:[],history:[],nextId:1};v.catalog.holdings??=[];v.catalog.payouts??=[];v.catalog.history??=[];v.catalog.nextId??=1;
  v.awards??={ceremonies:[]};v.awards.ceremonies??=[];
  if(!v.offerMigrationDone){
    const protect=o=>{if(!o||o.used||o.done||o.expires<s.week)return;if(o.reviewedMonth===undefined){o.originalExpiry=o.expires;o.reviewedMonth=null;o.expires=Number.MAX_SAFE_INTEGER}};
    for(const o of s.labelBusiness?.offers||[])protect(o);
    for(const o of s.empire?.media||[])protect(o);
    for(const o of s.expansion?.opportunities||[])protect(o);
    v.offerMigrationDone=true;
  }
}
function V080_reviewDeadline(){return s.week+Math.max(5,monthLength()+1)}
function V080_markReviewed(o){migrateV080();if(!o)return;if(o.reviewedMonth===null||o.reviewedMonth===undefined){o.reviewedMonth=s.empire.month;o.reviewedWeek=s.week;o.expires=V080_reviewDeadline();queueSave()}else if(o.expires===Number.MAX_SAFE_INTEGER)o.expires=V080_reviewDeadline()}
function V080_extendOffer(o){if(o)o.expires=Math.max(Number.isFinite(o.expires)?o.expires:0,V080_reviewDeadline())}
function V080_offerDeadlineText(o){return o.reviewedMonth===null||o.reviewedMonth===undefined?'No deadline until reviewed':`Decision due after Week ${o.expires}`}

function V080_unreadCount(){migrateV080();let n=(s.achievements?.briefings||[]).filter(b=>!b.read).length;n+=(s.labelBusiness?.offers||[]).filter(o=>!o.used&&o.expires>=s.week&&(o.reviewedMonth===null||o.reviewedMonth===undefined)).length;n+=(s.empire?.media||[]).filter(o=>!o.used&&o.expires>=s.week&&(o.reviewedMonth===null||o.reviewedMonth===undefined)).length;n+=(s.expansion?.opportunities||[]).filter(o=>!o.done&&o.expires>=s.week&&(o.reviewedMonth===null||o.reviewedMonth===undefined)).length;n+=(s.v080.commercial.offers||[]).filter(o=>o.status==='open'&&(o.reviewedMonth===null||o.reviewedMonth===undefined)).length;return n}
function V080_offerRiskCount(weeks=monthLength()){migrateV080();const edge=s.week+weeks;let n=0;for(const o of [...(s.labelBusiness?.offers||[]),...(s.empire?.media||[]),...(s.expansion?.opportunities||[]),...(s.v080.commercial.offers||[])]){const active=!(o.used||o.done||['accepted','declined'].includes(o.status));if(active&&o.reviewedMonth!==null&&o.reviewedMonth!==undefined&&Number.isFinite(o.expires)&&o.expires<Number.MAX_SAFE_INTEGER&&o.expires<=edge)n++}return n}

function V080_navigationTools(){migrateV080();const unread=V080_unreadCount();return `<div class="navigation-tools"><button class="secondary" onclick="goBack()" aria-label="Back to previous screen">← Back</button><span class="section-identity">${screenFamily().toUpperCase()}</span><button class="secondary inbox-nav" onclick="openDestination('Inbox')">Inbox${unread?` <b>${unread}</b>`:''}</button><button class="secondary" onclick="go('Guide')">Guide ?</button><button class="text-button" onclick="openSettings()" aria-label="Open settings">Settings</button></div>`}
navigationTools=V080_navigationTools;

function V080_screenFamily(){if(tab==='Home')return 'backstage';if(tab==='Create'||tab==='Stats')return 'studio';if(tab==='Guide'||tab==='Menu'||tab==='Artist')return 'library';if(tab==='Industry')return industryTab==='Charts'?'charts':'social';if(tab==='ArtistFile')return 'wealth';if(tab==='Career'){if(['Social','Location'].includes(careerTab))return 'social';if(['Wealth','Properties','Finances','Profile'].includes(careerTab))return 'wealth';if(careerTab==='Market'||careerTab==='CatalogMarket')return 'exchange';if(['Deals','Labels','League','Agency','Team','Commerce','Opportunities','Offers'].includes(careerTab))return 'business';if(['Releases','Campaigns','Touring'].includes(careerTab))return 'studio';if(['Awards','Milestones','Celebrations','Legacy'].includes(careerTab))return 'awards';if(careerTab==='Inbox')return 'inbox';return 'library'}return 'library'}
screenFamily=V080_screenFamily;

const V080_destinations=[['Career Inbox','Career','Inbox','Unread briefings, offers and celebrations',4],['Player guide','Career','Guide','Search help or replay the tour',4],['Studio','Music','Create','Write, record and release',1],['Releases','Music','Releases','Singles, albums and catalog',1],['Stats','Music','Stats','Develop your craft',2],['Charts','Music','Industry','Rankings and movement',3],['Marketing','Music','Campaigns','Promote your music',3],['Touring','Music','Touring','Book your next stage',3],['PULSE','Social','Social','Posts, replies and connections',3],['Artists','Social','Artists','Discover collaborators',3],['Location','Social','Location','Your city and local scene',3],['Offers Center','Business','Offers','Label, media, endorsement and brand offers',4],['Deals & rights','Business','Deals','Contracts, ownership and buyouts',4],['Labels','Business','Labels','Demos and your own label',4],['Label league','Business','League','Competition across the industry',4],['Agent','Business','Agency','Representation and negotiation',4],['Team','Business','Team','Managers and specialists',4],['Merchandise','Business','Commerce','Merchandise and product inventory',4],['Exchange','Wealth','Market','Live simulated prices and trades',2],['Catalog Market','Wealth','CatalogMarket','Buy, hold and sell artist catalogs',2],['Collection','Wealth','Wealth','Cars, jewelry, art and property',4],['Properties','Wealth','Properties','Rentals, tenants and renovation',0],['Finances','Wealth','Finances','Income, expenses and taxes',2],['Artist File','Career','ArtistFile','Your evolving career profile',4],['Awards','Legacy','Awards','ENCORE Honors, nominations and wins',2],['Milestones','Legacy','Milestones','Career firsts and landmark moments',2],['Celebrations','Legacy','Celebrations','Big moments worth revisiting',2],['Achievements','Legacy','Achievements','Unlockable game challenges only',2],['Certifications','Legacy','Certifications','Gold, platinum and beyond',2],['Activity','Career','Activity','Your career history',4],['Saves','Career','Saves','Backups and exports',4],['Settings','Career','Settings','Appearance and preferences',4]];
function V080_openDestination(id){if(id==='Guide'){go('Guide');return}if(id==='Settings'){openSettings();return}if(id==='ArtistFile'){openArtistFile();return}if(id==='Industry')industryTab='Charts';if(['Create','Stats','Industry'].includes(id)){go(id);return}if(id==='Artists'){industryTab='Artists';go('Industry');return}careerTab=id;go('Career')}
openDestination=V080_openDestination;
function V080_menuResults(query=''){const q=query.trim().toLowerCase(),matches=V080_destinations.filter(d=>d.join(' ').toLowerCase().includes(q));return [...new Set(matches.map(d=>d[1]))].map(group=>`<section class="destination-group"><h2>${group}</h2><div class="destination-grid">${matches.filter(d=>d[1]===group).map(([name,g,id,description,i])=>`<button class="destination" onclick="openDestination('${id}')"><svg viewBox="0 0 24 24" aria-hidden="true">${icons[i]}</svg><span><strong>${name}</strong><small>${description}</small></span><span aria-hidden="true">↗</span></button>`).join('')}</div></section>`).join('')||'<p>No matching screens.</p>'}
menuResults=V080_menuResults;

function V080_inboxItems(){migrateV080();const items=[];for(const b of s.achievements?.briefings||[])items.push({key:'brief:'+b.id,kind:'brief',category:b.type||'Briefing',title:b.title,detail:b.body,week:b.week,unread:!b.read,obj:b});for(const o of s.labelBusiness?.offers||[])if(!o.used&&o.expires>=s.week)items.push({key:'label:'+o.id,kind:'label',category:'Label offer',title:labelDeals[o.label]?.name||'Label offer',detail:o.source||'A label wants to talk.',week:o.reviewedWeek??s.week,unread:o.reviewedMonth===null||o.reviewedMonth===undefined,obj:o});for(const o of s.expansion?.opportunities||[])if(!o.done&&o.expires>=s.week)items.push({key:'op:'+o.id,kind:'opportunity',category:'Opportunity',title:o.type,detail:o.name?`With ${o.name}`:'Career opportunity',week:o.week??s.week,unread:o.reviewedMonth===null||o.reviewedMonth===undefined,obj:o});for(const o of s.v080.commercial.offers||[])if(o.status==='open'&&o.expires>=s.week)items.push({key:'commercial:'+o.id,kind:'commercial',category:V080_offerCategoryName(o.category),title:o.name,detail:`${money(o.totalValue)} headline value`,week:o.createdWeek,unread:o.reviewedMonth===null||o.reviewedMonth===undefined,obj:o});for(const o of s.empire?.media||[])if(!o.used&&o.expires>=s.week)items.push({key:'legacy-media:'+o.id,kind:'legacy-media',category:'Media offer',title:o.name,detail:`${money(o.fee)} fee`,week:o.week??s.week,unread:o.reviewedMonth===null||o.reviewedMonth===undefined,obj:o});return items.sort((a,b)=>(b.unread-a.unread)||(b.week-a.week))}
function V080_openInboxItem(key){const item=V080_inboxItems().find(x=>x.key===key);if(!item)return;if(item.kind==='brief'){item.obj.read=true;queueSave();showBriefing(item.obj.id);return}if(item.kind==='label'){reviewArtistOffer(item.obj.id);return}if(item.kind==='opportunity'){V080_markReviewed(item.obj);modal(`<span class="eyebrow">${esc(item.obj.type)}</span><h2>${esc(item.obj.name||'Career opportunity')}</h2><p>Fee ${money(item.obj.fee||0)} · 15 energy.</p><p>${V080_offerDeadlineText(item.obj)}. Reviewing never accepts the offer.</p><button class="primary" onclick="acceptOpportunity('${item.obj.id}')">Review acceptance</button><button class="secondary" onclick="declineOpportunity('${item.obj.id}')">Decline</button>`);render();return}if(item.kind==='commercial'){reviewCommercialOffer080(item.obj.id);return}if(item.kind==='legacy-media'){reviewMedia(item.obj.id);return}}
function V080_togglePin(key){migrateV080();const p=s.v080.inbox.pinned,i=p.indexOf(key);if(i>=0)p.splice(i,1);else p.push(key);queueSave();render()}
function V080_inboxPage(){migrateV080();const all=V080_inboxItems(),filters=['Unread','All','Offers','Celebrations','Briefings'],filtered=all.filter(x=>V080_inboxFilter==='All'||V080_inboxFilter==='Unread'&&x.unread||V080_inboxFilter==='Offers'&&['label','opportunity','commercial','legacy-media'].includes(x.kind)||V080_inboxFilter==='Celebrations'&&x.category==='Celebration'||V080_inboxFilter==='Briefings'&&!['label','opportunity','commercial','legacy-media'].includes(x.kind));return head('Nothing important gets lost','Career Inbox.',`<span class="pill">${V080_unreadCount()} unread</span>`)+`<div class="chips">${filters.map(f=>`<button class="${V080_inboxFilter===f?'selected':''}" onclick="V080_inboxFilter='${f}';render()">${f}</button>`).join('')}</div><section class="card inbox-summary"><p>Offers remain available until you review them. Once reviewed, you always receive at least a full decision window. Pin anything you want to revisit.</p></section><div class="inbox-stack">${filtered.map(x=>{const pinned=s.v080.inbox.pinned.includes(x.key);return `<section class="card inbox-item ${x.unread?'unread':''}"><div><span class="eyebrow">${esc(x.category)} · Week ${x.week}${x.unread?' · NEW':''}</span><h2>${esc(x.title)}</h2><p>${esc(x.detail||'')}</p>${['label','opportunity','commercial','legacy-media'].includes(x.kind)?`<small>${esc(V080_offerDeadlineText(x.obj))}</small>`:''}</div><div class="inbox-actions"><button class="primary" onclick="V080_openInboxItem('${x.key}')">Open</button><button class="secondary" onclick="V080_togglePin('${x.key}')">${pinned?'Unpin':'Pin'}</button></div></section>`}).join('')||'<section class="card empty"><h2>You’re caught up.</h2><p>New offers, milestones, celebrations and career reports will remain available here.</p></section>'}</div>`}

function V080_offerCategoryName(category){return ({label:'Label offer',media:'Media',endorsement:'Endorsement',brand:'Brand deal',partnership:'Partnership',lifetime:'Lifetime partnership',live:'Live opportunity'})[category]||'Offer'}
function V080_commercialLeverage(){const followers=s.social?.followers||0,awardWins=s.expansion?.awardWins||0,base=Math.log10(1+Math.max(0,s.fans))*11+Math.log10(1+followers)*5+s.reputation*.18+level('marketability')*.22+level('charisma')*.08+s.loyalty*.08+Math.min(15,awardWins*2.5);return clamp(base,0,100)}
const V080_brandPools={media:['Northline Studios','Framehouse Media','Signal Network','Brightline Pictures'],endorsement:['Apex Audio','Drift Athletics','Orbit Mobile','Vale Timepieces'],brand:['Crown Street','Monarch Goods','Vesper Motors','Studio North'],partnership:['Atlas Collective','Evergreen Group','Halcyon Global','Summit House'],lifetime:['Apex Legacy','Monarch Forever','Jordanesque House','Crown Heritage']};
function V080_makeCommercialOffer(category,slot){migrateV080();const leverage=V080_commercialLeverage(),audience=Math.max(100,s.fans+(s.social?.followers||0)*.22),tierMult=.45+tier(s.fans)*.82,impact=1+s.reputation/180+level('marketability')/180+Math.min(.35,(s.expansion?.awardWins||0)*.04),scale={media:.22,endorsement:.75,brand:1.15,partnership:1.75,lifetime:3.7}[category]||.5;let value=Math.max(500,Math.round(audience*tierMult*impact*scale));if(category==='media')value=Math.min(value,25000000);if(category==='endorsement')value=Math.min(value,350000000);if(category==='brand')value=Math.min(value,800000000);if(category==='partnership')value=Math.min(value,1500000000);if(category==='lifetime')value=Math.min(Math.max(value,250000000),3000000000);const pool=V080_brandPools[category],brand=pool[(s.empire.month+slot*2)%pool.length],duration=category==='media'?1:category==='endorsement'?12:category==='brand'?24:category==='partnership'?60:120,guarantee=Math.round(value*(category==='lifetime'?.62:.72)),bonus=value-guarantee;return {id:s.v080.commercial.nextId++,category,name:`${brand} · ${category==='media'?'feature opportunity':category==='endorsement'?'endorsement':category==='brand'?'signature campaign':category==='partnership'?'global partnership':'lifetime partnership'}`,brand,totalValue:value,guarantee,bonus,durationMonths:duration,lifetime:category==='lifetime',exclusive:['brand','partnership','lifetime'].includes(category),createdMonth:s.empire.month,createdWeek:s.week,reviewedMonth:null,expires:Number.MAX_SAFE_INTEGER,status:'open',rounds:0,maxValue:Math.round(value*(1.12+leverage/500))}}
function generateCommercialOffers080(){migrateV080();const c=s.v080.commercial;if(c.lastGeneratedMonth===s.empire.month)return;c.lastGeneratedMonth=s.empire.month;const l=V080_commercialLeverage();if(s.fans<750)return;let count=1+(s.fans>=100000?1:0)+(s.fans>=2000000?1:0);const categories=['media',l>=35?'endorsement':'media',l>=55?'brand':'endorsement'];if(l>=70)categories[2]='partnership';if(l>=90&&s.fans>=50000000&&(s.expansion?.awardWins||0)>=1)categories[2]='lifetime';for(let i=0;i<count;i++){const o=V080_makeCommercialOffer(categories[i],i);c.offers.push(o);addBriefing('commercial:'+o.id,'Opportunity',V080_offerCategoryName(o.category)+' arrived',o.name+' is offering a headline package worth '+money(o.totalValue)+'. It will not expire until you review it.','Open Career → Offers Center to review, counter or decline.')}c.offers=c.offers.filter(o=>o.status==='open'||s.empire.month-(o.createdMonth||0)<24).slice(-60)}
function reviewCommercialOffer080(id){migrateV080();const o=s.v080.commercial.offers.find(x=>x.id===id&&x.status==='open'&&x.expires>=s.week);if(!o)return;V080_markReviewed(o);modal(`<span class="eyebrow">${esc(V080_offerCategoryName(o.category))}</span><h2>${esc(o.name)}</h2>${profileRows([['Headline value',money(o.totalValue)],['Guaranteed compensation',money(o.guarantee)],['Performance / milestone upside',money(o.bonus)],['Term',o.lifetime?'Lifetime relationship · guaranteed payments over 120 months':o.durationMonths+' months'],['Exclusivity',o.exclusive?'Category exclusivity':'Non-exclusive'],['Decision window',V080_offerDeadlineText(o)]])}<p>Value reflects audience scale, engagement, reputation, performance, awards and marketability. Headline value is not paid all at once: long deals use a signing payment plus monthly guaranteed installments and potential bonuses.</p><form class="form" onsubmit="counterCommercialOffer080(event,${id})"><label>Counter headline value ($)<input name="value" type="number" min="1" max="9007199254740991" step="1" value="${o.totalValue}" required></label><button class="secondary">Send counter · 5 energy</button></form><div class="controls"><button class="primary" onclick="acceptCommercialOffer080(${id})">Accept offer</button><button class="secondary" onclick="declineCommercialOffer080(${id})">Decline</button></div>`);render()}
function counterCommercialOffer080(e,id){e.preventDefault();const o=s.v080?.commercial?.offers.find(x=>x.id===id&&x.status==='open'&&x.expires>=s.week),ask=Number(new FormData(e.target).get('value'));if(!o||!Number.isSafeInteger(ask)||ask<1||!spend(5))return;o.rounds++;if(ask<=o.maxValue){o.totalValue=ask;o.guarantee=Math.round(ask*(o.lifetime?.62:.72));o.bonus=ask-o.guarantee;o.response='They accepted your counter.'}else{o.totalValue=o.maxValue;o.guarantee=Math.round(o.totalValue*(o.lifetime?.62:.72));o.bonus=o.totalValue-o.guarantee;o.response='They countered at '+money(o.totalValue)+'.'}V080_extendOffer(o);render();reviewCommercialOffer080(id);toast(o.response)}
function acceptCommercialOffer080(id){migrateV080();const o=s.v080.commercial.offers.find(x=>x.id===id&&x.status==='open'&&x.expires>=s.week);if(!o||!spend(10))return;const upfront=cents(o.guarantee*(o.lifetime?.25:.35)),remaining=cents(o.guarantee-upfront);o.status='accepted';o.acceptedMonth=s.empire.month;o.paid=upfront;changeCash(upfront);recordIncome('media',upfront);s.v080.commercial.contracts.push({id:o.id,name:o.name,brand:o.brand,category:o.category,lifetime:o.lifetime,totalValue:o.totalValue,guarantee:o.guarantee,bonus:o.bonus,durationMonths:o.durationMonths,monthsPaid:0,remaining,active:true,startedMonth:s.empire.month});moneyEvent(o.name+' signing payment',upfront);milestone('commercial-'+o.id,'Signed '+V080_offerCategoryName(o.category),money(o.totalValue)+' headline value');$('modal').close();render();toast('Deal signed · '+money(upfront)+' paid now')}
function declineCommercialOffer080(id){const o=s.v080?.commercial?.offers.find(x=>x.id===id&&x.status==='open');if(!o)return;o.status='declined';o.declinedMonth=s.empire.month;$('modal').close();render()}
function settleCommercialContracts080(){migrateV080();for(const c of s.v080.commercial.contracts.filter(x=>x.active)){const months=Math.max(1,c.durationMonths||120),installment=c.monthsPaid>=months?0:cents(c.remaining/Math.max(1,months-c.monthsPaid));if(installment>0){c.monthsPaid++;c.remaining=cents(Math.max(0,c.remaining-installment));c.paid=cents((c.paid||0)+installment);changeCash(installment);recordIncome('media',installment);moneyEvent(c.name+' guaranteed installment',installment)}if(c.monthsPaid>=months&&c.remaining<=0){if(!c.lifetime)c.active=false;else c.guaranteeComplete=true}}}
function V080_offersPage(){migrateV080();const tabs=['All','Labels','Media','Endorsements','Brand deals','Partnerships','Lifetime'],items=[];for(const o of s.labelBusiness.offers||[])if(!o.used&&o.expires>=s.week)items.push({kind:'label',category:'Labels',name:labelDeals[o.label].name,value:o.proposal?.advance||labelDeals[o.label].advance,detail:o.source,obj:o});for(const o of s.v080.commercial.offers||[])if(o.status==='open'&&o.expires>=s.week)items.push({kind:'commercial',category:o.category==='media'?'Media':o.category==='endorsement'?'Endorsements':o.category==='brand'?'Brand deals':o.category==='partnership'?'Partnerships':'Lifetime',name:o.name,value:o.totalValue,detail:o.exclusive?'Exclusive':'Non-exclusive',obj:o});for(const o of s.empire.media||[])if(!o.used&&o.expires>=s.week)items.push({kind:'legacy-media',category:'Media',name:o.name,value:o.fee,detail:'Existing media opportunity',obj:o});const visible=items.filter(x=>V080_offerFilter==='All'||x.category===V080_offerFilter);return head('Every opportunity in one place','Offers Center.',`<span class="pill">${items.length} open</span>`)+`<p>Label negotiations stay separate from endorsements, media and brand partnerships. Unreviewed offers do not expire.</p><div class="chips">${tabs.map(t=>`<button class="${V080_offerFilter===t?'selected':''}" onclick="V080_offerFilter='${t}';render()">${t}</button>`).join('')}</div><div class="offer-grid">${visible.map(x=>`<section class="card offer-card"><span class="eyebrow">${esc(x.category)}</span><h2>${esc(x.name)}</h2><strong class="offer-value">${money(x.value)}</strong><p>${esc(x.detail||'')}</p><small>${esc(V080_offerDeadlineText(x.obj))}</small><button class="primary" onclick="${x.kind==='label'?`reviewArtistOffer('${x.obj.id}')`:x.kind==='legacy-media'?`reviewMedia(${x.obj.id})`:`reviewCommercialOffer080(${x.obj.id})`}">Review / negotiate</button></section>`).join('')||'<section class="card empty"><h2>No offers in this category.</h2><p>Keep building fans, engagement, performance, awards and cultural impact.</p></section>'}</div><section class="card"><h2>Active commercial relationships</h2>${s.v080.commercial.contracts.map(c=>`<div class="row"><span>${esc(c.name)}</span><strong>${money(c.paid||0)} paid · ${c.active?'Active':'Completed'}</strong></div>`).join('')||'<p>No signed commercial partnerships yet.</p>'}</section>`}

function V080_catalogStats(a){const weekly=(a.catalog||[]).reduce((n,x)=>n+(x.streams||0),0),lifetime=(a.catalog||[]).reduce((n,x)=>n+(x.total||0),0)+(a.archivedStreams||0),annual=weekly*.5*52*.15,multiple=1.6+a.skill/55+tier(a.fans)*.22,trend=1+s.empire.month*.0025,cycle=1+Math.sin((s.empire.month+1)*(a.id+3)*1.317)*.09+Math.cos((s.empire.month+2)*(a.id+5)*.719)*.035,value=Math.max(1000,cents(annual*multiple*trend*cycle));return {weekly,lifetime,annual,multiple,cycle,value}}
function V080_catalogUniverse(){migrateV080();const start=(s.empire.month*5)%s.world.length;return Array.from({length:Math.min(12,s.world.length)},(_,i)=>s.world[(start+i*2)%s.world.length]).filter((a,i,arr)=>arr.findIndex(x=>x.id===a.id)===i)}
function V080_ownedShare(artist){return s.v080.catalog.holdings.filter(h=>h.artist===artist).reduce((n,h)=>n+h.share,0)}
function V080_catalogBuyForm(id){migrateV080();const a=s.world[id];if(!a)return;const st=V080_catalogStats(a),owned=V080_ownedShare(id),options=[.1,.25,.5,1].filter(p=>p<=1-owned+.000001);modal(`${personPhoto('catalog-'+a.id,a.name,true)}<span class="eyebrow">CATALOG MARKET</span><h2>${esc(a.name)}</h2>${profileRows([['Estimated full catalog value',money(st.value)],['Current weekly streams',compact(st.weekly)],['Your current economic interest',Math.round(owned*100)+'%'],['Market movement',((st.cycle-1)*100).toFixed(1)+'% vs baseline']])}<p>Catalog prices can rise or fall. Holdings pay simulated monthly royalty distributions while you own them. Long-term value tends to benefit from durable streams, career growth and legacy, but losses remain possible.</p>${options.length?`<div class="catalog-share-grid">${options.map(p=>`<button class="secondary" onclick="V080_reviewCatalogPurchase(${id},${p})">Buy ${Math.round(p*100)}% · ${money(st.value*p*1.03)}</button>`).join('')}</div>`:'<p>You already own 100% of the available economic interest.</p>'}`)}
function V080_reviewCatalogPurchase(id,share){const a=s.world[id],st=a&&V080_catalogStats(a),owned=V080_ownedShare(id);if(!a||![.1,.25,.5,1].includes(share)||owned+share>1.000001)return;const price=cents(st.value*share*1.03);modal(`<h2>Buy ${Math.round(share*100)}% of ${esc(a.name)}’s catalog?</h2>${profileRows([['Purchase price',money(price)],['Full catalog valuation',money(st.value)],['Economic interest after purchase',Math.round((owned+share)*100)+'%'],['Monthly payouts','Variable · based on current catalog performance']])}<p>5 energy. This is a capital purchase, not an immediate deductible expense. Value and payouts can decrease. You can sell later at the then-current market price less a transaction spread.</p><button class="primary" onclick="V080_confirmCatalogPurchase(${id},${share})">Confirm purchase</button>`)}
function V080_confirmCatalogPurchase(id,share){migrateV080();const a=s.world[id],st=a&&V080_catalogStats(a),owned=V080_ownedShare(id);if(!a||owned+share>1.000001)return;const price=cents(st.value*share*1.03);if(s.cash<price){toast('Not enough cash for this catalog position.');return}if(!spend(5))return;changeCash(-price);const h={id:s.v080.catalog.nextId++,artist:id,name:a.name,share,basis:price,boughtMonth:s.empire.month,payouts:0,lastValue:cents(st.value*share),history:[{month:s.empire.month,value:cents(st.value*share)}]};s.v080.catalog.holdings.push(h);moneyEvent('Catalog purchase · '+a.name,-price);milestone('catalog-buy-'+h.id,'Bought into '+a.name+' catalog',Math.round(share*100)+'% economic interest');$('modal').close();render()}
function settleCatalogHoldings080(){migrateV080();let total=0;for(const h of s.v080.catalog.holdings){const a=s.world[h.artist];if(!a)continue;const st=V080_catalogStats(a),payout=cents(st.weekly*.5*monthLength()*.15*h.share),value=cents(st.value*h.share);h.payouts=cents((h.payouts||0)+payout);h.lastValue=value;h.history=(h.history||[]);h.history.push({month:s.empire.month,value});h.history=h.history.slice(-36);if(payout>0){changeCash(payout);recordIncome('investment',payout);total+=payout;s.v080.catalog.payouts.unshift({month:s.empire.month,artist:h.artist,name:h.name,holding:h.id,amount:payout})}}if(total>0)moneyEvent('Catalog distributions',total);s.v080.catalog.payouts=s.v080.catalog.payouts.slice(0,120);return total}
function V080_sellCatalog(id,confirmed=false){migrateV080();const h=s.v080.catalog.holdings.find(x=>x.id===id);if(!h)return;const a=s.world[h.artist],st=a&&V080_catalogStats(a),proceeds=cents(st.value*h.share*.97),gain=cents(proceeds-h.basis);if(!confirmed){modal(`<h2>Sell your ${Math.round(h.share*100)}% interest in ${esc(h.name)}?</h2>${profileRows([['Current position value',money(st.value*h.share)],['Estimated sale proceeds',money(proceeds)],['Original basis',money(h.basis)],['Realized gain / loss',(gain>=0?'+':'')+money(gain)],['Distributions received',money(h.payouts||0)]])}<p>5 energy. Sale value uses the current market estimate and a 3% transaction spread. Positive realized gains enter game taxes.</p><button class="primary" onclick="V080_sellCatalog(${id},true)">Confirm sale</button>`);return}if(!spend(5))return;changeCash(proceeds);if(gain>0)recordIncome('investment',gain);moneyEvent('Catalog sale · '+h.name,proceeds);s.v080.catalog.holdings=s.v080.catalog.holdings.filter(x=>x.id!==id);$('modal').close();render()}
function V080_catalogMarketPage(){migrateV080();const tabs=['Marketplace','My holdings','Payout history'],universe=V080_catalogUniverse();return head('Own a piece of music history','Catalog Market.',`<span class="pill">${s.v080.catalog.holdings.length} holdings</span>`)+`<p>Buy economic interests in other artists’ catalogs, collect distributions while holding, and sell later. Prices can fall even though durable catalogs tend to gain value over long careers.</p><div class="chips">${tabs.map(t=>`<button class="${V080_catalogFilter===t?'selected':''}" onclick="V080_catalogFilter='${t}';render()">${t}</button>`).join('')}</div>${V080_catalogFilter==='Marketplace'?`<div class="catalog-market-grid">${universe.map(a=>{const st=V080_catalogStats(a),owned=V080_ownedShare(a.id);return `<button class="card catalog-listing" onclick="V080_catalogBuyForm(${a.id})">${personPhoto('catalog-'+a.id,a.name)}<span class="eyebrow">${esc(a.genre)} · ${tierNames[tier(a.fans)]}</span><h2>${esc(a.name)}</h2><strong>${money(st.value)}</strong><p>${compact(st.weekly)} current weekly streams · ${owned?Math.round(owned*100)+'% owned':'No position'}</p><small>${((st.cycle-1)*100)>=0?'+':''}${((st.cycle-1)*100).toFixed(1)}% market cycle</small></button>`}).join('')}</div>`:V080_catalogFilter==='My holdings'?`<div class="catalog-market-grid">${s.v080.catalog.holdings.map(h=>{const a=s.world[h.artist],st=V080_catalogStats(a),value=cents(st.value*h.share),gain=cents(value-h.basis);return `<section class="card catalog-listing">${personPhoto('catalog-'+a.id,a.name)}<span class="eyebrow">${Math.round(h.share*100)}% ECONOMIC INTEREST</span><h2>${esc(h.name)}</h2>${profileRows([['Current value',money(value)],['Cost basis',money(h.basis)],['Unrealized gain / loss',(gain>=0?'+':'')+money(gain)],['Distributions received',money(h.payouts||0)]])}<button class="secondary" onclick="V080_sellCatalog(${h.id})">Review sale</button></section>`}).join('')||'<section class="card"><p>You do not own any outside catalogs yet.</p></section>'}</div>`:`<section class="card"><h2>Distribution history</h2>${s.v080.catalog.payouts.map(p=>`<div class="row"><span>${esc(p.name)} · Month ${p.month+1}</span><strong>${money(p.amount)}</strong></div>`).join('')||'<p>Your holdings have not paid a distribution yet.</p>'}</section>`}`}

function V080_playerAwardScore(kind){const songs=s.songs.filter(x=>x.released&&x.released>s.week-52&&x.released<=s.week),albums=s.albums.filter(x=>x.week>s.week-52&&x.week<=s.week),bestSong=songs.slice().sort((a,b)=>awardScore(b)-awardScore(a))[0],bestAlbum=albums.slice().sort((a,b)=>albumStreams(b,true)-albumStreams(a,true))[0],recentTours=s.careerRecords.tours.filter(t=>t.week>s.week-52);if(kind==='Record of the Year'||kind==='Song of the Year')return bestSong?awardScore(bestSong)+(kind==='Song of the Year'?level('writing')*.12:0):0;if(kind==='Album of the Year')return bestAlbum?Math.min(100,(bestAlbum.cohesion||50)*.35+Math.log10(1+albumStreams(bestAlbum,true))*7):0;if(kind==='Artist of the Year')return clamp(Math.log10(1+s.fans)*9+s.reputation*.25+level('marketability')*.18+(s.expansion.awardWins||0)*2,0,120);if(kind==='Best New Artist')return s.week<=104?clamp(Math.log10(1+s.fans)*10+s.reputation*.2,0,110):0;if(kind==='Best Collaboration'){const collab=songs.filter(x=>x.feature).sort((a,b)=>awardScore(b)-awardScore(a))[0];return collab?awardScore(collab)+5:0}if(kind==='Live Act of the Year'){const gross=recentTours.reduce((n,t)=>n+(t.gross||0),0);return gross?clamp(Math.log10(1+gross)*7+level('stagePresence')*.3+level('touring')*.2,0,120):0}if(kind==='Fan Choice')return clamp(Math.log10(1+s.fans)*10+Math.log10(1+(s.social?.followers||0))*4+s.loyalty*.2,0,120);return 0}
function V080_npcAwardScore(a,kind){const base=a.skill*.45+a.reputation*.25+Math.log10(1+a.fans)*5;const mod=kind==='Live Act of the Year'?a.skill*.15:kind==='Fan Choice'?Math.log10(1+a.fans)*2:kind==='Best New Artist'&&a.fans>2000000?-20:0;return base+mod}
function annualAwards080(){migrateV080();const year=Math.ceil(s.week/52),categories=['Record of the Year','Song of the Year','Album of the Year','Artist of the Year','Best New Artist','Best Collaboration','Live Act of the Year','Fan Choice'],results=[];let wins=0,noms=0;for(const category of categories){const playerScore=V080_playerAwardScore(category),npc=s.world.slice().sort((a,b)=>V080_npcAwardScore(b,category)-V080_npcAwardScore(a,category)).slice(0,7).map(a=>({name:a.name,score:V080_npcAwardScore(a,category),you:false})),pool=[...npc,{name:s.name,score:playerScore,you:true}].sort((a,b)=>b.score-a.score),nominees=pool.slice(0,5),winner=nominees[0],nominated=nominees.some(x=>x.you)&&playerScore>0,won=winner?.you&&playerScore>0;if(nominated)noms++;if(won)wins++;results.push({category,nominees:nominees.map(x=>({name:x.name,score:Math.round(x.score),you:x.you})),winner:winner?.name||null,nominated,won,score:Math.round(playerScore)})}const ceremony={year,week:s.week,results,wins,nominations:noms};s.v080.awards.ceremonies.push(ceremony);s.v080.awards.ceremonies=s.v080.awards.ceremonies.slice(-50);s.expansion.awardNominations=(s.expansion.awardNominations||0)+noms;s.expansion.awardWins=(s.expansion.awardWins||0)+wins;s.expansion.awards.push({year,title:null,score:Math.max(0,...results.map(r=>r.score)),nominated:noms>0,won:wins>0,categories:results});if(noms){addBriefing('honors:'+year,'Celebration','Year '+year+' ENCORE Honors',wins?`You won ${wins} award${wins===1?'':'s'} from ${noms} nomination${noms===1?'':'s'}.`:`You earned ${noms} nomination${noms===1?'':'s'} at the ENCORE Honors.`,'Open Career → Awards to revisit the full ceremony.');milestone('honors-'+year,wins?'ENCORE Honors winner':'ENCORE Honors nominee',wins+' wins · '+noms+' nominations')}}
annualAwards=annualAwards080;
function V080_awardsPage(){migrateV080();const ceremonies=s.v080.awards.ceremonies.slice().reverse(),latest=ceremonies[0];return head('Industry recognition, separate from game achievements','The ENCORE Honors.',`<span class="pill">${s.expansion.awardWins||0} wins</span>`)+`<section class="awards-hero"><div><span class="eyebrow">ANNUAL AWARDS SHOW</span><h1>THE ENCORE<br>HONORS</h1><p>Eight major categories judged against the living artist world using music performance, audience reach, career impact, collaborations and live success.</p></div><div class="award-stat"><strong>${s.expansion.awardWins||0}</strong><span>Career wins</span><strong>${s.expansion.awardNominations||0}</strong><span>Nominations</span></div></section>${latest?`<section class="card"><div class="sectionhead"><h2>Year ${latest.year} ceremony</h2><span>${latest.wins} wins · ${latest.nominations} nominations</span></div><div class="award-category-grid">${latest.results.map(r=>`<article class="award-category ${r.won?'winner':''}"><span class="eyebrow">${esc(r.category)}</span><h3>${esc(r.winner||'No winner')}</h3><p>${r.won?'🏆 YOU WON':r.nominated?'NOMINATED':'Not nominated'}</p><details><summary>Nominees</summary>${r.nominees.map(n=>`<div class="row"><span>${n.you?'<strong>'+esc(n.name)+'</strong>':esc(n.name)}</span><small>${n.score}</small></div>`).join('')}</details></article>`).join('')}</div></section>`:`<section class="card"><h2>Your first ceremony arrives at the end of Year 1.</h2><p>Release music, chart, tour and grow your audience to enter the conversation.</p></section>`}<section class="card"><h2>Awards history</h2>${ceremonies.map(c=>`<div class="row"><span>Year ${c.year} · ENCORE Honors</span><strong>${c.wins} wins / ${c.nominations} nominations</strong></div>`).join('')||'<p>No completed ceremonies yet.</p>'}</section>`}
function V080_milestonesPage(){const list=(s.expansion?.timeline||[]).slice().reverse();return head('Career firsts and landmark moments','Milestones.')+`<section class="card"><p>Milestones record what happened in your career. They are separate from unlockable Achievements.</p>${list.map(x=>`<div class="story"><small>WEEK ${x.week}</small><strong>${esc(x.title)}</strong><p>${esc(x.detail||'')}</p></div>`).join('')||'<p>Your next career first will appear here.</p>'}</section>`}
function V080_celebrationsPage(){const list=(s.achievements?.briefings||[]).filter(b=>b.type==='Celebration').slice();return head('The moments worth replaying','Celebrations.')+`<section class="card">${list.map(b=>`<button class="briefing-row" onclick="showBriefing('${b.id}')"><span><small>WEEK ${b.week}</small><strong>${esc(b.title)}</strong><p>${esc(b.body)}</p></span><span>Open</span></button>`).join('')||'<p>Your chart breakthroughs, certifications, tour completions and awards will collect here.</p>'}</section>`}
function V080_achievementsPage(){const defs=achievementDefinitions(),unlocked=Object.keys(s.achievements.unlocked).length,visible=defs.filter(a=>achievementFilter==='All'||(achievementFilter==='Unlocked'?!!s.achievements.unlocked[a.id]:!s.achievements.unlocked[a.id]));return head('Challenges you can unlock','Achievements.',`<span class="pill">${unlocked} / ${defs.length}</span>`)+`<p>Achievements are game challenges only. Awards, milestones, celebrations and briefings now have their own homes.</p><div class="achievement-controls"><div class="chips">${['All','Unlocked','Locked'].map(t=>`<button class="${achievementFilter===t?'selected':''}" onclick="achievementFilter='${t}';render()">${t}</button>`).join('')}</div><button class="secondary" aria-pressed="${s.achievements.popups}" onclick="toggleBriefings()">Briefing pop-ups: ${s.achievements.popups?'On':'Off'}</button></div><div class="achievement-stack">${visible.map(a=>{const earned=s.achievements.unlocked[a.id];return `<section class="card achievement-card ${earned?'earned':''}"><span class="achievement-mark">${earned?'✓':'○'}</span><div><span class="eyebrow">${esc(a.group)}</span><h2>${esc(a.title)}</h2><p>${esc(a.description)}</p><div class="bar"><i style="width:${earned?100:clamp(a.value/a.target*100)}%"></i></div><span class="fine">${earned?(earned.recovered?'Recovered from saved career · Original date unknown':'Unlocked Week '+earned.week):compact(Math.min(a.value,a.target))+' / '+compact(a.target)}</span></div></section>`}).join('')}</div>`}
achievementsPage=V080_achievementsPage;

function V080_commercePage(){return head('Products, inventory and fan commerce','Merchandise.')+`<section class="card"><h2>Commercial deals moved</h2><p>Media, endorsement, brand and partnership offers now live in the Offers Center so they are never mixed into merchandise inventory.</p><button class="secondary" onclick="openDestination('Offers')">Open Offers Center</button></section><section class="card"><h2>360 coverage</h2><p>Active 360 deals share touring, merchandise and media gross at the negotiated rate. Investments, catalog holdings and rental income remain excluded.</p></section><div class="wealth-grid">${merchItems.map(m=>`<button class="asset-tile" onclick="merchForm('${m[0]}')">${merchPhoto(m[0],0)}<h2>${m[1]}</h2><p>${money(m[2])} production per unit · Suggested price ${money(m[3])}. Set your own quantity and price.</p><strong>Create product →</strong></button>`).join('')}</div><section class="card"><h2>Inventory</h2>${s.empire.merch.map(m=>`<div class="row"><div class="merch-inventory-art">${merchPhoto(m.item,m.look||0)}</div><span>${esc(m.name)} · ${m.stock} left · ${m.sold} sold</span><strong>${money(m.price)}</strong></div>`).join('')||'<p>No merchandise produced.</p>'}</section>`}
commercePage=V080_commercePage;

const V080_merchLooks=['Midnight / gold soundwave','Ivory / cobalt geometry','Burgundy / botanical','Electric / ultraviolet','Monochrome / tour archive','Chrome / future classic'];
function V080_merchPhoto(id,look=0){const safe=Number.isInteger(look)&&look>=0&&look<V080_merchLooks.length?look:0,panel=safe%3;return `<div class="merch-photo merch-edition-${safe}" role="img" aria-label="${esc(merchItems.find(m=>m[0]===id)?.[1]||'Merchandise')}: ${V080_merchLooks[safe]}" style="background-image:url('${MERCH_ART[id]||''}');background-position:${panel*50}% center"></div>`}
merchPhoto=V080_merchPhoto;
function V080_merchChoices(id){return `<fieldset class="merch-choices"><legend>Choose your visual edition</legend>${V080_merchLooks.map((name,i)=>`<label class="merch-look">${merchPhoto(id,i)}<span><input type="radio" name="look" value="${i}" ${i===0?'checked':''}> ${name}</span></label>`).join('')}</fieldset><p class="fine">Six permanent looks per product. Visual edition changes appearance only; demand still depends on fan interest, price and your career momentum.</p>`}
merchChoices=V080_merchChoices;
function V080_createMerch(e,id){e.preventDefault();const m=merchItems.find(x=>x[0]===id),f=new FormData(e.target),qty=Number(f.get('qty')),price=Number(f.get('price'));if(!m||!Number.isInteger(qty)||qty<1||qty>1e6||!Number.isFinite(price)||price<1||price>100000)return;const look=Number(f.get('look')||0);if(!Number.isInteger(look)||look<0||look>=V080_merchLooks.length)return;pendingMerch={item:id,look,name:m[1]+' · '+V080_merchLooks[look],stock:qty,sold:0,price,cost:qty*m[2]};modal(`${merchPhoto(id,look)}<h2>Produce ${qty} ${m[1]}?</h2><p>${money(pendingMerch.cost)} upfront · 10 energy. Price ${money(price)} per unit. An active 360 share applies to sales gross.</p><button class="primary" onclick="confirmMerch()">Confirm production</button>`)}
createMerch=V080_createMerch;

function V080_personPhoto(key,name,large=false){let h=2166136261;for(const c of String(key))h=Math.imul(h^c.charCodeAt(0),16777619)>>>0;const skin=['#5b3527','#754734','#925c42','#b97958','#d19a73','#e4b990','#8d5a45','#c98b68'][h%8],hair=['#151218','#2a1a16','#3a2820','#5d3a24','#10151c','#6a4a2c'][Math.floor(h/8)%6],shirt=['#264653','#5b2a50','#33415c','#7a4b2f','#1f4d3b','#493657','#2f4858','#673c4f'][Math.floor(h/48)%8],bg=['#d7b56d','#8fb8b2','#b894c4','#a4b7d3','#d49b82','#87a57a','#c5a27a','#7aa7bd'][Math.floor(h/384)%8],hairStyle=Math.floor(h/3072)%5,earring=Math.floor(h/15360)%3===0;const hairPath=[`<path d="M22 39q2-25 28-25t28 25q-8-13-28-13T22 39" fill="${hair}"/>`,`<path d="M20 42q0-30 30-30t30 30q-4-8-10-13-2 12-20 12t-20-12q-7 5-10 13" fill="${hair}"/>`,`<path d="M24 36q8-25 26-25 24 0 30 28-9-8-16-9-2 9-14 9-14 0-18-10-5 2-8 7" fill="${hair}"/>`,`<path d="M22 41q2-25 28-25 9 0 18 5l7 18-13-7-11 5-12-6-17 10" fill="${hair}"/>`,`<path d="M25 34q4-22 25-22t26 24l-10-9-13 3-10-4-18 8" fill="${hair}"/>`][hairStyle];const svg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><rect width="100" height="100" rx="16" fill="${bg}"/><circle cx="50" cy="42" r="24" fill="${skin}"/>${hairPath}<path d="M20 100q3-31 30-31t30 31" fill="${shirt}"/><circle cx="42" cy="43" r="2" fill="#151515"/><circle cx="58" cy="43" r="2" fill="#151515"/><path d="M45 55q5 4 10 0" fill="none" stroke="#5a2f2f" stroke-width="2" stroke-linecap="round"/>${earring?'<circle cx="75" cy="50" r="2" fill="#f5df9a"/>':''}<path d="M10 83h80" stroke="rgba(255,255,255,.22)"/></svg>`;return `<span class="person-photo v080-person ${large?'portrait-large':''}" role="img" aria-label="Stylized fictional portrait of ${esc(name)}" style="background-image:url(&quot;data:image/svg+xml,${encodeURIComponent(svg)}&quot;)"></span>`}
personPhoto=V080_personPhoto;

function V080_validatePresentationState(){if(s.onboarding&&(s.onboarding.version!==1||typeof s.onboarding.seen!=='boolean'))throw Error('Invalid onboarding');if(s.collection&&(!Array.isArray(s.collection.purchased)||s.collection.purchased.length>120||new Set(s.collection.purchased).size!==s.collection.purchased.length||s.collection.purchased.some(id=>typeof id!=='string'||!/^\d+-[0-5]$/.test(id))))throw Error('Invalid collection');for(const m of s.empire.merch)if(m.look!==undefined&&(!Number.isInteger(m.look)||m.look<0||m.look>=V080_merchLooks.length))throw Error('Invalid merchandise artwork');for(const a of s.empire.assets)if(a.editionId!==undefined&&(typeof a.editionId!=='string'||!/^\d+-[0-5]$/.test(a.editionId)||typeof a.edition!=='string'))throw Error('Invalid edition');if(s.v080){if(s.v080.version!==V080_SCHEMA||!Array.isArray(s.v080.commercial?.offers)||!Array.isArray(s.v080.catalog?.holdings))throw Error('Invalid 0.8 state');for(const h of s.v080.catalog.holdings)if(!Number.isInteger(h.id)||!Number.isInteger(h.artist)||!Number.isFinite(h.share)||h.share<=0||h.share>1||!Number.isFinite(h.basis)||h.basis<0)throw Error('Invalid catalog holding')}}
validatePresentationState=V080_validatePresentationState;

const V080_createLabelOffer071=createLabelOffer;
createLabelOffer=function(i,source){const before=s.labelBusiness?.offers?.length||0;V080_createLabelOffer071(i,source);const list=s.labelBusiness?.offers||[];if(list.length>before){const o=list.at(-1);o.reviewedMonth=null;o.expires=Number.MAX_SAFE_INTEGER;o.originalExpiry=s.week+9}return list.at(-1)};
const V080_reviewArtistOffer071=reviewArtistOffer;
reviewArtistOffer=function(id){const o=s.labelBusiness?.offers?.find(x=>x.id===id&&!x.used&&x.expires>=s.week);if(o)V080_markReviewed(o);return V080_reviewArtistOffer071(id)};
const V080_counterArtistOffer071=counterArtistOffer;
counterArtistOffer=function(e,id){const result=V080_counterArtistOffer071(e,id),o=s.labelBusiness?.offers?.find(x=>x.id===id&&!x.used);if(o)V080_extendOffer(o);return result};
const V080_labelPage071=labelPage;
labelPage=function(){return V080_labelPage071().replace(/Expires after Week 9007199254740991/g,'No deadline until reviewed')};

const V080_createOpportunity071=createOpportunity;
createOpportunity=function(){const before=s.expansion.opportunities.length;V080_createOpportunity071();if(s.expansion.opportunities.length>before){const o=s.expansion.opportunities.at(-1);o.reviewedMonth=null;o.originalExpiry=o.expires;o.expires=Number.MAX_SAFE_INTEGER}};
const V080_acceptOpportunity071=acceptOpportunity;
acceptOpportunity=function(id,confirmed=false){const o=s.expansion.opportunities.find(x=>x.id===id&&!x.done&&x.expires>=s.week);if(o)V080_markReviewed(o);return V080_acceptOpportunity071(id,confirmed)};
function V080_opportunitiesPage(){const list=s.expansion.opportunities.filter(x=>!x.done&&x.expires>=s.week);return head('Appearances, features and opening doors','Career opportunities.')+`<p>Unreviewed opportunities stay open. Once reviewed, you receive a full decision window.</p>${list.map(o=>`<section class="card"><span class="eyebrow">${esc(V080_offerDeadlineText(o))}</span><h2>${esc(o.type)}</h2><p>With ${esc(o.name)} · ${money(o.fee)} · 15 energy.</p><button class="primary" onclick="V080_markReviewed(s.expansion.opportunities.find(x=>x.id==='${o.id}'));acceptOpportunity('${o.id}')">Review offer</button><button class="secondary" onclick="declineOpportunity('${o.id}')">Decline</button></section>`).join('')||'<section class="card"><p>No active career opportunities.</p></section>'}`}
opportunitiesPage=V080_opportunitiesPage;

const V080_reviewMedia071=reviewMedia;
reviewMedia=function(id){const o=s.empire.media.find(x=>x.id===id&&!x.used&&x.expires>=s.week);if(o)V080_markReviewed(o);return V080_reviewMedia071(id)};
const V080_counterMedia071=counterMedia;
counterMedia=function(e,id){const r=V080_counterMedia071(e,id),o=s.empire.media.find(x=>x.id===id&&!x.used);if(o)V080_extendOffer(o);return r};
settleCommerce=function(){const active=s.empire.merch.filter(m=>m.stock>0);for(const m of active){const spec=merchItems.find(x=>x[0]===m.item),demand=Math.max(0,Math.floor(s.fans*.015/Math.max(1,active.length)*Math.pow(spec[3]/m.price,2)*rand(.6,1.3))),sold=Math.min(m.stock,demand),gross=cents(sold*m.price);m.stock-=sold;m.sold+=sold;changeCash(gross);recordIncome('live',gross);if(sold)moneyEvent(m.name+' sales',gross)}s.empire.media=s.empire.media.filter(o=>!o.used&&o.expires>=s.week).slice(-20)};

const V080_settleAssets071=settleAssets;
settleAssets=function(){const r=V080_settleAssets071();settleCommercialContracts080();settleCatalogHoldings080();return r};

artistLabelCut=function(royalties){const c=s.expansion.contract,w=s.finance.week;if(!c)return 0;const music=(c.catalogReleased?0:royalties+(['record','distribution','360'].includes(c.type)?w.albumSales||0:0)),other=c.type==='360'?(w.live||0)+(w.media||0):0;return cents((music+other)*c.share)};
closeFinances=function(royalties,rate){const f=s.finance,w=f.week,labelCut=artistLabelCut(royalties),labelBusiness=w.labelBusiness||0,labelPayroll=w.labelPayroll||0,albumSales=w.albumSales||0,investment=w.investment||0,media=w.media||0,agentFee=agentCommission(royalties+w.live+albumSales+media),overhead=cents((royalties+w.live+albumSales)*rate+media*rate*.35),revenue=cents(royalties+w.live+w.wages+albumSales+labelBusiness+investment+media),expenses=cents(w.expenses+overhead+labelCut+agentFee);if(s.expansion.contract)s.expansion.contract.recovered=(s.expansion.contract.recovered||0)+labelCut;f.weeks++;f.revenue=cents(f.revenue+revenue);f.expenses=cents(f.expenses+expenses);const profit=cents(f.revenue-f.expenses),yearEnd=s.week%52===0,target=yearEnd?taxDue(profit):cents(taxDue(Math.max(0,profit)*52/f.weeks)*f.weeks/52),reserveChange=cents(target-f.reserve);f.reserve=target;changeCash(royalties-overhead-reserveChange-labelCut-agentFee);const report={week:s.week,revenue,investment,media,agentFee,royalties,albumSales,labelBusiness,labelPayroll,labelCut,wages:w.wages,live:w.live,expenses,actionExpenses:w.expenses,overhead,rate,taxReserve:reserveChange,net:cents(revenue-expenses-reserveChange),cash:s.cash,yearEnd,settlement:yearEnd?target:0};if(yearEnd){f.lastSettlement={year:f.year,profit,tax:target,reconciliation:reserveChange};f.taxesPaid=cents(f.taxesPaid+target);f.reserve=0;f.year++;f.weeks=0;f.revenue=0;f.expenses=0}f.week={wages:0,live:0,expenses:0};f.last=report;return report};
financeRows=function(r,full=false){const payout=cents(r.royalties+(r.albumSales||0)+(r.labelBusiness||0)-(r.labelPayroll||0)-(r.labelCut||0)-r.overhead-r.taxReserve);return [...(full?[['Taxable revenue including realized investments',money(r.revenue)],['Commercial / media income',money(r.media||0)],['Investment gains, distributions & rent',money(r.investment||0)],['Work, advances & live income',money(r.wages+r.live)],['Action costs','−'+money(r.actionExpenses-(r.labelPayroll||0))]]:[]),['Streaming royalties',money(r.royalties)],['Album downloads',money(r.albumSales||0)],['Label-business receipts',money(r.labelBusiness||0)],['Label payroll','−'+money(r.labelPayroll||0)],['Your label / 360 contract share','−'+money(r.labelCut||0)],['Career overhead','−'+money(r.overhead)],[r.taxReserve<0?'Tax reserve returned':'Tax reserve set aside',(r.taxReserve<0?'+':'−')+money(Math.abs(r.taxReserve))],[full?'Net for the whole week':'Week-close payout',money(full?r.net:payout)],['Spendable cash',money(r.cash)]]};

const V080_advance071=advance;
advance=function(confirmed=false){if(!confirmed){const weeks=monthLength(),risk=V080_offerRiskCount(weeks);modal(`<h2>Close this month?</h2><p>${weeks} chart weeks will resolve. Your unused ${s.energy}/200 energy will be replaced by 200. Music, contracts, income taxes, staff, investments, catalog holdings and rentals settle during this advance.</p><p><strong>${risk?risk+' reviewed offer'+(risk===1?'':'s')+' may expire during this advance.':'No reviewed offer is currently at risk of expiring.'}</strong> Unreviewed offers are protected until you open them.</p><button class="secondary" onclick="$('modal').close()">Keep playing</button><button class="primary" onclick="$('modal').close();advance(true)">Advance week</button>`);return}return V080_advance071(true)};

const V080_monthlyRecap071=monthlyRecap;
monthlyRecap=function(report){generateCommercialOffers080();queueSave();const unread=V080_unreadCount(),openOffers=(s.labelBusiness.offers||[]).filter(o=>!o.used&&o.expires>=s.week).length+s.v080.commercial.offers.filter(o=>o.status==='open'&&o.expires>=s.week).length;const index=report.monthIndex??Math.max(0,s.empire.month-1);modal(`<article class="month-issue"><div class="issue-masthead"><strong>ENCORE</strong><span>CAREER REPORT<br>${careerDate(index)}</span></div><div class="issue-hero"><img src="${ENCORE_ART.backstage}" alt=""><div><span>${esc(s.name)}</span><h2>${report.streams?'YOUR MONTH.<br>YOUR MOMENT.':'THE NEXT<br>CHAPTER.'}</h2></div></div><div class="issue-numbers"><div><strong>${compact(report.streams)}</strong><span>Streams</span></div><div><strong>${report.fans>=0?'+':''}${compact(report.fans)}</strong><span>Net fans</span></div><div><strong>${money(report.royalties)}</strong><span>Royalties</span></div></div><div class="issue-ledger">${profileRows([['Cash movement',money(report.cashChange)],['Tax reserve change',money(report.taxes)],['Spendable cash',money(s.cash)],['Open offers',String(openOffers)],['Unread inbox',String(unread)]])}<p>Includes assets, staff, rentals, commercial installments and catalog distributions. Chart weeks ${report.start}–${report.end} resolved.</p></div><div class="issue-actions"><button class="primary" onclick="$('modal').close()">Continue · ${careerDate()}</button><button class="secondary" onclick="$('modal').close();openDestination('Inbox')">Open Inbox${unread?' · '+unread+' new':''} →</button><button class="secondary" onclick="$('modal').close();openDestination('Offers')">Review offers →</button></div></article>`,'month-dialog')};

function V080_career(){migrateV080();const nav=careerMenu();const extra={Market:marketPage,Location:locationPage,Agency:agencyPage,League:labelLeaguePage,Social:pulsePage,Deals:dealsPage,Wealth:wealthPage,Properties:propertiesPage,Team:teamPage,Commerce:commercePage,Touring:tourPage,Campaigns:marketingPage,Opportunities:opportunitiesPage,Labels:labelPage,Legacy:V080_awardsPage,Awards:V080_awardsPage,Milestones:V080_milestonesPage,Celebrations:V080_celebrationsPage,Inbox:V080_inboxPage,Offers:V080_offersPage,CatalogMarket:V080_catalogMarketPage,Saves:savesPage};if(extra[careerTab])return nav+extra[careerTab]();if(careerTab==='Achievements')return nav+achievementsPage();if(careerTab==='Certifications')return nav+certificationsPage();if(careerTab==='Finances')return nav+financeScreen();if(careerTab==='Releases')return nav+catalog();if(careerTab==='Activity')return nav+head('Your career, week by week','Activity.')+`<section class="card">${s.history.map(x=>`<div class="story"><small>WEEK ${x.week}</small>${esc(x.text)}</div>`).join('')}</section>`;return nav+careerProfile()}
career=V080_career;

/* Ensure 0.8 migration runs during every render without replacing the existing render pipeline. */
const V080_render071=render;
render=function(){if(saveReady&&!monthlyAdvancing)migrateV080();return V080_render071()};
