/* ENCORE 0.8 compatibility fixes and copy corrections. */
renderTitle=function(){V080_renderTitle071();const root=$('title-screen');if(!root||root.hidden||!root.querySelectorAll)return;if(root.querySelector?.('[data-v080-news]'))return;const beta=[...root.querySelectorAll('button')].find(b=>/Beta info/i.test(b.textContent));if(beta&&globalThis.document?.createElement){const b=document.createElement('button');b.className='intro-secondary';b.dataset.v080News='1';b.textContent="What's new in 0.8";b.onclick=V080_whatsNew;beta.before?.(b)}};
const V080_createLabelOfferSafe=createLabelOffer;
createLabelOffer=function(i,source){const o=V080_createLabelOfferSafe(i,source);const briefing=(s.achievements?.briefings||[]).find(b=>b.id==='label-offer:'+i+':'+s.week);if(briefing){briefing.body=labelDeals[i].name+' wants to talk. Review and counter the advance, royalty split and length in Career → Offers Center or Labels. This offer will not expire until you review it; after review you receive a full decision window.';briefing.detail='Label offers stay separate from media, endorsement and brand opportunities.'}return o};

/* Keep the proven media-opportunity engine for old saves/tests, but remove it from the
   merchandise UI. Unreviewed media offers are refreshed each month so they cannot
   silently expire before the player opens them. */
settleCommerce=function(){const active=s.empire.merch.filter(m=>m.stock>0);for(const m of active){const spec=merchItems.find(x=>x[0]===m.item),demand=Math.max(0,Math.floor(s.fans*.015/Math.max(1,active.length)*Math.pow(spec[3]/m.price,2)*rand(.6,1.3))),sold=Math.min(m.stock,demand),gross=cents(sold*m.price);m.stock-=sold;m.sold+=sold;changeCash(gross);recordIncome('live',gross);if(sold)moneyEvent(m.name+' sales',gross)}for(const o of s.empire.media)if(!o.used&&(o.reviewedMonth===null||o.reviewedMonth===undefined))o.expires=s.week+9;if(s.fans>=1000){const fee=Math.max(200,Math.round(s.fans*.015*(1+socialLeverage()))),o={id:s.empire.nextId++,name:pick(['Podcast appearance','Lifestyle brand campaign','Film sync licence','Festival media interview','Fashion editorial partnership']),fee,max:Math.round(fee*(1.2+s.reputation/200+socialLeverage()*.3)),rounds:0,expires:s.week+9,used:false,reviewedMonth:null,week:s.week};s.empire.media.push(o);addBriefing('media:'+o.id,'Opportunity','A media offer arrived',o.name+' offered '+money(fee)+'. It remains protected until you review it in Career → Offers Center.','Media offers are separate from label deals and merchandise.')}s.empire.media=s.empire.media.filter(o=>!o.used&&((o.reviewedMonth===null||o.reviewedMonth===undefined)||o.expires>=s.week)).slice(-20)};

reviewMedia=function(id){const o=s.empire.media.find(x=>x.id===id&&!x.used&&((x.reviewedMonth===null||x.reviewedMonth===undefined)||x.expires>=s.week));if(!o)return;if(o.reviewedMonth===null||o.reviewedMonth===undefined){o.reviewedMonth=s.empire.month;o.reviewedWeek=s.week;o.expires=V080_reviewDeadline()}modal(`<h2>${esc(o.name)}</h2><p>Fee ${money(o.fee)} · 15 energy. Taxable commercial income; an active 360 share applies. You can request up to ${money(o.max)} based on fans, reputation and social influence.</p><p>${esc(V080_offerDeadlineText(o))}</p><form onsubmit="counterMedia(event,${id})"><label>Your requested fee<input name="fee" type="number" min="1" value="${o.fee}" required></label><button class="secondary">Send counter · 5 energy</button></form><button class="primary" onclick="acceptMedia(${id})">Accept & perform</button><button class="secondary" onclick="declineMedia(${id})">Decline</button>`);queueSave()};
counterMedia=function(e,id){e.preventDefault();const o=s.empire.media.find(x=>x.id===id&&!x.used&&x.expires>=s.week),fee=Number(new FormData(e.target).get('fee'));if(!o||!Number.isSafeInteger(fee)||fee<1||!spend(5))return;o.fee=Math.min(fee,o.max);o.rounds++;V080_extendOffer(o);render();reviewMedia(id)};
acceptMedia=function(id){const o=s.empire.media.find(x=>x.id===id&&!x.used&&((x.reviewedMonth===null||x.reviewedMonth===undefined)||x.expires>=s.week));if(!o||!spend(15))return;if(o.reviewedMonth===null||o.reviewedMonth===undefined){o.reviewedMonth=s.empire.month;o.expires=V080_reviewDeadline()}o.used=true;changeCash(o.fee);recordIncome('media',o.fee);moneyEvent(o.name+' fee',o.fee);$('modal').close();render()};
