/* ENCORE 0.8 navigation, guidance and presentation polish. */

const V080_GUIDE_TOPICS=[
['First steps','Home','Create your artist, choose a background, genre and city, then build your first audience. Backgrounds affect starting skills. The Player Guide stays available for the entire career.'],
['Career Inbox','Inbox','Inbox keeps briefings, celebrations and offers from disappearing. Unreviewed offers have no deadline. Pin anything you want to revisit.'],
['Energy and months','Home','You have 200 energy. Advancing a month resolves four or five chart weeks, settlements, tours, taxes, staff, investments and offer deadlines you have already reviewed.'],
['Make a song','Create','Choose a title, direction, production budget and creative brief. Write, record and mix in stages. Unfinished projects remain in your studio.'],
['Features and albums','Create','Add up to six guests to an active project. Finished recordings can be held for albums. Relationships, audience and reputation affect collaboration access and price.'],
['Training','Stats','Writing, Recording, Producing, Charisma and Marketability shape future work. Stage Presence, Touring and Viral Ability support live and audience systems.'],
['Charts and certifications','Industry','Charts resolve during monthly advances. Records can debut late, re-enter and earn certifications from lifetime performance.'],
['PULSE','Social','Posts, likes and replies influence engagement, label discovery and commercial leverage. Followers are reach; true fans are much stronger buyers.'],
['Offers Center','Offers','Label offers are separated from media, endorsements, brand deals, partnerships and lifetime commercial relationships. Review, counter, accept or decline from one place.'],
['Label contracts','Labels','Labels propose recording, distribution or 360 structures. As an artist you counter money, share and term—not the deal type. When you own a label, you may offer 360 contracts to your roster.'],
['Commercial deals','Offers','Deal value scales with fans, followers, engagement, reputation, awards, performance and marketability. Global icons can receive rare nine- and ten-figure partnerships or lifetime offers.'],
['Awards','Awards','The ENCORE Honors are industry awards, not Achievements. You compete against NPC artists across eight annual categories and can revisit every ceremony.'],
['Milestones and celebrations','Milestones','Milestones are career firsts and landmarks. Celebrations archive major chart, certification, tour and awards moments. Achievements remain unlockable game challenges.'],
['Catalog Market','CatalogMarket','Buy 10%, 25%, 50% or 100% economic interests in other artists’ catalogs, collect monthly distributions, hold through value changes, or sell later. Prices can fall.'],
['Touring','Touring','Plan 8–160 shows from clubs to stadiums. Fans, loyalty, performance and engaged social reach drive ticket demand. Exceptional global eras can cross $1B or $2B gross, but gross is never take-home profit.'],
['Merchandise','Commerce','Every merch category has multiple visual editions. Quantity and price affect risk; unsold inventory persists. Commercial sponsorship offers live in Offers Center, not Merchandise.'],
['Collection and assets','Wealth','Cars, property, jewelry, art and collectibles rotate through the market. Limited editions can disappear on the next monthly advance; owned items remain yours.'],
['Finances','Finances','Streaming, live, commercial, label-business and investment income feed the game tax system. A 360 can share media income; investments and outside catalog holdings remain excluded from the label share.'],
['Saves and recovery','Saves','Autosave stays tied to this browser career. Export a JSON backup before switching devices, clearing browser data or testing major updates.'],
['Navigation','Menu','The bottom bar opens Studio, PULSE, Home, Stats and Menu. The top controls always provide Back, Inbox, Guide and Settings. Menu searches every destination.']
];
function V080_guideResults(query=''){const q=query.toLowerCase().trim();return V080_GUIDE_TOPICS.filter(t=>t.join(' ').toLowerCase().includes(q)).map(([title,id,body])=>`<details class="card guide-topic"><summary>${title}</summary><p>${body}</p><button class="secondary" onclick="${id==='Home'||id==='Menu'?"go('"+id+"')":"openDestination('"+id+"')"}">Open relevant screen →</button></details>`).join('')||'<p>No matching topics. Try “offers”, “catalog”, “awards”, “tour” or “save”.</p>'}
guideResults=V080_guideResults;
guidePage=function(){return head('Your permanent player handbook','The ENCORE Guide.')+`<section class="card guide-intro"><h2>Learn at your own pace.</h2><p>Search any system, replay the optional guided tour, or practice a release. The guide never disappears and the tour never spends your energy or money.</p><div class="controls"><button class="primary" onclick="openTour(0)">Start guided tour</button><button class="secondary" onclick="startPractice()">Practice a release</button><button class="secondary" onclick="openDestination('Inbox')">Open Career Inbox</button></div></section><label class="menu-search">Search the handbook<input type="search" placeholder="Offers, awards, catalogs, songs…" oninput="$('guide-results').innerHTML=guideResults(this.value)"></label><div id="guide-results">${guideResults()}</div>`};

const V080_GAMEPLAY_TOUR=[
{page:'Home',target:'.home-dashboard',title:'Your career at a glance',text:'Cash funds choices, true fans drive real demand, and energy limits actions between monthly advances.'},
{page:'Home',target:'.home-quick',title:'Make your first moves',text:'Work creates runway, open mics build an audience and performance skills, and rest restores energy once per week.'},
{page:'Create',target:'.studio-active',title:'Build the record',text:'Write, record and mix one persistent project. Every cost and energy requirement is shown before you commit.'},
{page:'Stats',target:'.development-stack',title:'Build the artist',text:'Train core skills that affect quality, performance, appeal, negotiation and long-term career ceiling.'},
{page:'Career',section:'Social',target:'.social-profile',title:'Connect on PULSE',text:'Followers expand reach, but true fans and engagement are much stronger signals for sales, tours and commercial leverage.'},
{page:'Career',section:'Inbox',target:'#app .heading',title:'Nothing important gets lost',text:'Inbox stores briefings, offers and celebrations. Unreviewed offers are protected from expiration.'},
{page:'Career',section:'Offers',target:'#app .heading',title:'Know what kind of deal you are seeing',text:'Label offers, media, endorsements, brand deals, partnerships and lifetime relationships are separated here.'},
{page:'Career',section:'Labels',target:'#app .heading',title:'Negotiate label contracts',text:'The label proposes the contract structure. Counter the advance, share and duration—or decline. Your own label can offer 360 deals to its artists.'},
{page:'Industry',section:'Charts',target:'.chart-summary',title:'Follow the chart story',text:'Monthly advances resolve four or five chart issues. Debuts, late entries, movement, peaks and longevity reflect competition.'},
{page:'Career',section:'Touring',target:'#app .heading',title:'Build a live era',text:'Plan 8–160 shows. At global-icon scale, fan demand and stadium capacity can support billion-dollar gross eras.'},
{page:'Career',section:'Commerce',target:'#app .heading',title:'Build merchandise',text:'Choose from multiple product visuals, set quantity and price, and carry unsold inventory forward.'},
{page:'Career',section:'CatalogMarket',target:'#app .heading',title:'Own other artists’ catalogs',text:'Buy economic interests, collect distributions, watch valuations rise or fall, and sell when you choose.'},
{page:'Career',section:'Awards',target:'#app .heading',title:'Compete for the ENCORE Honors',text:'Awards are industry recognition and live separately from unlockable Achievements, Milestones and Celebrations.'},
{page:'Career',section:'Market',target:'.market-terminal',title:'Invest beyond music',text:'The fictional exchange and Catalog Market can both make or lose money. Investments remain outside label 360 shares.'},
{page:'Career',section:'Saves',target:'#app .heading',title:'Protect the career',text:'Export backups before changing devices, clearing browser data or experimenting with major updates.'},
{page:'Menu',target:'#menu-results',title:'Every system has a home',text:'Menu searches every destination. Every normal screen keeps Back, Inbox, Guide and Settings within reach.'},
{page:'Home',target:'.weekbar',title:'Advance deliberately',text:'Before closing a month, ENCORE warns you about reviewed offers at risk. Unreviewed offers remain protected.'}
];
openTour=function(step=0){if(!saveReady||saveConflict)return;if($('modal').open)$('modal').close();if(tourStep<0)tourOrigin={tab,careerTab,industryTab,chartKind,chartMine};titleVisible=false;tourStep=Math.max(0,Math.min(V080_GAMEPLAY_TOUR.length-1,step));renderTitle();const t=V080_GAMEPLAY_TOUR[tourStep];if(t.page==='Industry'){industryTab=t.section;if(t.section==='Charts'){chartKind='Songs';chartMine=false}}if(t.page==='Career')careerTab=t.section;tab=t.page;render();renderGameplayTour()};
renderGameplayTour=function(){const panel=$('gameplay-tour');if(!panel)return;clearTourTarget();panel.hidden=tourStep<0;document.body?.classList[tourStep>=0?'add':'remove']('tour-running');for(const el of document.querySelectorAll?.('main,nav,.weekbar')||[])el.inert=tourStep>=0;if(tourStep<0)return;const t=V080_GAMEPLAY_TOUR[tourStep];panel.innerHTML=`<div class="coach-inner"><div class="coach-top"><span>GAMEPLAY TOUR · ${tourStep+1} / ${V080_GAMEPLAY_TOUR.length}</span><button class="text-button" onclick="endTour()">Skip tour</button></div><h2 id="coach-title">${esc(t.title)}</h2><p>${esc(t.text)}</p><div class="coach-controls"><button class="secondary" onclick="${tourStep===0?'endTour()':'openTour(tourStep-1)'}">Back</button><span>${esc(t.page)}${t.section?' · '+esc(t.section):''}</span><button class="primary" onclick="${tourStep===V080_GAMEPLAY_TOUR.length-1?'endTour()':'openTour(tourStep+1)'}">${tourStep===V080_GAMEPLAY_TOUR.length-1?'Finish tour':'Next'}</button></div></div>`;const target=document.querySelector?.(t.target);if(target){tourTarget=target;target.classList?.add('tour-target');if(target.style)target.style.scrollMarginTop=((panel.getBoundingClientRect?.().height||220)+18)+'px';target.scrollIntoView?.({behavior:'auto',block:'start'})}panel.querySelector?.('h2')?.setAttribute('tabindex','-1');panel.querySelector?.('h2')?.focus({preventScroll:true})};

const V080_home071=home;
home=function(){return V080_home071().replace(/careerTab='Achievements';go\('Career'\)/g,"openDestination('Inbox')").replace(/<strong>Briefings /g,'<strong>Inbox ').replace(/careerTab='Deals';go\('Career'\)/g,"openDestination('Offers')").replace(/Your deal room/g,'Offers Center').replace(/Labels, ownership & opportunities/g,'Labels, brand deals & opportunities')};
briefingShortcut=function(){const unread=V080_unreadCount();return `<button class="briefing-shortcut" onclick="openDestination('Inbox')"><span><strong>Career Inbox</strong><small>${unread?unread+' unread':'You’re caught up'} · offers, briefings & celebrations</small></span><span>Open</span></button>`};
offerBriefingButton=function(b){if(b.id.startsWith('agent:')||b.id.startsWith('agent-offer:'))return `<button class="memo-primary" onclick="$('modal').close();openDestination('Agency')">Review agent</button>`;if(b.id.startsWith('label-offer:')){const parts=b.id.split(':'),id='label-'+parts[1]+'-'+parts[2];return `<button class="memo-primary" onclick="$('modal').close();reviewArtistOffer('${id}')">Review label offer</button>`}if(b.id.startsWith('media:')||b.id.startsWith('commercial:'))return `<button class="memo-primary" onclick="$('modal').close();openDestination('Offers')">Review in Offers Center</button>`;if(b.id.startsWith('honors:'))return `<button class="memo-primary" onclick="$('modal').close();openDestination('Awards')">Open ENCORE Honors</button>`;if(b.id.startsWith('late-chart:'))return `<button class="memo-primary" onclick="$('modal').close();industryTab='Charts';go('Industry')">View charts</button>`;return ''};

function V080_whatsNew(){modal(`<span class="eyebrow">ENCORE · 0.8</span><h2>A bigger career world.</h2><ul><li>Career Inbox keeps missed briefings and unreviewed offers safe.</li><li>Offers Center separates labels, media, endorsements, brand deals, partnerships and lifetime offers.</li><li>The ENCORE Honors adds a full awards history separate from Achievements and Milestones.</li><li>Catalog Market lets you buy, hold, collect payouts from and sell other artists’ music rights.</li><li>Commercial deals now scale from early-career opportunities to rare billion-dollar icon partnerships.</li><li>Merch has six visual editions and the monthly collection rotates more choices.</li><li>Updated walkthrough directions match the current layout.</li></ul><button class="primary" onclick="$('modal').close()">Back to ENCORE</button>`)}
const V080_renderTitle071=renderTitle;
renderTitle=function(){V080_renderTitle071();const root=$('title-screen');if(!root||root.hidden||root.querySelector('[data-v080-news]'))return;const beta=[...root.querySelectorAll('button')].find(b=>/Beta info/i.test(b.textContent));if(beta){const b=document.createElement('button');b.className='intro-secondary';b.dataset.v080News='1';b.textContent="What's new in 0.8";b.onclick=V080_whatsNew;beta.before(b)}};

currentDrops=function(){const items=wealthItems.filter(x=>!marketInstrument(x.id)),month=s.empire.month,count=Math.min(10,Math.max(1,items.length));return Array.from({length:count},(_,i)=>{const item=items[(month*7+i*5+i*i)%items.length],limited=i<4,edition=editionNames[(month+i*2)%editionNames.length];return {id:month+'-'+i,month,item:item.id,name:item.name+' · '+edition,price:cents(item.price*(limited?1.08+(i%3)*.045:1+(i%4)*.018)),edition,limited}})};
collectionDrops=function(){migrateCollection();const drops=currentDrops();return `<section class="card collection-drop"><span class="eyebrow">MONTHLY COLLECTION · ${careerDate()}</span><h2>Rotating assets & limited editions</h2><p>${drops.length} image-backed opportunities rotate each month. The first four are limited collector editions; the rest are rotating market selections. Owned assets remain yours after the rotation changes.</p><div class="wealth-grid">${drops.map(d=>{const item=wealthItems.find(x=>x.id===d.item),sold=s.collection.purchased.includes(d.id);return `<button class="asset-tile" ${sold?'disabled':''} onclick="reviewDrop('${d.id}')">${assetPhoto(item)}<small>${d.limited?'LIMITED · THIS MONTH':'MONTHLY ROTATION'}</small><h3>${esc(d.name)}</h3><strong>${money(d.price)}</strong><p>${sold?'Acquired':'Review purchase →'}</p></button>`}).join('')}</div></section>`};
validatePresentationState=function(){if(s.onboarding&&(s.onboarding.version!==1||typeof s.onboarding.seen!=='boolean'))throw Error('Invalid onboarding');if(s.collection&&(!Array.isArray(s.collection.purchased)||s.collection.purchased.length>180||new Set(s.collection.purchased).size!==s.collection.purchased.length||s.collection.purchased.some(id=>typeof id!=='string'||!/^\d+-(?:[0-9]|1[01])$/.test(id))))throw Error('Invalid collection');for(const m of s.empire.merch)if(m.look!==undefined&&(!Number.isInteger(m.look)||m.look<0||m.look>=V080_merchLooks.length))throw Error('Invalid merchandise artwork');for(const a of s.empire.assets)if(a.editionId!==undefined&&(typeof a.editionId!=='string'||!/^\d+-(?:[0-9]|1[01])$/.test(a.editionId)||typeof a.edition!=='string'))throw Error('Invalid edition');if(s.v080){if(s.v080.version!==V080_SCHEMA||!Array.isArray(s.v080.commercial?.offers)||!Array.isArray(s.v080.catalog?.holdings))throw Error('Invalid 0.8 state');for(const h of s.v080.catalog.holdings)if(!Number.isInteger(h.id)||!Number.isInteger(h.artist)||!Number.isFinite(h.share)||h.share<=0||h.share>1||!Number.isFinite(h.basis)||h.basis<0)throw Error('Invalid catalog holding')}};


/* The original render already runs migrations before building UI; use it directly so 0.8 migration is invoked from the new navigation/page functions after those migrations are ready. */
render=V080_render071;
