/* ENCORE 0.8.1 depth pass: label intelligence, artist development,
   creative services, messaging, deeper investing and financial visibility. */

const V081_SCHEMA=1;
const V081_UPGRADE_KEYS=['equipment','marketing','logistics','touring','merch'];
const V081_UPGRADE_META={
  equipment:{name:'Studio equipment',desc:'Improves roster development and release performance.',base:50000},
  marketing:{name:'Label marketing',desc:'Improves first-month reach for roster releases.',base:75000},
  logistics:{name:'Operations & logistics',desc:'Reduces label payroll drag and keeps projects moving.',base:60000},
  touring:{name:'Touring infrastructure',desc:'Raises simulated live opportunity value for 360 artists.',base:100000},
  merch:{name:'Merch infrastructure',desc:'Raises simulated merchandise opportunity value for 360 artists.',base:80000}
};
const V081_DEV_KEYS=['writing','recording','producing','charisma','marketability','stage','touring','viral'];
let V081_featureAccessFilter='Available',V081_featureGenre='All',V081_featurePage=0,V081_creativeTab='Opportunities',V081_sportsTab='Market';

function migrateV081(){
  migrateV080?.();
  if(!s.v081)s.v081={version:V081_SCHEMA,label:{upgrades:Object.fromEntries(V081_UPGRADE_KEYS.map(k=>[k,0])),artistDev:{}},creative:{offers:[],nextId:1,lastGeneratedMonth:-1,songMarket:[],songNextId:1,songMarketMonth:-1},messages:{threads:{},nextId:1},sports:{holdings:[],nextId:1,teams:null,lastSettledMonth:-1},lastSettledMonth:-1};
  const v=s.v081;v.version=V081_SCHEMA;
  v.label??={upgrades:{},artistDev:{}};v.label.upgrades??={};v.label.artistDev??={};for(const k of V081_UPGRADE_KEYS)if(!Number.isInteger(v.label.upgrades[k]))v.label.upgrades[k]=0;
  v.creative??={offers:[],nextId:1,lastGeneratedMonth:-1,songMarket:[],songNextId:1,songMarketMonth:-1};v.creative.offers??=[];v.creative.songMarket??=[];v.creative.nextId??=1;v.creative.songNextId??=1;v.creative.lastGeneratedMonth??=-1;v.creative.songMarketMonth??=-1;
  v.messages??={threads:{},nextId:1};v.messages.threads??={};v.messages.nextId??=1;
  v.sports??={holdings:[],nextId:1,teams:null,lastSettledMonth:-1};v.sports.holdings??=[];v.sports.nextId??=1;
  if(!Array.isArray(v.sports.teams))v.sports.teams=V081_makeSportsTeams();
  for(const a of s.empire?.assets||[]){a.history??=[];a.boughtMonth??=s.empire?.month??0}
  if(s.market?.quotes)for(const q of Object.values(s.market.quotes)){q.monthlyHistory??=[q.price];q.monthlyMonths??=[s.empire?.month??0]}
  if(Array.isArray(V080_destinations)&&!V080_destinations.some(d=>d[2]==='Creative'))V080_destinations.push(['Creative opportunities','Business','Creative','Ghostwriting, production, song offers and DMs',4]);
  if(Array.isArray(V080_destinations)&&!V080_destinations.some(d=>d[2]==='Sports'))V080_destinations.push(['Sports ownership','Wealth','Sports','Buy franchise stakes and follow full seasons',2]);
}

function V081_pct(n,d=1){return (n>=0?'+':'')+(n*100).toFixed(d)+'%'}
function V081_releaseDateForWeek(week){const month=Math.max(0,Math.floor((Math.max(1,week)-1)*12/52));return typeof careerDate==='function'?careerDate(month):'Week '+week}
function V081_spark(values,label='Trend'){const a=(values||[]).filter(Number.isFinite);if(a.length<2)return '<p class="fine">Trend builds after more monthly updates.</p>';const min=Math.min(...a),max=Math.max(...a),spread=Math.max(.01,max-min),pts=a.map((v,i)=>(i/Math.max(1,a.length-1)*600).toFixed(1)+','+(145-(v-min)/spread*120).toFixed(1)).join(' ');return `<svg class="v081-chart" viewBox="0 0 600 165" role="img" aria-label="${esc(label)}. Low ${money(min)}, high ${money(max)}"><path d="M0 145H600M0 85H600M0 25H600"/><polyline points="${pts}" fill="none" stroke="currentColor" stroke-width="3" stroke-linejoin="round"/></svg>`}
function V081_taxRateForAsset(x){return x.kind==='Property'?.02:['Stocks','Bonds','Crypto'].includes(x.kind)?0:.08}
function V081_assetForecast(x){const annual=((1+(x.drift||0))**12-1),band=Math.min(.95,Math.max(.03,(x.vol||.02)*Math.sqrt(12)*1.5));return {expected:annual,low:Math.max(-.95,annual-band),high:annual+band}}
function V081_assetAvailability(x){if(x.editionId)return 'Limited edition · owned';if(['Cars','Jewelry','Art','Property'].includes(x.kind))return 'Core market · subject to monthly limited editions';return 'Simulated market · while listed'}
function V081_riskLabel(vol){return vol>=.15?'Very high':vol>=.07?'High':vol>=.025?'Moderate':'Low'}

function V081_marketMonthlySnapshot(){if(!s.market?.quotes)return;for(const q of Object.values(s.market.quotes)){q.monthlyHistory??=[];q.monthlyMonths??=[];if(q.monthlyMonths.at(-1)!==s.empire.month){q.monthlyMonths.push(s.empire.month);q.monthlyHistory.push(q.price);q.monthlyMonths=q.monthlyMonths.slice(-24);q.monthlyHistory=q.monthlyHistory.slice(-24)}}}

const V081_assetDetail080=assetDetail;
assetDetail=function(id){migrateV081();if(marketInstrument(id)){tradeForm(id);return}const x=wealthItems.find(x=>x.id===id);if(!x)return;const taxRate=V081_taxRateForAsset(x),tax=cents(x.price*taxRate),f=V081_assetForecast(x);modal(`${assetPhoto(x)}<span class="eyebrow">${esc(x.kind)} · INVESTMENT PROFILE</span><h2>${esc(x.name)}</h2><p>${esc(x.desc)}</p>${profileRows([['Price',money(x.price)],['Purchase tax',money(tax)+' · '+(taxRate*100).toFixed(0)+'%'],['All-in cost',money(x.price+tax)],['Availability',V081_assetAvailability(x)],['Estimated annual value range',V081_pct(f.low)+' to '+V081_pct(f.high)],['Trend midpoint',V081_pct(f.expected)],['Volatility',V081_riskLabel(x.vol||0)+' · '+((x.vol||0)*100).toFixed(1)+'% monthly simulation'],['Income yield',x.rent?money(x.rent)+'/month asking rent':x.yield?((x.yield*12)*100).toFixed(2)+'% annualized simulated distribution':'None']])}<p class="fine">The annual range is a game forecast based on this asset’s trend and volatility. It is not guaranteed: value can finish outside the range.</p><form class="form" onsubmit="reviewAssetBuy(event,'${id}')"><label>Quantity<input name="qty" type="number" min="1" max="1000000" step="1" value="1" required></label><button class="primary">Review purchase</button></form>`)};

const V081_reviewAssetBuy080=reviewAssetBuy;
reviewAssetBuy=function(event,id){migrateV081();const x=wealthItems.find(x=>x.id===id);if(!x)return;V081_reviewAssetBuy080(event,id);const el=$('modal'),f=V081_assetForecast(x);if(el?.open)el.innerHTML+=`<section class="investment-note"><strong>Projected annual value range</strong><span>${V081_pct(f.low)} to ${V081_pct(f.high)}</span><small>Forecast only · actual simulation may finish outside this range.</small></section>`};

const V081_confirmAssetBuy080=confirmAssetBuy;
confirmAssetBuy=function(){const before=new Set((s.empire?.assets||[]).map(a=>a.id));V081_confirmAssetBuy080();migrateV081();for(const a of s.empire.assets||[])if(!before.has(a.id)){a.boughtMonth=s.empire.month;a.history=[{month:s.empire.month,value:a.value}]}};

const V081_holdingDetail080=holdingDetail;
holdingDetail=function(id){migrateV081();const a=s.empire.assets.find(x=>x.id===id);if(!a)return;V081_holdingDetail080(id);const x=wealthItems.find(x=>x.id===a.item),f=x?V081_assetForecast(x):null,el=$('modal');if(el?.open&&x){const hist=(a.history||[]).map(h=>h.value);el.innerHTML+=`<section class="card"><h3>Value outlook</h3>${profileRows([['Annual forecast range',V081_pct(f.low)+' to '+V081_pct(f.high)],['Months owned',Math.max(0,s.empire.month-(a.boughtMonth??s.empire.month))],['Value change %',a.basis?V081_pct(a.value/a.basis-1):'—']])}${V081_spark(hist,'Monthly holding value trend')}</section>`}};

const V081_reviewDrop080=reviewDrop;
reviewDrop=function(id){migrateV081();V081_reviewDrop080(id);const d=currentDrops().find(x=>x.id===id),item=d&&wealthItems.find(x=>x.id===d.item),el=$('modal');if(el?.open&&d&&item){const f=V081_assetForecast(item);el.innerHTML+=`<section class="investment-note"><strong>Estimated annual value range</strong><span>${V081_pct(f.low)} to ${V081_pct(f.high)}</span><small>Limited status affects availability, not a guaranteed resale premium.</small></section>`}};

const V081_marketPage080=marketPage;
marketPage=function(){migrateV081();V081_marketMonthlySnapshot();const spec=marketInstrument(marketSelected),q=spec&&s.market.quotes[spec.id],item=spec&&wealthItems.find(x=>x.id===spec.id);if(!spec||!q||!item)return V081_marketPage080();const hist=q.monthlyHistory||[q.price],first=hist[0]||q.price,change=q.price/(first||q.price)-1,oneTick=q.previous?q.price/q.previous-1:0,annualDiv=(item.yield||0)*12;const intelligence=`<section class="card market-intelligence"><span class="eyebrow">INVESTMENT INTELLIGENCE</span><h2>${esc(item.name)} · ${esc(spec.ticker)}</h2>${profileRows([['Sector',spec.sector],['Current price',money(q.price)],['Latest change',V081_pct(oneTick,2)],['Tracked-period change',V081_pct(change,2)],['Volatility',V081_riskLabel(spec.vol)+' · '+(spec.vol*100).toFixed(2)+'% per live tick'],['Dividend / distribution',annualDiv?V081_pct(annualDiv,2)+' annualized':'None'],['History shown',Math.max(1,hist.length)+' monthly snapshots']])}${V081_spark(hist,`${spec.ticker} monthly simulated price trend`)}<p class="fine">All securities in ENCORE are fictional. Percent changes and charts come from the game simulation, not real markets.</p></section>`;return V081_marketPage080().replace('<section class="card market-terminal">',intelligence+'<section class="card market-terminal">')};

const V081_tradeForm080=tradeForm;
tradeForm=function(id,side='buy'){migrateV081();V081_tradeForm080(id,side);const spec=marketInstrument(id),item=wealthItems.find(x=>x.id===id),q=s.market?.quotes?.[id],el=$('modal');if(el?.open&&spec&&item&&q){const hist=q.monthlyHistory||[q.price];el.innerHTML+=`<section class="investment-note"><strong>${esc(spec.sector)} · ${V081_riskLabel(spec.vol)} volatility</strong><span>${(item.yield||0)?'Annualized distribution '+V081_pct((item.yield||0)*12,2):'No distribution'}</span><small>${hist.length>1?'Tracked-period change '+V081_pct(q.price/hist[0]-1,2):'Monthly history starts after your next advance.'}</small></section>`}};

function V081_catalogRange(a){const st=V080_catalogStats(a),durability=clamp((a.skill||50)*.35+(a.reputation||50)*.25+Math.log10(1+(a.fans||0))*5,0,100),mid=.02+(durability/100)*.12,vol=.08+(1-durability/100)*.18;return {st,low:Math.max(-.5,mid-vol),high:mid+vol,mid}}
function V081_catalogChart(h){return V081_spark((h?.history||[]).map(x=>x.value),'Monthly catalog position value')}
const V081_catalogBuyForm080=V080_catalogBuyForm;
V080_catalogBuyForm=function(id){migrateV081();V081_catalogBuyForm080(id);const a=s.world[id],el=$('modal');if(el?.open&&a){const r=V081_catalogRange(a);el.innerHTML+=`<section class="investment-note"><strong>Estimated annual catalog value range</strong><span>${V081_pct(r.low)} to ${V081_pct(r.high)}</span><small>Driven by current streams, artist momentum, skill, reputation and market-cycle variance.</small></section>`}};
const V081_reviewCatalogPurchase080=V080_reviewCatalogPurchase;
V080_reviewCatalogPurchase=function(id,share){V081_reviewCatalogPurchase080(id,share);const a=s.world[id],el=$('modal');if(el?.open&&a){const r=V081_catalogRange(a);el.innerHTML+=`<section class="investment-note"><strong>Annual value forecast</strong><span>${V081_pct(r.low)} to ${V081_pct(r.high)}</span><small>Payouts are separate from market-value changes and continue while you hold the interest.</small></section>`}};

const V081_catalogMarketPage080=V080_catalogMarketPage;
V080_catalogMarketPage=function(){migrateV081();const base=V081_catalogMarketPage080();if(V080_catalogFilter!=='Marketplace')return base;if(!s.world?.length)return base;return base.replace('<p>Buy economic interests',`<section class="card"><h2>How to read catalog investments</h2><p>Every catalog has a simulated annual appreciation/depreciation range. Payout yield and market value are separate: a catalog can pay you while its resale value falls, or appreciate while current payouts soften.</p></section><p>Buy economic interests`)};

function V081_artistDev(a){migrateV081();const key=String(a.id),seed=Math.round(a.skill||50);if(!s.v081.label.artistDev[key])s.v081.label.artistDev[key]={xp:0,skills:{writing:seed,recording:seed,producing:Math.max(20,seed-5),charisma:Math.max(20,Math.round(a.reputation||seed)),marketability:Math.max(20,Math.round((a.reputation||seed)*.9)),stage:Math.max(20,seed-3),touring:Math.max(20,seed-5),viral:Math.max(20,Math.round((a.reputation||seed)*.8))}};return s.v081.label.artistDev[key]}
function V081_devAverage(dev){return Math.round(Object.values(dev.skills).reduce((n,x)=>n+x,0)/V081_DEV_KEYS.length)}
function V081_upgradeLevel(k){migrateV081();return s.v081.label.upgrades[k]||0}
function V081_upgradeCost(k){const lvl=V081_upgradeLevel(k),m=V081_UPGRADE_META[k];return lvl>=5?0:Math.round(m.base*Math.pow(2.25,lvl))}
function V081_upgradeLabel(k,confirmed=false){migrateV081();const co=s.labelBusiness?.company,m=V081_UPGRADE_META[k],lvl=V081_upgradeLevel(k),cost=V081_upgradeCost(k);if(!co||!m||lvl>=5)return;if(!confirmed){modal(`<h2>Upgrade ${m.name}?</h2>${profileRows([['Current level',lvl+' / 5'],['Next level',lvl+1+' / 5'],['Investment',money(cost)]])}<p>${m.desc}</p><button class="primary" onclick="V081_upgradeLabel('${k}',true)">Invest ${money(cost)}</button>`);return}if(s.cash<cost){toast('Not enough cash for this label upgrade.');return}changeCash(-cost);s.v081.label.upgrades[k]++;moneyEvent('Label upgrade · '+m.name,-cost);$('modal').close();render()}

const V081_labelPayroll080=labelPayroll;
labelPayroll=function(){const base=V081_labelPayroll080(),lvl=V081_upgradeLevel('logistics');return cents(base*(1-lvl*.04))};

function V081_artistProject(a){const until=Math.max(0,(a.nextRelease||s.week)-s.week),type=until<=2?'Single / feature window':until<=5?'Single or EP work':'Early project development',stage=until<=1?'Final masters / scheduling':until<=3?'Recording & post-production':until<=6?'Writing / recording':'Concept & writing';return {type,stage,release:V081_releaseDateForWeek(a.nextRelease||s.week+4),weeks:until,title:until<=2?generate('song'):'Untitled project'}}
function V081_artistNetWorth(a){const weekly=(a.catalog||[]).reduce((n,x)=>n+(x.streams||0),0),career=(a.catalog||[]).reduce((n,x)=>n+(x.total||0),0),cash=Math.max(500,weekly*.5*8+career*.015),assets=Math.max(0,(a.fans||0)*(.12+((a.id%7)/100)));return Math.round(cash+assets)}
function V081_artistInvestments(a){const options=['Index funds','Property','Art','Private businesses','Catalog rights','Sports ownership'];const n=Math.min(3,1+tier(a.fans)%3);return Array.from({length:n},(_,i)=>options[(a.id*3+i+tier(a.fans))%options.length])}
function V081_artistCard(a,c){const dev=V081_artistDev(a),p=V081_artistProject(a);return `<section class="card roster-intel">${personPhoto('artist-'+(a.directoryKey??a.id),a.name)}<span class="eyebrow">ROSTER INTELLIGENCE</span><h3>${esc(a.name)}</h3>${profileRows([['Deal',c.type==='360'?'360':c.type==='distribution'?'Distribution':'Recording'],['Current project',p.type],['Stage',p.stage],['Projected release',p.release],['Overall skill',V081_devAverage(dev)+'/100'],['Relationship',(a.relation>0?'+':'')+a.relation]])}<div class="mini-skill-grid">${V081_DEV_KEYS.map(k=>`<span><small>${k}</small><strong>${dev.skills[k]}</strong></span>`).join('')}</div><div class="controls"><button class="secondary" onclick="V081_artistDevelopment(${a.id})">Develop artist</button><button class="secondary" onclick="V081_openDM(${a.id})">Message</button></div></section>`}

const V081_companyPage080=companyPage;
companyPage=function(){migrateV081();const html=V081_companyPage080(),co=s.labelBusiness?.company;if(!co)return html;const upgrades=`<section class="card"><span class="eyebrow">LABEL INFRASTRUCTURE</span><h2>Build the machine around your roster</h2><p>These investments apply to every active artist on your label. Upgrades are permanent and stack with hired staff.</p><div class="upgrade-grid">${V081_UPGRADE_KEYS.map(k=>{const m=V081_UPGRADE_META[k],lvl=V081_upgradeLevel(k),cost=V081_upgradeCost(k);return `<div class="upgrade-card"><strong>${m.name}</strong><span>Level ${lvl}/5</span><p>${m.desc}</p><button class="secondary" ${lvl>=5?'disabled':''} onclick="V081_upgradeLabel('${k}')">${lvl>=5?'Maxed':'Upgrade · '+money(cost)}</button></div>`}).join('')}</div></section>`;const roster=ownerContracts().length?`<section class="card"><span class="eyebrow">ARTIST DEVELOPMENT & PROJECTS</span><h2>Your roster in motion</h2><p>See what each artist is working on, projected release timing and development progress.</p></section><div class="roster-intel-grid">${ownerContracts().map(c=>V081_artistCard(s.world[c.artist],c)).join('')}</div>`:'';return html+upgrades+roster};

function V081_artistDevelopment(id){migrateV081();const a=s.world[id],c=ownerContracts().find(c=>c.artist===id);if(!a||!c)return;const d=V081_artistDev(a);modal(`${personPhoto('artist-'+(a.directoryKey??a.id),a.name,true)}<span class="eyebrow">ARTIST DEVELOPMENT</span><h2>${esc(a.name)}</h2><p>Invest directly in a skill. Label equipment and logistics also help organic monthly growth.</p><div class="development-stack">${V081_DEV_KEYS.map(k=>`<div class="row"><span>${k[0].toUpperCase()+k.slice(1)}</span><strong>${d.skills[k]}/100</strong><button class="secondary" ${d.skills[k]>=100?'disabled':''} onclick="V081_trainRosterArtist(${id},'${k}')">Train · ${money(2500+Math.round(d.skills[k]**2*8))}</button></div>`).join('')}</div><p class="fine">Development changes future releases and career growth; it does not rewrite records already released.</p>`)}
function V081_trainRosterArtist(id,k){const a=s.world[id],d=a&&V081_artistDev(a);if(!a||!d||!V081_DEV_KEYS.includes(k)||d.skills[k]>=100)return;const cost=2500+Math.round(d.skills[k]**2*8);if(s.cash<cost){toast('Not enough label cash for this session.');return}changeCash(-cost);d.skills[k]=Math.min(100,d.skills[k]+Math.max(1,Math.round(5-d.skills[k]/30)));a.skill=V081_devAverage(d);moneyEvent('Artist development · '+a.name+' · '+k,-cost);render();V081_artistDevelopment(id)}
function V081_settleRosterDevelopment(){const co=s.labelBusiness?.company;if(!co)return;for(const c of ownerContracts()){const a=s.world[c.artist],d=V081_artistDev(a),gain=1+V081_upgradeLevel('equipment')*.45+V081_upgradeLevel('logistics')*.2;d.xp+=gain;while(d.xp>=4){d.xp-=4;const keys=V081_DEV_KEYS.filter(k=>d.skills[k]<100);if(!keys.length)break;const k=keys[(s.empire.month+a.id)%keys.length];d.skills[k]++;}a.skill=V081_devAverage(d)}}

const V081_worldWeek080=worldWeek;
worldWeek=function(){migrateV081();const before=new Map(s.world.map(a=>[a.id,(a.catalog||[]).length]));V081_worldWeek080();const co=s.labelBusiness?.company;if(!co)return;for(const c of ownerContracts()){const a=s.world[c.artist],start=before.get(a.id)||0,newReleases=a.catalog.slice(start);if(!newReleases.length)continue;const bonus=.03*V081_upgradeLevel('equipment')+.05*V081_upgradeLevel('marketing');for(const x of newReleases){const extra=Math.round((x.streams||0)*bonus);x.streams+=extra;x.total=(x.total||0)+extra;a.weekly=(a.weekly||0)+extra;const feed=s.feed.find(f=>f.week===s.week&&f.name===a.name&&f.title===x.title);if(feed)feed.streams=x.streams}}};

function V081_rosterInterest(a,t){const req=rosterTerms(a,t.type,t.share,t.weeks),advanceRatio=t.advance/Math.max(1,req.minimum),sharePressure=Math.max(0,t.share-.12)*120,termPressure=Math.max(0,t.weeks-52)*.22,typePenalty=t.type==='360'?10:t.type==='distribution'?-5:0;let score=55+a.relation*.25+(s.reputation-req.reputation)*.35+(advanceRatio-1)*36-sharePressure-termPressure-typePenalty+V081_upgradeLevel('marketing')*2+V081_upgradeLevel('equipment');score=clamp(Math.round(score),0,100);const walk=clamp(Math.round(88-score*.75+(advanceRatio<.85?14:0)),3,92);return {score,walk,minimum:req.minimum,reputation:req.reputation,label:score>=85?'Eager':score>=68?'Strong interest':score>=50?'Interested':score>=35?'Cautious':'At risk'}}
function V081_interestMeter(m){return `<div class="interest-meter"><div><span>Interest</span><strong>${m.label} · ${m.score}/100</strong></div><div class="bar"><i style="width:${m.score}%"></i></div><small>Estimated walk-away risk if you push these exact terms: ${m.walk}%</small></div>`}
const V081_previewRosterTerms080=previewRosterTerms;
previewRosterTerms=function(form,id){try{const t=readRosterTerms(form),a=s.world[id],m=V081_rosterInterest(a,t),el=$('roster-preview');if(el)el.innerHTML=`Requested advance ${money(m.minimum)} · Reputation ${s.reputation}/${m.reputation}${V081_interestMeter(m)}`}catch{V081_previewRosterTerms080(form,id)}};
const V081_rosterOfferForm080=rosterOfferForm;
rosterOfferForm=function(id){V081_rosterOfferForm080(id);const el=$('modal'),a=s.world[id];if(el?.open&&a)el.innerHTML+=`<p class="fine">Interest updates live as you change advance, label share, contract type and term. It is a negotiation signal—not a guarantee.</p>`};
const V081_reviewRosterOffer080=reviewRosterOffer;
reviewRosterOffer=function(e,id){let t,m;try{t=readRosterTerms(e.target);m=V081_rosterInterest(s.world[id],t)}catch{}V081_reviewRosterOffer080(e,id);const el=$('modal');if(el?.open&&m)el.innerHTML+=V081_interestMeter(m)};

const V081_quote080=quote;
quote=function(a){const q=V081_quote080(a);if(q===0&&freeEligible(a))return Math.max(25,Math.min(5000,Math.round(baseFee(a)*.02/5)*5));return q};
function V081_charityAmount(a){return Math.max(100,Math.min(10000,Math.round(baseFee(a)*.0125/25)*25))}
function V081_charityFeature(id){const a=s.world[id],d=s.draft;if(!a||!d||!freeEligible(a)||guestList(d).some(g=>g.id===id)||guestList(d).length>=6)return;const donation=V081_charityAmount(a);if(!spend(5,donation))return;d.features=[...guestList(d),{id,name:a.name,fans:a.fans,fee:0,charity:donation}];d.feature=d.features[0];a.relation=clamp(a.relation+3,-100,100);moneyEvent('Donation for '+a.name+' feature',-donation);$('modal').close();render();toast(a.name+' joined the record after your '+money(donation)+' donation.')}
const V081_studioGuest080=studioGuest;
studioGuest=function(id){V081_studioGuest080(id);const a=s.world[id],el=$('modal');if(el?.open&&a&&freeEligible(a)&&s.draft&&!guestList(s.draft).some(g=>g.id===id))el.innerHTML+=`<section class="card"><h3>Inner-circle option</h3><p>${esc(a.name)} is close enough to keep the verse price symbolic. You can pay the courtesy fee above, or donate ${money(V081_charityAmount(a))} to a cause they support instead.</p><button class="secondary" onclick="V081_charityFeature(${id})">Donate ${money(V081_charityAmount(a))} & confirm feature</button></section>`};

function V081_allFeatureArtists(){return [...s.world.filter(a=>a.directoryKey===undefined),...Array.from({length:2500},(_,i)=>directoryArtist(i))]}
featurePicker=function(){if(!labelActive())return;migrateV081();const all=V081_allFeatureArtists(),filtered=all.filter(a=>(V081_featureGenre==='All'||a.genre===V081_featureGenre)&&(!directoryQuery||a.name.toLowerCase().includes(directoryQuery.toLowerCase()))).filter(a=>V081_featureAccessFilter==='Available'?accessible(a)&&a.relation>-40:!accessible(a)||a.relation<=-40),pages=Math.max(1,Math.ceil(filtered.length/20));V081_featurePage=Math.min(V081_featurePage,pages-1);modal(`<span class="eyebrow">COLLABORATION DIRECTORY / 2,500+ ARTISTS</span><h2>Find a guest · ${guestList(s.draft).length}/6 booked</h2><div class="chips"><button class="${V081_featureAccessFilter==='Available'?'selected':''}" onclick="V081_featureAccessFilter='Available';V081_featurePage=0;featurePicker()">Available</button><button class="${V081_featureAccessFilter==='Locked'?'selected':''}" onclick="V081_featureAccessFilter='Locked';V081_featurePage=0;featurePicker()">Locked</button></div><p>${V081_featureAccessFilter==='Available'?'These artists currently meet your career, reputation and relationship requirements.':'These artists show exactly what you still need to unlock the collaboration.'}</p><form onsubmit="event.preventDefault();directoryQuery=new FormData(this).get('search');V081_featurePage=0;featurePicker()"><label>Search artists<input name="search" value="${esc(directoryQuery)}" placeholder="Artist name"></label><button class="secondary">Search</button></form><label>Genre<select onchange="V081_featureGenre=this.value;V081_featurePage=0;featurePicker()">${['All',...genres].map(g=>`<option ${g===V081_featureGenre?'selected':''}>${g}</option>`).join('')}</select></label>${filtered.slice(V081_featurePage*20,V081_featurePage*20+20).map(a=>`<div class="project-row">${personPhoto('artist-'+(a.directoryKey??a.id),a.name)}<div><strong>${esc(a.name)}</strong><small>${esc(a.genre)} · ${tierNames[tier(a.fans)]} · ${compact(a.fans)} fans</small><small>${accessible(a)?'Feature '+money(quote(a)):'Locked'}${freeEligible(a)?' · courtesy/charity option':''}</small>${!accessible(a)?featureRequirements(a):''}</div><button class="secondary" onclick="${a.directoryKey===undefined?(s.draft?'studioGuest('+a.id+')':'profile('+a.id+')'):'directoryGuest('+a.directoryKey+')'}">${accessible(a)?'Meet':'View requirements'}</button></div>`).join('')||'<p>No artists match this filter.</p>'}<div class="controls"><button class="secondary" ${V081_featurePage===0?'disabled':''} onclick="V081_featurePage--;featurePicker()">Previous</button><span>${V081_featurePage+1}/${pages}</span><button class="secondary" ${V081_featurePage>=pages-1?'disabled':''} onclick="V081_featurePage++;featurePicker()">Next</button></div>`)};

function V081_thread(id){migrateV081();const key=String(id);if(!s.v081.messages.threads[key])s.v081.messages.threads[key]={artist:id,messages:[]};return s.v081.messages.threads[key]}
function V081_openDM(id){const a=s.world[id];if(!a)return;const t=V081_thread(id);modal(`${personPhoto('artist-'+(a.directoryKey??a.id),a.name,true)}<span class="eyebrow">DIRECT MESSAGES</span><h2>${esc(a.name)}</h2><div class="dm-thread">${t.messages.map(m=>`<div class="dm ${m.from==='you'?'you':'them'}"><small>${m.from==='you'?'YOU':esc(a.name)} · ${m.month}</small><p>${esc(m.text)}</p></div>`).join('')||'<p class="fine">No messages yet. Start a conversation.</p>'}</div><form class="form" onsubmit="V081_sendDM(event,${id})"><label>Intent<select name="intent"><option value="talk">Check in</option><option value="collab">Ask about a collaboration</option><option value="song">Ask about songs / writing</option><option value="business">Talk business</option></select></label><label>Message<input name="text" maxlength="220" placeholder="Type your message…" required></label><button class="primary">Send message</button></form>`)}
function V081_sendDM(e,id){e.preventDefault();const a=s.world[id],t=a&&V081_thread(id);if(!a||!t)return;const f=new FormData(e.target),intent=String(f.get('intent')||'talk'),text=String(f.get('text')||'').trim().slice(0,220);if(!text)return;t.messages.push({id:s.v081.messages.nextId++,from:'you',month:s.empire.month+1,text,intent});let reply,rel=a.relation||0;if(intent==='collab')reply=accessible(a)?(rel>=60?'I’m with it. Send me the record and let’s figure out the details.':'I’m open. Let’s talk song and timing.'):'I’m not there yet. Build the relationship and career leverage first.';else if(intent==='song')reply=rel>=50?'I’ve got a couple ideas that might fit you. I’ll send something if one feels right.':'I’m listening. Keep building and circle back.';else if(intent==='business')reply=rel>=30?'Send the terms. I’ll look at it with my team.':'I’d rather build more trust before we get into money.';else reply=rel>=60?'Always good hearing from you. Keep me posted on what you’re building.':'Good hearing from you. Hope the next release goes crazy.';t.messages.push({id:s.v081.messages.nextId++,from:'them',month:s.empire.month+1,text:reply,intent});if(intent==='talk')a.relation=clamp(a.relation+1,-100,100);if(intent==='collab'&&accessible(a)&&Math.random()<.25+.003*Math.max(0,rel))V081_addCreativeOffer('featureInvite',a);t.messages=t.messages.slice(-60);render();V081_openDM(id)}

const V081_profile080=profile;
profile=function(id){V081_profile080(id);const a=s.world[id],el=$('modal');if(!a||!el?.open)return;const p=V081_artistProject(a),worth=V081_artistNetWorth(a);el.innerHTML+=`<section class="card"><h3>Career intelligence</h3>${profileRows([['Estimated net worth',money(worth)],['Current project',p.type],['Project stage',p.stage],['Projected release',p.release],['Investments',V081_artistInvestments(a).join(', ')]])}<p class="fine">Other artists’ wealth is a simulated estimate, not an exact accounting ledger.</p><button class="secondary" onclick="V081_openDM(${id})">Message ${esc(a.name)}</button></section>`};

function V081_offerFee(type,a){const scale=Math.max(250,Math.round((a.fans||1000)*.004+(a.reputation||20)*60));return Math.round(scale*(type==='ghostwrite'?1:type==='produce'?1.2:.7))}
function V081_addCreativeOffer(type,a){migrateV081();const quality=clamp(Math.round((a.skill||50)*.7+(a.reputation||40)*.3+rand(-8,8))),fee=V081_offerFee(type,a);s.v081.creative.offers.push({id:s.v081.creative.nextId++,type,artist:a.id,name:a.name,quality,fee,status:'open',createdMonth:s.empire.month,reviewedMonth:null});s.v081.creative.offers=s.v081.creative.offers.slice(-30)}
function V081_generateCreativeOffers(){migrateV081();if(s.v081.creative.lastGeneratedMonth===s.empire.month)return;s.v081.creative.lastGeneratedMonth=s.empire.month;const pool=s.world.slice().sort((a,b)=>(b.relation||0)-(a.relation||0)).slice(0,Math.min(20,s.world.length));const count=2+((s.empire.month+s.week)%3);for(let i=0;i<count;i++){const a=pool[(s.empire.month*3+i*5)%Math.max(1,pool.length)]||s.world[i%s.world.length];if(!a)continue;const type=['ghostwrite','produce','songOffer','featureInvite'][(s.empire.month+i+a.id)%4];V081_addCreativeOffer(type,a)} }
function V081_generateSongMarket(){migrateV081();if(s.v081.creative.songMarketMonth===s.empire.month)return;s.v081.creative.songMarketMonth=s.empire.month;s.v081.creative.songMarket=Array.from({length:12},(_,i)=>{const quality=clamp(Math.round(38+((s.empire.month*13+i*17)%55)+rand(-5,5))),commercial=clamp(Math.round(quality*.72+rand(0,22))),price=Math.max(250,Math.round((quality**2)*18*(.7+commercial/100)));return {id:s.v081.creative.songNextId++,title:generate('song'),writer:generate('artist'),quality,commercial,price,genre:genres[(s.empire.month+i*3)%genres.length]}})}
function V081_acceptCreative(id){migrateV081();const o=s.v081.creative.offers.find(x=>x.id===id&&x.status==='open'),a=o&&s.world[o.artist];if(!o||!a)return;if(o.type==='ghostwrite'||o.type==='produce'){if(!spend(10))return;changeCash(o.fee);recordIncome('wages',o.fee);gainXP(o.type==='ghostwrite'?'writing':'producing',45);a.relation=clamp(a.relation+3,-100,100);moneyEvent((o.type==='ghostwrite'?'Ghostwriting':'Production')+' fee · '+a.name,o.fee);o.status='accepted';toast('Session completed. You were paid '+money(o.fee)+'.')}else if(o.type==='songOffer'){const gifted=a.relation>=80,cost=gifted?0:Math.round(o.fee*.75);if(!spend(5,cost))return;const song={id:Date.now()+Math.random(),title:generate('song'),mood:directions[0].id,steps:3,quality:o.quality,commercial:clamp(o.quality+rand(-5,12)),feature:null,features:[],development:JSON.parse(JSON.stringify(s.development)),songRules:2,genre:s.genre,productionBudget:0,productionBonus:0,variation:0,appeal:0,released:null,streams:0,total:0,peak:null,album:null,source:'Artist song offer · '+a.name};s.songs.push(song);o.status='accepted';a.relation=clamp(a.relation+4,-100,100);toast(gifted?'They gave you the song. It is in Finished recordings.':'Song acquired and added to Finished recordings.')}else if(o.type==='featureInvite'){a.relation=clamp(a.relation+5,-100,100);o.status='accepted';V081_openDM(a.id);return}render()}
function V081_buyMarketSong(id){migrateV081();const x=s.v081.creative.songMarket.find(x=>x.id===id);if(!x)return;if(s.cash<x.price){toast('Not enough cash to acquire this song.');return}if(!spend(5))return;changeCash(-x.price);s.songs.push({id:Date.now()+Math.random(),title:x.title,mood:directions[0].id,steps:3,quality:x.quality,commercial:x.commercial,feature:null,features:[],development:JSON.parse(JSON.stringify(s.development)),songRules:2,genre:s.genre,productionBudget:0,productionBonus:0,variation:0,appeal:0,released:null,streams:0,total:0,peak:null,album:null,source:'Song marketplace · '+x.writer});moneyEvent('Purchased song · '+x.title,-x.price);s.v081.creative.songMarket=s.v081.creative.songMarket.filter(y=>y.id!==id);render();toast('Song purchased. It is ready for a single or album.')}
function V081_declineCreative(id){const o=s.v081.creative.offers.find(x=>x.id===id&&x.status==='open');if(o)o.status='declined';render()}
function V081_creativePage(){migrateV081();V081_generateCreativeOffers();V081_generateSongMarket();const tabs=['Opportunities','Song market','Messages'];return head('Write, produce and connect beyond your own releases','Creative network.',`<span class="pill">${s.v081.creative.offers.filter(o=>o.status==='open').length} open</span>`)+`<div class="chips">${tabs.map(t=>`<button class="${V081_creativeTab===t?'selected':''}" onclick="V081_creativeTab='${t}';render()">${t}</button>`).join('')}</div>${V081_creativeTab==='Opportunities'?`<div class="card-stack">${s.v081.creative.offers.filter(o=>o.status==='open').map(o=>{const type={ghostwrite:'Ghostwriting request',produce:'Production request',songOffer:'Song offered to you',featureInvite:'Collaboration message'}[o.type];return `<section class="card"><span class="eyebrow">${type}</span><h2>${esc(o.name)}</h2><p>${o.type==='ghostwrite'||o.type==='produce'?'Fee '+money(o.fee)+' · ':''}Estimated creative quality ${o.quality}/100.</p><button class="primary" onclick="V081_acceptCreative(${o.id})">${o.type==='songOffer'?'Review / accept song':o.type==='featureInvite'?'Open conversation':'Accept session'}</button><button class="secondary" onclick="V081_declineCreative(${o.id})">Decline</button></section>`}).join('')||'<section class="card"><p>No open creative opportunities this month.</p></section>'}</div>`:V081_creativeTab==='Song market'?`<section class="card"><h2>Written-song marketplace</h2><p>Buy finished compositions with visible quality and commercial-potential scores. Purchased songs arrive as finished recordings so albums do not require you to personally write every track.</p></section><div class="catalog-market-grid">${s.v081.creative.songMarket.map(x=>`<section class="card"><span class="eyebrow">${esc(x.genre)} · SONG FOR SALE</span><h2>${esc(x.title)}</h2><p>Written by ${esc(x.writer)}</p>${profileRows([['Quality',x.quality+'/100'],['Commercial potential',x.commercial+'/100'],['Price',money(x.price)]])}<button class="primary" onclick="V081_buyMarketSong(${x.id})">Buy song</button></section>`).join('')}</div>`:`<section class="card"><h2>Artist messages</h2>${Object.values(s.v081.messages.threads).filter(t=>t.messages.length).map(t=>{const a=s.world[t.artist],last=t.messages.at(-1);return `<button class="message-thread" onclick="V081_openDM(${a.id})">${personPhoto('artist-'+(a.directoryKey??a.id),a.name)}<span><strong>${esc(a.name)}</strong><small>${esc(last.text)}</small></span></button>`}).join('')||'<p>Message an artist from their profile or your label roster to start a thread.</p>'}</section>`}`}

const V081_rolloutDurations=[8,12,16];
function V081_rolloutMultiplier(){const r=s.expansion?.albumRollout;if(!r||r.until<s.week)return 1;const total=Math.max(1,(r.duration||4));return 1+Math.min(.5,.04*total+(r.budget||0)/1000000*.03)}
function V081_longRolloutCard(){const r=s.expansion?.albumRollout;return `<section class="card"><span class="eyebrow">ALBUM ROLLOUT</span><h2>Build a longer era</h2><p>Choose an 8, 12 or 16-week rollout. Longer campaigns cost more but build more sustained attention and make room for multiple singles, press moments and tour announcements.</p>${r&&r.until>=s.week?profileRows([['Active rollout',(r.duration||4)+' weeks'],['Ends after week',r.until],['Budget',money(r.budget||0)],['Current reach multiplier',V081_rolloutMultiplier().toFixed(2)+'×']]):`<div class="controls">${V081_rolloutDurations.map(w=>`<button class="secondary" onclick="V081_startRollout(${w})">${w} weeks · ${money(w*7500)}</button>`).join('')}</div>`}</section>`}
function V081_startRollout(weeks){if(!V081_rolloutDurations.includes(weeks))return;const cost=weeks*7500;if(!s.songs.some(x=>!x.album)){toast('Finish at least one song first.');return}if(s.cash<cost){toast('Not enough cash for that rollout.');return}if(!spend(15))return;changeCash(-cost);s.finance.week.expenses=cents(s.finance.week.expenses+cost);s.expansion.albumRollout={started:s.week,until:s.week+weeks-1,duration:weeks,budget:cost,boost:Math.min(.4,weeks*.025),lead:s.songs.filter(x=>!x.album)[0]?.id||null};moneyEvent(weeks+'-week album rollout',-cost);render()}
const V081_marketingPage080=marketingPage;
marketingPage=function(){return V081_marketingPage080()+V081_longRolloutCard()};

function V081_agentRate(){const a=s.expansion?.agent;return a?.commission||a?.rate||0}
function V081_tourTakeHome(v,shows,price){const tickets=tourDemand(v,price,shows),gross=tickets*price,production=v.setup+shows*v.fixed+gross*.35,agent=gross*V081_agentRate(),label=s.expansion.contract?.type==='360'?gross*(s.expansion.contract.share||0):0,overhead=Math.max(0,gross-production-agent-label)*operationRate(),taxBase=Math.max(0,gross-production-agent-label-overhead),tax=.18*taxBase;return {tickets,gross,production,agent,label,overhead,tax,net:gross-production-agent-label-overhead-tax}}

function V081_makeSportsTeams(){const cities=['Austin','Chicago','New York','Los Angeles','Miami','Seattle','Atlanta','Dallas'],names=['Comets','Kings','Empire','Waves','Flames','Sound','Flight','Stampede'];return cities.map((city,i)=>({id:i,name:city+' '+names[i],sport:['Basketball','Football','Baseball','Soccer'][i%4],value:[2200000000,4100000000,6200000000,5400000000,2800000000,1900000000,2400000000,3600000000][i],rating:58+(i*7)%35,wins:0,losses:0,season:1,games:0,history:[]}))}
function V081_sportsForecast(t){const strength=(t.rating-50)/100,mid=.035+strength*.09,vol=.08+(100-t.rating)/100*.08;return {low:mid-vol,high:mid+vol,mid}}
function V081_sportsHolding(team){return s.v081.sports.holdings.filter(h=>h.team===team.id).reduce((n,h)=>n+h.share,0)}
function V081_buySports(id,share=.01,confirmed=false){migrateV081();const t=s.v081.sports.teams.find(x=>x.id===id);if(!t||![.001,.005,.01,.05].includes(share)||V081_sportsHolding(t)+share>.1)return;const price=cents(t.value*share*1.01);if(!confirmed){const f=V081_sportsForecast(t);modal(`<h2>Buy ${(share*100).toFixed(1)}% of ${esc(t.name)}?</h2>${profileRows([['Franchise value',money(t.value)],['Stake price + 1% spread',money(price)],['Annual value range',V081_pct(f.low)+' to '+V081_pct(f.high)],['Current rating',t.rating+'/100'],['Season record',t.wins+'–'+t.losses]])}<p>Team value reacts to season performance and long-term franchise growth. There is no guaranteed appreciation.</p><button class="primary" onclick="V081_buySports(${id},${share},true)">Confirm purchase</button>`);return}if(s.cash<price){toast('Not enough cash for this ownership stake.');return}changeCash(-price);s.v081.sports.holdings.push({id:s.v081.sports.nextId++,team:id,share,basis:price,boughtMonth:s.empire.month,payouts:0,history:[{month:s.empire.month,value:t.value*share}]});moneyEvent('Sports ownership · '+t.name,-price);$('modal').close();render()}
function V081_settleSports(){migrateV081();if(s.v081.sports.lastSettledMonth===s.empire.month)return 0;s.v081.sports.lastSettledMonth=s.empire.month;let payouts=0;for(const t of s.v081.sports.teams){const gamesThisMonth=t.sport==='Baseball'?22:t.sport==='Basketball'?10:t.sport==='Football'?4:6;for(let i=0;i<gamesThisMonth;i++){const win=Math.random()<clamp(.25+t.rating/200,.28,.78);if(win)t.wins++;else t.losses++;t.games++}const seasonGames={Baseball:162,Basketball:82,Football:17,Soccer:34}[t.sport];const pct=t.games? t.wins/t.games:.5,performance=(pct-.5)*.08,move=.004+performance+rand(-.025,.025);t.value=cents(Math.max(100000000,t.value*(1+move)));t.history.push({month:s.empire.month,value:t.value});t.history=t.history.slice(-36);if(t.games>=seasonGames){t.season++;t.rating=clamp(Math.round(t.rating+(pct-.5)*12+rand(-4,4)),35,98);t.wins=0;t.losses=0;t.games=0}}for(const h of s.v081.sports.holdings){const t=s.v081.sports.teams.find(x=>x.id===h.team);if(!t)continue;const distribution=cents(t.value*h.share*.00035);if(distribution>0){changeCash(distribution);recordIncome('investment',distribution);h.payouts+=distribution;payouts+=distribution}h.history.push({month:s.empire.month,value:t.value*h.share});h.history=h.history.slice(-36)}return payouts}
function V081_sellSports(id,confirmed=false){const h=s.v081.sports.holdings.find(x=>x.id===id);if(!h)return;const t=s.v081.sports.teams.find(x=>x.id===h.team),gross=cents(t.value*h.share),proceeds=cents(gross*.99),gain=cents(proceeds-h.basis);if(!confirmed){modal(`<h2>Sell ${(h.share*100).toFixed(1)}% of ${esc(t.name)}?</h2>${profileRows([['Current stake value',money(gross)],['Sale proceeds',money(proceeds)],['Basis',money(h.basis)],['Realized gain / loss',money(gain)],['Distributions received',money(h.payouts||0)]])}<button class="primary" onclick="V081_sellSports(${id},true)">Confirm sale</button>`);return}changeCash(proceeds);s.finance.week.investment=cents((s.finance.week.investment||0)+gain);s.v081.sports.holdings=s.v081.sports.holdings.filter(x=>x.id!==id);$('modal').close();render()}
function V081_sportsPage(){migrateV081();const tabs=['Market','My stakes'];return head('Own a piece of the competition','Sports ownership.',`<span class="pill">${s.v081.sports.holdings.length} stakes</span>`)+`<p>Fictional teams automatically play complete seasons. Franchise values respond to performance, team rating and market variance.</p><div class="chips">${tabs.map(t=>`<button class="${V081_sportsTab===t?'selected':''}" onclick="V081_sportsTab='${t}';render()">${t}</button>`).join('')}</div>${V081_sportsTab==='Market'?`<div class="catalog-market-grid">${s.v081.sports.teams.map(t=>{const f=V081_sportsForecast(t);return `<section class="card"><span class="eyebrow">${t.sport} · SEASON ${t.season}</span><h2>${esc(t.name)}</h2>${profileRows([['Franchise value',money(t.value)],['Record',t.wins+'–'+t.losses],['Team rating',t.rating+'/100'],['Annual value range',V081_pct(f.low)+' to '+V081_pct(f.high)]])}${V081_spark(t.history.map(x=>x.value),t.name+' franchise value trend')}<div class="controls">${[.001,.005,.01].map(sh=>`<button class="secondary" onclick="V081_buySports(${t.id},${sh})">Buy ${(sh*100).toFixed(1)}%</button>`).join('')}</div></section>`}).join('')}</div>`:`<div class="catalog-market-grid">${s.v081.sports.holdings.map(h=>{const t=s.v081.sports.teams.find(x=>x.id===h.team),value=t.value*h.share,gain=value-h.basis;return `<section class="card"><h2>${esc(t.name)}</h2>${profileRows([['Ownership',(h.share*100).toFixed(1)+'%'],['Current value',money(value)],['Cost basis',money(h.basis)],['Unrealized gain / loss',money(gain)],['Distributions',money(h.payouts||0)]])}${V081_spark(h.history.map(x=>x.value),'Sports stake value trend')}<button class="secondary" onclick="V081_sellSports(${h.id})">Review sale</button></section>`}).join('')||'<section class="card"><p>No sports ownership stakes yet.</p></section>'}</div>`}`}

function V081_snapshotAssetHistory(){for(const a of s.empire.assets||[]){a.history??=[];a.history.push({month:s.empire.month,value:a.value});a.history=a.history.slice(-36)}V081_marketMonthlySnapshot()}
function V081_settleLabelInfrastructure(){const co=s.labelBusiness?.company;if(!co)return 0;let extra=0;for(const c of ownerContracts()){if(c.type!=='360')continue;const a=s.world[c.artist],tour=cents(a.fans*.002*V081_upgradeLevel('touring')*c.share),merch=cents(a.fans*.0015*V081_upgradeLevel('merch')*c.share);extra+=tour+merch;c.receipts=cents(c.receipts+tour+merch)}if(extra){changeCash(extra);recordIncome('labelBusiness',extra);co.receipts=cents(co.receipts+extra);moneyEvent('Label touring & merch infrastructure',extra)}return extra}
function V081_settleMonth(report){migrateV081();if(s.v081.lastSettledMonth===s.empire.month)return s.v081.lastReport||{};V081_settleRosterDevelopment();V081_snapshotAssetHistory();const sports=V081_settleSports(),label=V081_settleLabelInfrastructure();V081_generateCreativeOffers();V081_generateSongMarket();s.v081.lastSettledMonth=s.empire.month;s.v081.lastReport={sports,label};return s.v081.lastReport}

const V081_monthlyRecap080=monthlyRecap;
monthlyRecap=function(report){migrateV081();const depth=V081_settleMonth(report);V081_monthlyRecap080(report);const el=$('modal'),f=report.finance||s.finance.last||{},assetValue=(s.empire.assets||[]).reduce((n,a)=>n+a.value,0),catalogHoldings=(s.v080?.catalog?.holdings||[]).reduce((n,h)=>n+(h.lastValue||0),0),sportsValue=(s.v081.sports.holdings||[]).reduce((n,h)=>{const t=s.v081.sports.teams.find(x=>x.id===h.team);return n+(t?t.value*h.share:0)},0);if(el?.open){el.innerHTML=el.innerHTML.replace('</article>',`<section class="recap-financial"><span class="eyebrow">FINANCIAL BREAKDOWN</span><h3>Where the money moved</h3>${profileRows([['Royalties',money(report.royalties||0)],['Live income',money(f.live||0)],['Media / commercial',money(f.media||0)],['Label-business income',money((f.labelBusiness||0)+(depth.label||0))],['Investment income',money((f.investment||0)+(depth.sports||0))],['Career expenses',money(f.expenses||0)],['Tax reserve',money(report.taxes||0)],['Net cash movement',money(report.cashChange||0)],['Spendable cash',money(s.cash)],['Physical / market assets',money(assetValue)],['Outside catalogs',money(catalogHoldings)],['Sports stakes',money(sportsValue)]])}<p class="fine">Cash movement comes from the real simulation ledger. Asset, catalog and sports values are unrealized until sold.</p></section></article>`)} };

const V081_career080=career;
career=function(){migrateV081();if(careerTab==='Creative')return careerMenu()+V081_creativePage();if(careerTab==='Sports')return careerMenu()+V081_sportsPage();return V081_career080()};
const V081_screenFamily080=screenFamily;
screenFamily=function(){if(tab==='Career'&&careerTab==='Creative')return 'business';if(tab==='Career'&&careerTab==='Sports')return 'exchange';return V081_screenFamily080()};

const V081_render080=render;
render=function(){if(saveReady&&!monthlyAdvancing)migrateV081();return V081_render080()};

const V081_validatePresentation080=validatePresentationState;
validatePresentationState=function(){V081_validatePresentation080();if(!s.v081)return;const v=s.v081;if(v.version!==V081_SCHEMA||!v.label||!v.creative||!v.messages||!v.sports)throw Error('Invalid 0.8.1 state');for(const k of V081_UPGRADE_KEYS)if(!Number.isInteger(v.label.upgrades[k])||v.label.upgrades[k]<0||v.label.upgrades[k]>5)throw Error('Invalid label upgrade');if(!Array.isArray(v.creative.offers)||!Array.isArray(v.creative.songMarket)||!Array.isArray(v.sports.holdings)||!Array.isArray(v.sports.teams))throw Error('Invalid 0.8.1 records');for(const h of v.sports.holdings)if(!Number.isInteger(h.id)||!Number.isInteger(h.team)||!Number.isFinite(h.share)||h.share<=0||h.share>.1||!Number.isFinite(h.basis)||h.basis<0)throw Error('Invalid sports holding')};
