/* ENCORE 0.8.2 polish pass: faster studio flow, smarter home hierarchy,
   living NPC career arcs and premium presentation hooks. */

const V082_SCHEMA=1;
const V082_ACTIVE_NPCS=24;
const V082_ERA_WORDS=['Neon','Midnight','Golden','Afterglow','Pressure','Velvet','Satellite','Static','Blue Hour','New Dawn','Noir','Wildfire'];
const V082_ERA_NOUNS=['Era','Chapter','Season','Run','Phase','Wave','Cycle','Story'];

function V082_derivedNpcState(a){const n=(a.id*29+Math.round(a.fans||0)+Math.round(a.reputation||0)*7)%101,m=n-50;return {momentum:m,phase:m>42?'Prime':m>18?'Ascending':m<-35?'Quiet era':m<-10?'Rebuild':'Steady',era:V082_ERA_WORDS[(a.id*3)%V082_ERA_WORDS.length]+' '+V082_ERA_NOUNS[(a.id*5)%V082_ERA_NOUNS.length],lastEvent:'Career moving on its own schedule.',lastEventMonth:-1,hiatusUntil:-1,careerPeak:a.fans||0};}
function migrateV082(){
  migrateV081?.();
  if(!s.v082)s.v082={version:V082_SCHEMA,npc:{},headlines:[],lastSettledMonth:-1};
  s.v082.version=V082_SCHEMA;s.v082.npc??={};s.v082.headlines??=[];s.v082.lastSettledMonth??=-1;
  if(s.draft?.sessionPlan?.brief&&s.draft.steps===1){s.draft.sessionPlan={q:0,a:0};scoreSong(s.draft)}
  V082_patchGuidance();
}
function V082_npcState(a,persist=true){if(!a)return null;const canPersist=persist&&a.directoryKey===undefined&&a.id<V082_ACTIVE_NPCS,key=String(a.id);if(!canPersist)return V082_derivedNpcState(a);if(!s.v082.npc[key])s.v082.npc[key]=V082_derivedNpcState(a);const st=s.v082.npc[key];st.careerPeak=Math.max(st.careerPeak||0,a.fans||0);return st}
function V082_patchGuidance(){
  if(typeof V080_GUIDE_TOPICS!=='undefined'){const t=V080_GUIDE_TOPICS.find(x=>x[0]==='Make a song');if(t)t[2]='Choose a title, creative direction and production budget, then write, record and mix in stages. Recording and mixing decisions shape the finished record; unfinished projects remain in your studio.'}
  if(typeof V080_GAMEPLAY_TOUR!=='undefined'){const t=V080_GAMEPLAY_TOUR.find(x=>x.page==='Create'&&x.title==='Build the record');if(t)t.text='Choose a title, direction and production budget, then write, record and mix one persistent project. Recording and mixing choices shape the finished song.'}
}

/* Creative Brief removed: new projects start neutral and receive quality/appeal tradeoffs in recording/mixing. */
newSong=function(e){e.preventDefault();if(s.draft)return;const f=new FormData(e.target),production=studioPackages[Number(f.get('package'))]||studioPackages[0],mood=f.get('mood')||directions[0].id;if(!spend(10,production.fee))return;s.studioIdea={title:'',mood,package:String(f.get('package')||'0')};s.started=true;s.draft={id:Date.now()+Math.random(),title:String(f.get('songtitle')||'').trim()||generate('song'),mood,steps:1,quality:0,feature:null,development:JSON.parse(JSON.stringify(s.development)),songRules:2,genre:s.genre,productionBudget:production.fee,productionBonus:production.quality,variation:rand(-8,8),appeal:rand(-12,12),sessionPlan:{q:0,a:0}};scoreSong(s.draft);log('Started writing “'+s.draft.title+'”.');render()};

function V082_phaseFor(st){if(st.hiatusUntil>s.empire.month)return 'Hiatus';if(st.momentum>=55)return 'Prime';if(st.momentum>=20)return 'Ascending';if(st.momentum<=-45)return 'Quiet era';if(st.momentum<=-15)return 'Rebuild';if(st.lastEvent&&/comeback/i.test(st.lastEvent))return 'Comeback';return 'Steady'}
function V082_newEra(a,st){const i=(a.id+s.empire.month*3+Math.round(st.momentum))%V082_ERA_WORDS.length,j=(a.id*2+s.empire.month)%V082_ERA_NOUNS.length;st.era=V082_ERA_WORDS[Math.abs(i)]+' '+V082_ERA_NOUNS[Math.abs(j)]}
function V082_pushHeadline(a,title,body,tone='news'){const h={id:'npc-'+a.id+'-'+s.empire.month+'-'+Math.random(),month:s.empire.month,week:s.week,artist:a.id,title,body,tone};s.v082.headlines.unshift(h);s.v082.headlines=s.v082.headlines.slice(0,60);if(s.labelLeague?.news){s.labelLeague.news.unshift(a.name+': '+title+'.');s.labelLeague.news=s.labelLeague.news.slice(0,30)}}
function V082_npcEvent(a,st){
  const r=Math.random();
  if(st.momentum<-35&&r<.42){st.momentum=clamp(st.momentum-rand(4,12),-100,100);st.lastEvent='A difficult stretch slowed the career.';st.lastEventMonth=s.empire.month;a.nextRelease=Math.max(a.nextRelease||s.week+4,s.week+6+Math.floor(rand(0,5)));a.fans=Math.max(0,Math.round(a.fans*rand(.965,.99)));V082_pushHeadline(a,'Momentum cools','A quieter stretch has pushed the next release farther out.','down');return}
  if(st.momentum>42&&r<.48){const gain=Math.round(a.fans*rand(.02,.075)/(1+a.fans/250000000));a.fans+=gain;a.reputation=clamp(a.reputation+rand(.2,1.2));st.momentum=clamp(st.momentum+rand(5,14),-100,100);st.lastEvent='A breakout run is expanding the audience.';st.lastEventMonth=s.empire.month;a.nextRelease=Math.min(a.nextRelease||s.week+5,s.week+2+Math.floor(rand(0,4)));V082_pushHeadline(a,'A bigger era is taking shape','Momentum, audience growth and a faster release schedule are lining up.','up');return}
  if(r<.16){st.hiatusUntil=s.empire.month+2+Math.floor(rand(0,4));st.lastEvent='A short hiatus was announced.';st.lastEventMonth=s.empire.month;a.nextRelease=Math.max(a.nextRelease||s.week+4,s.week+8+Math.floor(rand(0,10)));V082_pushHeadline(a,'Steps away for a while','The release calendar is paused while the artist resets.','quiet');return}
  if(r<.42){V082_newEra(a,st);st.momentum=clamp(st.momentum+rand(-4,8),-100,100);st.lastEvent='A reinvention is underway: '+st.era+'.';st.lastEventMonth=s.empire.month;a.nextRelease=Math.min(a.nextRelease||s.week+6,s.week+4+Math.floor(rand(0,6)));V082_pushHeadline(a,'Reinvention season','A new visual and creative chapter is forming around '+st.era+'.','news');return}
  if(r<.68){st.momentum=clamp(st.momentum+rand(3,10),-100,100);st.lastEvent='A high-profile collaboration is adding momentum.';st.lastEventMonth=s.empire.month;V082_pushHeadline(a,'Collaboration buzz','A guest appearance is pulling new listeners into the catalog.','up');return}
  st.lastEvent='The current era is holding steady.';st.lastEventMonth=s.empire.month;
}
function V082_settleNpcLife(){migrateV082();if(s.v082.lastSettledMonth===s.empire.month)return;s.v082.lastSettledMonth=s.empire.month;for(const a of s.world.slice(0,V082_ACTIVE_NPCS)){const st=V082_npcState(a,true);if(st.hiatusUntil===s.empire.month){st.hiatusUntil=-1;st.momentum=clamp(st.momentum+rand(15,28),-100,100);st.lastEvent='A comeback is officially underway.';st.lastEventMonth=s.empire.month;a.nextRelease=Math.min(a.nextRelease||s.week+6,s.week+2+Math.floor(rand(0,4)));V082_newEra(a,st);V082_pushHeadline(a,'Comeback activated','The hiatus is over and a new release window is opening.','up')}
    const latest=a.catalog?.at(-1),age=Math.max(0,s.week-(latest?.week??s.week)),releaseSignal=latest?clamp(((latest.factor||1)-1)*55,-30,30):0,activity=age<8?10:age>20?-12:0;st.momentum=clamp(st.momentum*.72+releaseSignal+activity+rand(-12,12),-100,100);st.phase=V082_phaseFor(st);st.careerPeak=Math.max(st.careerPeak||0,a.fans||0);
    const growth=st.phase==='Hiatus'?rand(-.08,.08):st.phase==='Prime'?rand(.08,.42):st.phase==='Ascending'?rand(.06,.35):rand(-.04,.24);a.skill=clamp((a.skill||50)+growth,10,99);a.reputation=clamp((a.reputation||50)+rand(-.18,.28),0,100);
    if(st.phase!=='Hiatus'&&Math.random()<(.055+(Math.abs(st.momentum)>55?.035:0)))V082_npcEvent(a,st);st.phase=V082_phaseFor(st);
  }}
const V082_settleIndustry081=settleIndustryLife;
settleIndustryLife=function(){V082_settleIndustry081();V082_settleNpcLife()};

function V082_momentumLabel(n){return n>=60?'Surging':n>=25?'Rising':n<=-50?'Cold':n<=-20?'Cooling':'Stable'}
function V082_worldPulsePage(){migrateV082();const active=s.world.slice(0,V082_ACTIVE_NPCS).map(a=>({a,st:V082_npcState(a,true)})).sort((x,y)=>y.st.momentum-x.st.momentum),tabs=['Artists','Charts','New releases','World pulse'];return head('Careers move even when you are not watching','World Pulse.')+`<div class="chips">${tabs.map(x=>`<button class="${industryTab===x?'selected':''}" onclick="industryTab='${x}';render()">${x}</button>`).join('')}</div><section class="world-pulse-hero"><span class="eyebrow">LIVING INDUSTRY · ${careerDate()}</span><h2>The scene has its own momentum.</h2><p>Artists can surge, cool off, take a hiatus, reinvent themselves or come back. Their skill, audience and release timing continue moving as months pass.</p></section><div class="pulse-leaders">${active.slice(0,6).map(({a,st})=>`<button class="pulse-artist" onclick="profile(${a.id})">${personPhoto('artist-'+(a.directoryKey??a.id),a.name)}<span><small>${esc(st.phase)} · ${esc(st.era)}</small><strong>${esc(a.name)}</strong><em>${V082_momentumLabel(st.momentum)} · ${st.momentum>=0?'+':''}${Math.round(st.momentum)}</em></span></button>`).join('')}</div><section class="card"><div class="sectionhead"><h2>Industry headlines</h2><span class="pill">${s.v082.headlines.length}</span></div>${s.v082.headlines.length?s.v082.headlines.slice(0,18).map(h=>{const a=s.world[h.artist];return `<button class="world-headline ${esc(h.tone)}" onclick="profile(${h.artist})"><span>${esc(h.title)}</span><strong>${esc(a?.name||'Artist')}</strong><small>${esc(h.body)} · ${V081_releaseDateForWeek(h.week)}</small></button>`}).join(''):'<p>Advance a week and the industry will begin writing its own stories.</p>'}</section>`}
const V082_industry081=industry;
industry=function(){migrateV082();if(industryTab==='World pulse')return V082_worldPulsePage();const html=V082_industry081();return html.replace(/(<div class="chips">[\s\S]*?)(<\/div>)/,`$1<button class="" onclick="industryTab='World pulse';render()">World pulse</button>$2`)};

const V082_profile081=profile;
profile=function(id){migrateV082();V082_profile081(id);const a=s.world[id],el=$('modal');if(!a||!el?.open)return;const st=V082_npcState(a,true),project=typeof V081_artistProject==='function'?V081_artistProject(a):null;el.innerHTML+=`<section class="card npc-pulse-card"><span class="eyebrow">CAREER PULSE · ${esc(st.phase)}</span><div class="sectionhead"><h3>${esc(st.era)}</h3><strong class="momentum-score ${st.momentum<0?'down':''}">${st.momentum>=0?'+':''}${Math.round(st.momentum)}</strong></div>${profileRows([['Momentum',V082_momentumLabel(st.momentum)],['Career peak',compact(st.careerPeak||a.fans)],['Current chapter',st.lastEvent||'Steady career movement'],['Next project',project?project.title:'In development'],['Projected release',project?project.release:V081_releaseDateForWeek(a.nextRelease||s.week+4)]])}<p class="fine">NPC careers update during monthly advances. Momentum can change release timing, audience growth and career direction.</p></section>`};

function V082_attentionItems(){migrateV082();const items=[],label=(s.labelBusiness?.offers||[]).filter(o=>!o.used&&o.expires>=s.week).length,commercial=(s.v080?.commercial?.offers||[]).filter(o=>!o.used&&o.expires>=s.week).length,creative=(s.v081?.creative?.offers||[]).filter(o=>!o.done&&(o.expires??Number.MAX_SAFE_INTEGER)>=s.week).length,unread=typeof V080_unreadCount==='function'?V080_unreadCount():0;if(label+commercial+creative)items.push({k:'Offers',v:(label+commercial+creative)+' open',d:'Review before committing',go:"openDestination('Offers')"});if(unread)items.push({k:'Inbox',v:unread+' unread',d:'Briefings & celebrations',go:"openDestination('Inbox')"});if(s.draft)items.push({k:'Studio',v:s.draft.title,d:['','Recording next','Mixing next','Release ready'][s.draft.steps]||'In progress',go:"go('Create')"});if(s.liveTour&&s.liveTour.completed<s.liveTour.shows)items.push({k:'Tour',v:s.liveTour.completed+' / '+s.liveTour.shows+' shows',d:s.liveTour.paused?'Funding required':'Campaign active',go:"openDestination('Touring')"});if(s.energy<45&&s.restWeek!==s.week)items.push({k:'Energy',v:s.energy+'/200',d:'Recovery available',go:"statDetail('energy')"});return items.slice(0,4)}
function V082_attentionCard(){const items=V082_attentionItems();return `<section class="executive-brief"><div class="executive-title"><div><span class="eyebrow">RIGHT NOW</span><h2>${items.length?'Your career needs a few decisions.':'You’re clear to create.'}</h2></div><span class="live-dot">LIVE</span></div>${items.length?`<div class="executive-grid">${items.map(i=>`<button onclick="${i.go}"><small>${esc(i.k)}</small><strong>${esc(i.v)}</strong><span>${esc(i.d)}</span></button>`).join('')}</div>`:'<p>No urgent offers, unread briefings, active tour blockers or unfinished studio decisions.</p>'}</section>`}
const V082_home081=home;
home=function(){migrateV082();const base=V082_home081();return base.replace('<section class="home-dashboard"',V082_attentionCard()+'<section class="home-dashboard"')};

/* Stronger premium surface treatment without changing mechanics. */
function V082_whatsNew(){modal(`<span class="eyebrow">ENCORE · 0.8.2</span><h2>The world feels more alive.</h2><ul><li>Creative Brief removed from song creation; session choices now carry the creative tradeoffs.</li><li>Home adds a live decision brief for offers, inbox items, studio work, touring and recovery.</li><li>NPC artists gain career phases, momentum, hiatuses, reinventions, collaborations and comebacks.</li><li>World Pulse surfaces industry movement and headlines.</li><li>Artist profiles show their current era, momentum and next projected release.</li><li>High-traffic screens receive a more premium layered visual treatment.</li></ul><button class="primary" onclick="$('modal').close()">Back to ENCORE</button>`)}
const V082_renderTitle081=renderTitle;
renderTitle=function(){V082_renderTitle081();const root=$('title-screen');if(!root||root.hidden)return;const old=[...root.querySelectorAll?.('button')||[]].find(b=>/What's new in 0\.8/i.test(b.textContent));if(old){old.textContent="What's new in 0.8.2";old.onclick=V082_whatsNew}};

V082_patchGuidance();
