/* ENCORE 0.8.3 pacing and consistency pass: weekly advances, real calendar labels,
   a single ten-team basketball league, optional social song links and gender-consistent portraits. */

const V083_SCHEMA=1;
const V083_START_YEAR=2026;
const V083_MONTHS=['January','February','March','April','May','June','July','August','September','October','November','December'];
const V083_FEMALE_NAMES=new Set('Amara Asha Azra Cassia Celine Farah Hana Imani Iris Jaya Keira Lana Lena Liora Lumi Lyra Maeve Maren Mira Nia Nova Nyla Sanaa Selah Skye Sora Talia Uma Veda Yara Zara Zuri'.split(' '));
const V083_MALE_NAMES=new Set('Arlo Atlas Bowie Cairo Dario Elio Ezra Felix Idris Jalen Kai Kairo Kofi Leif Leon Luca Malik Mateo Micah Milan Nico Omar Orion Rio Theo'.split(' '));
const V083_FEMALE_PORTRAITS=[0,3,7];
const V083_MALE_PORTRAITS=[2,4,6];
const V083_NEUTRAL_PORTRAITS=[1,5];
const V083_CAST={'agent-maya':0,'agent-dev':4,'agent-celeste':7,'agent-roman':6,'agent-june':3,'agent-nico':2};
const V083_BASKETBALL_TEAMS=[
 {id:0,name:'Austin Outlaws',sport:'Basketball',value:1850000000,rating:64,titles:0,playoffRate:.28,legacy:'Young franchise · growing market · still chasing its first title'},
 {id:1,name:'Chicago Forge',sport:'Basketball',value:5900000000,rating:84,titles:5,playoffRate:.72,legacy:'Historic contender · five championships · strong national following'},
 {id:2,name:'New York Empire',sport:'Basketball',value:8200000000,rating:79,titles:3,playoffRate:.64,legacy:'Premium-market giant · three championships · enormous media value'},
 {id:3,name:'Los Angeles Waves',sport:'Basketball',value:7500000000,rating:91,titles:7,playoffRate:.81,legacy:'Seven-time champion · glamour franchise · perennial contender'},
 {id:4,name:'Miami Tides',sport:'Basketball',value:4200000000,rating:76,titles:2,playoffRate:.59,legacy:'Two championships · destination market · volatile competitive cycles'},
 {id:5,name:'Seattle Sound',sport:'Basketball',value:3000000000,rating:68,titles:1,playoffRate:.42,legacy:'One championship · loyal regional base · rebuilding upward'},
 {id:6,name:'Atlanta Flight',sport:'Basketball',value:2700000000,rating:61,titles:0,playoffRate:.31,legacy:'No championships yet · athletic young core · higher upside and risk'},
 {id:7,name:'Dallas Stampede',sport:'Basketball',value:5100000000,rating:82,titles:2,playoffRate:.67,legacy:'Two championships · consistent playoff history · large business market'},
 {id:8,name:'Las Vegas Neon',sport:'Basketball',value:3600000000,rating:73,titles:0,playoffRate:.38,legacy:'Expansion-era franchise · premium entertainment market · no titles yet'},
 {id:9,name:'Boston Foundry',sport:'Basketball',value:6400000000,rating:87,titles:8,playoffRate:.78,legacy:'League-record eight championships · deep tradition · high expectations'}
];

function V083_monthLabel(index){const i=Math.max(0,Math.floor(Number(index)||0));return V083_MONTHS[i%12]+' '+(V083_START_YEAR+Math.floor(i/12))}
careerDate=function(index=s.empire?.month??calendarMonthAtWeek(s.week)){return V083_monthLabel(index)};
function V083_weekDate(week=s.week){const w=Math.max(1,Math.floor(Number(week)||1));return 'Week '+w+' · '+V083_monthLabel(calendarMonthAtWeek(w))}

function V083_nameGender(name){const first=String(name||'').trim().split(/\s+/)[0].replace(/[^A-Za-z]/g,'');if(V083_FEMALE_NAMES.has(first))return 'female';if(V083_MALE_NAMES.has(first))return 'male';return 'neutral'}
function V083_nameHash(name){return Array.from(String(name||'')).reduce((n,c)=>(n*31+c.charCodeAt(0))>>>0,7)}
personPhoto=function(key,name,large=false){let index=V083_CAST[key];if(index===undefined){const gender=V083_nameGender(name),pool=gender==='female'?V083_FEMALE_PORTRAITS:gender==='male'?V083_MALE_PORTRAITS:V083_NEUTRAL_PORTRAITS;index=pool[V083_nameHash(name)%pool.length]}return `<span class="person-photo ${large?'portrait-large':''}" role="img" aria-label="Illustrated fictional portrait of ${esc(name)}" style="background-image:url('${CAST_ART}');background-position:${index%4*100/3}% ${index<4?0:100}%"></span>`};

function V083_migrateBasketballLeague(){migrateV081?.();const sports=s.v081?.sports;if(!sports)return;const existing=Array.isArray(sports.teams)?sports.teams:[],firstMigration=!s.v083?.sportsMigrated;sports.teams=V083_BASKETBALL_TEAMS.map(def=>{const old=existing.find(x=>x.id===def.id);return {...def,wins:firstMigration?0:(old?.wins||0),losses:firstMigration?0:(old?.losses||0),season:firstMigration?1:(old?.season||1),games:firstMigration?0:(old?.games||0),history:firstMigration?[]:(Array.isArray(old?.history)?old.history:[]),lastSeason:firstMigration?null:(old?.lastSeason||null)}});if(firstMigration)s.v083.sportsMigrated=true;sports.holdings=sports.holdings.filter(h=>sports.teams.some(t=>t.id===h.team));}

function migrateV083(){migrateV082?.();if(!s.v083)s.v083={version:V083_SCHEMA,sportsMigrated:false,monthAccumulator:null};s.v083.version=V083_SCHEMA;s.empire.month=calendarMonthAtWeek(s.week);if(!s.v083.monthAccumulator||s.v083.monthAccumulator.monthIndex!==s.empire.month)s.v083.monthAccumulator={monthIndex:s.empire.month,startWeek:s.week,streams:0,fans:0,royalties:0,taxes:0,cashChange:0};V083_migrateBasketballLeague();V083_patchGuidance()}

function V083_patchGuidance(){if(typeof V080_GUIDE_TOPICS!=='undefined'){const energy=V080_GUIDE_TOPICS.find(x=>x[0]==='Energy and months'||x[0]==='Energy and weeks');if(energy){energy[0]='Energy and weeks';energy[2]='You have 200 energy each week. Advancing resolves one chart week and refills energy. Rent, assets, catalogs, commercial installments, sports and other monthly systems settle when the calendar rolls into a new month.'}const social=V080_GUIDE_TOPICS.find(x=>x[0]==='PULSE');if(social)social[2]='Posts, likes and replies influence engagement, label discovery and commercial leverage. Linking a song is optional for normal posts; only a Release Announcement requires a released song.'}if(typeof V080_GAMEPLAY_TOUR!=='undefined'){const last=V080_GAMEPLAY_TOUR.at(-1);if(last?.page==='Home'){last.title='Advance one week at a time';last.text='Each advance resolves one chart week and refills energy. Monthly business systems settle automatically when the calendar crosses into a new month.'}const chart=V080_GAMEPLAY_TOUR.find(x=>x.page==='Industry'&&x.section==='Charts');if(chart)chart.text='Each weekly advance resolves one chart issue. Debuts, late entries, movement, peaks and longevity reflect the live competition.'}}



const V083_weekRecap082=weekRecap;
weekRecap=function(completed,count,added,debut,financial,earned=[]){const label=V083_weekDate(completed),next=V083_weekDate(completed+1);modal(memoFrame('Weekly recap',label+' · Your career report',`<div class="memo-headline"><span>Streams this week</span><strong>${compact(count)}</strong><small>${added>=0?'+':''}${compact(added)} net fans</small></div><div class="memo-finances">${financeRows(financial).map(([k,v])=>`<div><span>${esc(k)}</span><strong>${esc(v)}</strong></div>`).join('')}</div>${earned.length?`<p class="memo-note">${earned.length} new achievements filed.</p>`:''}${financial.yearEnd?`<p class="memo-note">Tax year settled: ${money(financial.settlement)} paid from your reserve.</p>`:''}<p class="memo-note">Energy restored to 200. ${s.feed.filter(x=>x.week===completed).length} industry projects released.</p>`,`<button class="memo-primary" onclick="$('modal').close()">Continue · ${esc(next)}</button><button class="memo-secondary" onclick="$('modal').close();careerTab='Finances';go('Career')">Full financial report</button>`,completed),'memo-dialog');queueSave()};

const V083_render082=render;
render=function(){if(V083_transitionAdvancing)return V083_render082();const result=V083_render082();if(saveReady){migrateV083();if($('week'))$('week').textContent=V083_weekDate();}return result};

composePulse=function(){if(!labelActive()||s.social.posts.filter(p=>p.week===s.week).length>=3)return;modal(`<h2>Create a PULSE post</h2><p>This is part of your simulated career. Posts do not go to real social platforms.</p><form class="form" onsubmit="publishPulse(event)"><label>Format<select name="format">${pulseFormats.map(f=>`<option value="${f.id}">${f.name} · ${f.energy} energy</option>`).join('')}</select></label><label>Caption<textarea name="caption" maxlength="220" required placeholder="What do you want your audience to hear?"></textarea></label><label>Song link <span class="fine">(optional)</span><select name="song"><option value="">No song link</option>${s.songs.filter(x=>x.released).map(x=>`<option value="${x.id}">${esc(x.title)}</option>`).join('')}</select></label><p class="fine">Normal posts never require a song. Only the Release Announcement format requires you to choose a released track.</p><details><summary>How formats work</summary>${pulseFormats.map(f=>`<p><strong>${f.name}:</strong> ${f.note}</p>`).join('')}</details><p class="fine">Results depend on your skills, format and audience response. Repeating one format this week reduces reach. Linked posts can add up to 20% social reach to that song at week close. Maximum three posts per week.</p><button class="primary">Publish in-game post</button></form>`)};

V081_settleSports=function(){migrateV083();const sports=s.v081.sports;if(sports.lastSettledMonth===s.empire.month)return 0;sports.lastSettledMonth=s.empire.month;let payouts=0;const finished=[];for(const t of sports.teams){const remaining=Math.max(0,82-t.games),gamesThisMonth=Math.min(remaining,(s.empire.month%6===5?6:7));for(let i=0;i<gamesThisMonth;i++){const win=Math.random()<clamp(.24+t.rating/190,.27,.80);if(win)t.wins++;else t.losses++;t.games++}const pct=t.games?t.wins/t.games:.5,performance=(pct-.5)*.035,marketBias=(t.value/8200000000)*.003,move=.002+marketBias+performance+rand(-.012,.012);t.value=cents(Math.max(500000000,t.value*(1+move)));t.history.push({month:s.empire.month,value:t.value});t.history=t.history.slice(-36);if(t.games>=82)finished.push(t)}if(finished.length===sports.teams.length){const champion=finished.slice().sort((a,b)=>(b.wins/82)-(a.wins/82)||b.rating-a.rating)[0];for(const t of finished){const pct=t.wins/82;t.lastSeason={season:t.season,wins:t.wins,losses:t.losses,champion:t.id===champion.id};if(t.id===champion.id){t.titles++;t.value=cents(t.value*1.04)}t.rating=clamp(Math.round(t.rating+(pct-.5)*14+(t.id===champion.id?3:0)+rand(-3,3)),40,98);t.season++;t.wins=0;t.losses=0;t.games=0}}for(const h of sports.holdings){const t=sports.teams.find(x=>x.id===h.team);if(!t)continue;const distribution=cents(t.value*h.share*.00035);if(distribution>0){changeCash(distribution);recordIncome('investment',distribution);h.payouts=cents((h.payouts||0)+distribution);payouts+=distribution}h.history??=[];h.history.push({month:s.empire.month,value:t.value*h.share});h.history=h.history.slice(-36)}return payouts};

V081_sportsPage=function(){migrateV083();const tabs=['Market','My stakes'];return head('Ten teams. One league.','ENCORE Pro Basketball.',`<span class="pill">${s.v081.sports.holdings.length} stakes</span>`)+`<p>All ten fictional franchises compete in the same 82-game basketball league. Their valuations differ because market size, historical success, current team strength and season performance differ.</p><div class="chips">${tabs.map(t=>`<button class="${V081_sportsTab===t?'selected':''}" onclick="V081_sportsTab='${t}';render()">${t}</button>`).join('')}</div>${V081_sportsTab==='Market'?`<div class="catalog-market-grid">${s.v081.sports.teams.map(t=>{const f=V081_sportsForecast(t);return `<section class="card"><span class="eyebrow">BASKETBALL · SEASON ${t.season}</span><h2>${esc(t.name)}</h2>${profileRows([['Franchise value',money(t.value)],['Current record',t.wins+'–'+t.losses+' · '+t.games+'/82 games'],['Team rating',t.rating+'/100'],['Championships',String(t.titles)],['Historic playoff rate',Math.round(t.playoffRate*100)+'%'],['Annual value range',V081_pct(f.low)+' to '+V081_pct(f.high)]])}<p class="fine">${esc(t.legacy)}</p>${t.lastSeason?`<p class="fine">Last season: ${t.lastSeason.wins}–${t.lastSeason.losses}${t.lastSeason.champion?' · LEAGUE CHAMPION':''}</p>`:''}${V081_spark(t.history.map(x=>x.value),t.name+' franchise value trend')}<div class="controls">${[.001,.005,.01].map(sh=>`<button class="secondary" onclick="V081_buySports(${t.id},${sh})">Buy ${(sh*100).toFixed(1)}%</button>`).join('')}</div></section>`}).join('')}</div>`:`<div class="catalog-market-grid">${s.v081.sports.holdings.map(h=>{const t=s.v081.sports.teams.find(x=>x.id===h.team),value=t.value*h.share,gain=value-h.basis;return `<section class="card"><span class="eyebrow">ENCORE PRO BASKETBALL</span><h2>${esc(t.name)}</h2>${profileRows([['Ownership',(h.share*100).toFixed(1)+'%'],['Current value',money(value)],['Cost basis',money(h.basis)],['Unrealized gain / loss',money(gain)],['Distributions',money(h.payouts||0)],['Team record',t.wins+'–'+t.losses]])}${V081_spark(h.history.map(x=>x.value),'Sports stake value trend')}<button class="secondary" onclick="V081_sellSports(${h.id})">Review sale</button></section>`}).join('')||'<section class="card"><p>No sports ownership stakes yet.</p></section>'}</div>`}`};

const V083_buySports081=V081_buySports;
V081_buySports=function(id,share=.01,confirmed=false){V083_buySports081(id,share,confirmed);if(confirmed)return;const t=s.v081?.sports?.teams?.find(x=>x.id===id),el=$('modal');if(t&&el?.open)el.innerHTML+=`<section class="investment-note"><strong>Franchise history</strong><span>${t.titles} championship${t.titles===1?'':'s'} · ${Math.round(t.playoffRate*100)}% historic playoff rate</span><small>${esc(t.legacy)}</small></section>`};

const V083_whatsNew082=V082_whatsNew;
V082_whatsNew=function(){modal(`<span class="eyebrow">ENCORE · 0.8.3</span><h2>More rhythm. More consistency.</h2><ul><li>Career progression is weekly again; one advance equals one chart week.</li><li>Calendar labels now use real months and years beginning in January 2026.</li><li>Monthly business systems still settle once per month, so rent, assets and catalogs are not charged weekly.</li><li>Sports ownership is now one ten-team fictional basketball league with varied valuations and franchise histories.</li><li>PULSE song links are optional for normal posts; only release announcements require a track.</li><li>Character portraits now use deterministic gender-aware assignment so obvious names match their illustrated portrait.</li></ul><button class="primary" onclick="$('modal').close()">Back to ENCORE</button>`)};

const V083_renderTitle082=renderTitle;
renderTitle=function(){V083_renderTitle082();const root=$('title-screen');if(root&&!root.hidden){const line=root.querySelector?.('.intro-overline');if(line)line.textContent='THE ARTIST LIFE SIM · BETA '+GAME_VERSION}};
