/* ENCORE 0.9.2 — feature pricing, cash/royalty splits and studio cleanup. */
function V092_migrateCollabs(){
  migrateV081?.();
  const c=s.v081.creative;
  if(!Number.isSafeInteger(c.featurePrice)||c.featurePrice<0)c.featurePrice=V092_featureMarketValue();
  c.featureRoyalties??=[];c.featureDeals??=[];
}
function V092_featureMarketValue(){
  const fans=Math.max(1,s.fans||0),followers=Math.max(0,s.social?.followers||0),awards=Math.max(0,s.expansion?.awardWins||0);
  return Math.max(100,Math.round((Math.sqrt(fans)*95+Math.sqrt(followers)*30+(s.reputation||0)*400+level('marketability')*250+awards*7500)/50)*50)
}
function V092_featureBudget(a){return a?Math.max(250,Math.round(((a.fans||0)*.018+(a.reputation||0)*900+(a.skill||0)*650)/100)*100):0}
function V092_setFeaturePrice(e){e.preventDefault();V092_migrateCollabs();const value=Number(new FormData(e.target).get('price'));if(!Number.isSafeInteger(value)||value<0){toast('Enter a whole-dollar feature price of $0 or more.');return}s.v081.creative.featurePrice=value;queueSave();render();toast('Feature price set to '+money(value)+'.')}
function V092_featurePriceCard(){
  V092_migrateCollabs();const ask=s.v081.creative.featurePrice,fair=V092_featureMarketValue(),ratio=ask/Math.max(1,fair),demand=ratio<=.75?'Very attractive':ratio<=1.25?'Market-aligned':ratio<=2?'Premium':ratio<=5?'Selective':'Very unlikely without major leverage';
  return `<section class="card feature-rate-card"><span class="eyebrow">YOUR FEATURE MARKET</span><h2>Set your guest verse price.</h2>${profileRows([['Your asking price',money(ask)],['Current market estimate',money(fair)],['Booking outlook',demand]])}<p>Your rate can be as high as you want. Artists compare it with your audience, momentum, reputation and their own budget. If cash is short, negotiate royalty points or a hybrid deal.</p><form class="form" onsubmit="V092_setFeaturePrice(event)"><label>Feature asking price ($)<input name="price" type="number" min="0" max="9007199254740991" step="1" value="${ask}" required></label><button class="primary">Update feature price</button></form></section>`
}
function V092_featureProjectedRoyaltyValue(a){return Math.max(1000,(a?.fans||0)*.45)*.5*26}
function V092_featureTermScore(o,cash,royalty){
  const a=s.world[o.artist],ask=Math.max(1,s.v081.creative.featurePrice||V092_featureMarketValue()),budget=V092_featureBudget(a),royaltyValue=V092_featureProjectedRoyaltyValue(a)*royalty/100,equivalent=cash+royaltyValue,relation=a?.relation||0,valueRatio=equivalent/ask,budgetFit=Math.min(1.25,budget/ask),audienceFit=Math.min(1.2,Math.log10(10+(a?.fans||0))/Math.max(1,Math.log10(10+(s.fans||0)))),score=clamp(Math.round(22+valueRatio*42+budgetFit*12+audienceFit*10+relation*.18+level('charisma')*.06),2,96);
  return {score,ask,budget,royaltyValue,equivalent,label:score>=82?'Excellent chance':score>=65?'Strong chance':score>=48?'Possible':score>=30?'Long shot':'Very unlikely'}
}
function V092_featureMeter(m){return `<div class="interest-meter"><div><span>Booking likelihood</span><strong>${m.label} · ${m.score}/100</strong></div><div class="bar"><i style="width:${m.score}%"></i></div><small>Royalty value is an estimate. Actual payouts depend on future simulated streams.</small></div>`}
function V092_previewFeatureTerms(form,id){const o=s.v081.creative.offers.find(x=>x.id===id&&x.status==='open');if(!o)return;const f=new FormData(form),cash=Number(f.get('cash')),royalty=Number(f.get('royalty')),m=V092_featureTermScore(o,Number.isFinite(cash)?cash:0,Number.isFinite(royalty)?royalty:0),el=$('feature-term-preview');if(el)el.innerHTML=`${profileRows([['Your ask',money(m.ask)],['Their estimated cash budget',money(m.budget)],['Cash offer',money(Math.max(0,cash||0))],['Royalty value estimate',money(m.royaltyValue)]])}${V092_featureMeter(m)}`}
function V092_reviewFeatureInvite(id){
  V092_migrateCollabs();const o=s.v081.creative.offers.find(x=>x.id===id&&x.status==='open'),a=o&&s.world[o.artist];if(!o||!a)return;const ask=s.v081.creative.featurePrice||0,budget=V092_featureBudget(a),cash=Math.min(ask,budget),shortfall=Math.max(0,ask-cash),royalty=shortfall?clamp(Math.ceil(shortfall/Math.max(1,V092_featureProjectedRoyaltyValue(a))*100),3,35):0,m=V092_featureTermScore(o,cash,royalty);
  modal(`${personPhoto('artist-'+(a.directoryKey??a.id),a.name,true)}<span class="eyebrow">FEATURE NEGOTIATION</span><h2>${esc(a.name)} wants you on a record.</h2><p>Your posted feature rate is ${money(ask)}. Their estimated cash budget is ${money(budget)}. Take cash, royalty points, or combine both.</p><form class="form" oninput="V092_previewFeatureTerms(this,${id})" onsubmit="V092_submitFeatureTerms(event,${id})"><label>Cash payment ($)<input name="cash" type="number" min="0" max="9007199254740991" step="1" value="${cash}" required></label><label>Your royalty share (%)<input name="royalty" type="number" min="0" max="50" step="0.5" value="${royalty}" required></label><div id="feature-term-preview">${profileRows([['Your ask',money(m.ask)],['Their estimated cash budget',money(m.budget)],['Cash offer',money(cash)],['Royalty value estimate',money(m.royaltyValue)]])}${V092_featureMeter(m)}</div><button class="primary">Send feature terms · 5 energy</button></form><button class="secondary" onclick="V081_declineCreative(${id});$('modal').close()">Decline</button>`);V090_wireNumberReadbacks?.($('modal'))
}
function V092_submitFeatureTerms(e,id){
  e.preventDefault();V092_migrateCollabs();const o=s.v081.creative.offers.find(x=>x.id===id&&x.status==='open'),a=o&&s.world[o.artist];if(!o||!a)return;const f=new FormData(e.target),cash=Number(f.get('cash')),royalty=Number(f.get('royalty'));if(!Number.isSafeInteger(cash)||cash<0||!Number.isFinite(royalty)||royalty<0||royalty>50)return;const m=V092_featureTermScore(o,cash,royalty);if(!spend(5))return;if(Math.random()>m.score/100){o.response='They passed on those terms.';o.status='declined';$('modal').close();render();toast(a.name+' passed on the feature terms.');return}
  const title=generate('song'),uid=a.nextCatalogId??((a.catalog||[]).length+1);a.nextCatalogId=uid+1;a.catalog.push({uid,title:title+' (feat. '+s.name+')',type:'Single',week:s.week,base:Math.max(1000,a.fans*.45),streams:Math.max(1000,Math.round(a.fans*.45)),total:Math.max(1000,Math.round(a.fans*.45)),factor:1});if(cash){changeCash(cash);recordIncome('other',cash);moneyEvent('Feature fee · '+a.name,cash)}if(royalty>0)s.v081.creative.featureRoyalties.push({id:s.v081.creative.nextId++,artist:a.id,uid,artistName:a.name,title,share:royalty/100,started:s.week,lastPaidWeek:s.week-1,earned:0,active:true});s.v081.creative.featureDeals.push({week:s.week,artist:a.id,name:a.name,title,cash,royalty});s.expansion.featureAppearances=(s.expansion.featureAppearances||0)+1;a.relation=clamp((a.relation||0)+5,-100,100);o.status='accepted';milestone('feature-deal-'+o.id,'Featured on '+a.name+' record',title+' · '+money(cash)+(royalty?' + '+royalty+'% royalty':''));$('modal').close();render();toast('Feature booked with '+a.name+'.')
}
function V092_settleFeatureRoyalties(){V092_migrateCollabs();let total=0;for(const r of s.v081.creative.featureRoyalties.filter(x=>x.active&&x.lastPaidWeek<s.week)){const a=s.world[r.artist],track=a?.catalog?.find(x=>x.uid===r.uid);if(!track){r.active=false;continue}const payout=cents(Math.max(0,track.streams||0)*.5*r.share);r.lastPaidWeek=s.week;r.earned=cents((r.earned||0)+payout);if(payout){changeCash(payout);recordIncome('other',payout);total+=payout}}if(total)moneyEvent('Feature royalty payouts',total);return total}
const V092_finishCareerWeek=finishCareerWeek;finishCareerWeek=function(){const out=V092_finishCareerWeek();V092_settleFeatureRoyalties();return out};
const V092_creativePage=V081_creativePage;V081_creativePage=function(){V092_migrateCollabs();return V092_creativePage().replace('<div class="chips">',V092_featurePriceCard()+'<div class="chips">')};
const V092_acceptCreative=V081_acceptCreative;V081_acceptCreative=function(id){const o=s.v081?.creative?.offers?.find(x=>x.id===id);if(o?.type==='featureInvite'&&o.status==='open')return V092_reviewFeatureInvite(id);return V092_acceptCreative(id)};

/* Keep only the newer 0.9 creative-direction interface. */
const V092_studio=studio;studio=function(){let html=V092_studio();if(!s.draft&&html.includes('studio-creative-brief'))html=html.replace(/<h[23]>Creative direction<\/h[23]>[\s\S]*?(?=<h[23]>Production budget<\/h[23]>)/i,'');return html};

/* Preserve decimal values in live number readbacks. */
V090_readableNumber=function(value,moneyValue=false){const raw=String(value??'').replace(/,/g,'').trim();if(!raw)return '';const n=Number(raw);if(!Number.isFinite(n))return '';const formatted=n.toLocaleString('en-US',{maximumFractionDigits:6});let words='';if(Number.isInteger(n)&&Math.abs(n)<=999999999999999)words=V090_numberWords(Math.abs(n));return `${moneyValue?'$':''}${formatted}${words?` · ${n<0?'negative ':''}${words}${moneyValue?' dollars':''}`:''}`};