/* ENCORE 0.9.3 — lifetime fame and legacy foundation.
   Careers can begin young, evolve through eras, and continue culturally after death. */
function V093_legacyState(){s.legacyWorld??={version:1,careerStartAge:Number(s.age||18),eras:[],milestones:[],estate:{active:false,value:0,weeklyRevenue:0,catalogDemand:0,screenProjects:[],stageProjects:[],anniversaries:[]},culturalImmortality:0};return s.legacyWorld}
function V093_lifeStage(age=Number(s.age||18)){if(age<13)return 'Child star';if(age<18)return 'Teen star';if(age<30)return 'Young adult';if(age<45)return 'Prime';if(age<60)return 'Veteran';return 'Living legend'}
function V093_legacyScore(){const l=V093_legacyState(),records=s.careerRecords||{},honors=Number(records.awards||records.honors||0),fans=Math.max(0,Number(s.fans||0)),catalog=Math.max(0,Number(s.catalogValue||s.empire?.catalogValue||0)),recognition=Number(s.careerWorld?.recognition||0),culture=Number(s.careerWorld?.culturalRelevance||0),longevity=Math.max(0,Number(s.age||18)-l.careerStartAge);const score=clamp(Math.log10(1+fans)*7+Math.log10(1+catalog)*3+recognition*.22+culture*.22+Math.min(18,honors*.7)+Math.min(15,longevity*.35),0,100);l.culturalImmortality=Math.max(l.culturalImmortality||0,score);return l.culturalImmortality}
function V093_legacyTier(){const x=V093_legacyScore();if(x>=95)return 'Immortal icon';if(x>=88)return 'Generational icon';if(x>=76)return 'Global legend';if(x>=62)return 'Era-defining star';if(x>=45)return 'Established legacy';return 'Career in progress'}
function V093_recordEra(name,reason='Career evolution'){const l=V093_legacyState(),existing=l.eras.find(x=>x.name===name);if(existing)return existing;const era={id:'era-'+Date.now(),name,startWeek:s.week,startAge:Number(s.age||18),stage:V093_lifeStage(),reason,fans:Number(s.fans||0),recognition:Number(s.careerWorld?.recognition||0)};l.eras.push(era);return era}
function V093_legacyMilestone(id,title,detail,weight=1){const l=V093_legacyState();if(l.milestones.some(x=>x.id===id))return false;l.milestones.unshift({id,title,detail,week:s.week,age:Number(s.age||18),weight});l.milestones=l.milestones.slice(0,100);l.culturalImmortality=clamp((l.culturalImmortality||0)+weight,0,100);return true}
function V093_evaluateLifetimeMilestones(){const l=V093_legacyState(),fans=Number(s.fans||0),recognition=Number(s.careerWorld?.recognition||0);if(Number(s.age||18)<13&&fans>=100000)V093_legacyMilestone('child-breakout','Childhood phenomenon','Reached a major audience before the teenage years.',4);if(Number(s.age||18)<18&&fans>=1000000)V093_legacyMilestone('teen-icon','Teen icon','Built a million-fan audience before adulthood.',4);if(recognition>=95)V093_legacyMilestone('world-recognition','Recognized around the world','The artist has become a near-universal cultural figure.',5);if(fans>=100000000)V093_legacyMilestone('100m-fans','One hundred million fans','The audience has crossed into historic global scale.',5);return l}
function V093_activateEstate(){const l=V093_legacyState();l.estate.active=true;l.estate.value=Math.max(l.estate.value,Number(s.catalogValue||s.empire?.catalogValue||0),Number(s.money||0));return l.estate}
function V093_posthumousProject(type,title,budget=0){const l=V093_legacyState();if(!l.estate.active)return false;const legacy=V093_legacyScore(),baseAudience=Math.pow(Math.max(1,Number(s.fans||0)),.72),prestige=.55+legacy/75,spend=Math.max(0,Number(budget||0)),gross=Math.round((baseAudience*950+spend*2.1)*prestige*(.72+Math.random()*.56));const project={id:'legacy-'+Date.now(),type,title:title||'Untitled Legacy Project',budget:spend,gross,week:s.week,legacyAtRelease:Math.round(legacy)};(type==='Film'?l.estate.screenProjects:l.estate.stageProjects).push(project);l.estate.value+=Math.max(0,gross-spend);l.estate.weeklyRevenue+=Math.round(gross/104);V093_legacyMilestone('legacy-project-'+project.id,`${project.title} becomes a legacy event`,`${type} generated ${money(gross)} worldwide.`,gross>=1e9?6:gross>=2.5e8?3:1);return project}
function V093_legacyDashboard(){const l=V093_evaluateLifetimeMilestones(),tier=V093_legacyTier();return `<section class="card legacy-dashboard"><span class="eyebrow">LIFETIME LEGACY</span><h2>${tier}</h2><p class="fine">A career is bigger than its current chart week. Childhood fame, reinvention, cultural moments, longevity, catalog ownership and what happens after death all build the legacy.</p><div class="stats"><div><b>${V093_lifeStage()}</b><small>Life stage</small></div><div><b>${Math.round(V093_legacyScore())}</b><small>Legacy score</small></div><div><b>${l.eras.length}</b><small>Career eras</small></div></div>${l.estate.active?`<div class="legacy-estate"><b>Estate & cultural afterlife</b><small>${money(l.estate.value)} estate value · ${money(l.estate.weeklyRevenue)} recurring weekly legacy revenue</small></div>`:''}</section>`}
