/* Fictional asset economy. Asset purchases are not deductible career expenses. */
const wealthItems=[
{id:'coupe',name:'Vesper GT',kind:'Cars',price:95000,drift:-.012,vol:.025,icon:'car',desc:'A touring coupe. Mileage and condition influence resale value.'},
{id:'hypercar',name:'Aurelia V12',kind:'Cars',price:1800000,drift:-.004,vol:.06,icon:'car',desc:'A limited-production supercar with a volatile collector market.'},
{id:'chain',name:'Diamond Cuban chain',kind:'Jewelry',price:45000,drift:0,vol:.035,icon:'gem',desc:'Custom-set diamonds. Retail premiums are not guaranteed at resale.'},
{id:'watch',name:'Tourbillon No. 8',kind:'Jewelry',price:180000,drift:.002,vol:.05,icon:'watch',desc:'A collectible mechanical watch requiring regular servicing.'},
{id:'canvas',name:'Midnight in Motion',kind:'Art',price:250000,drift:.003,vol:.08,icon:'art',desc:'An original contemporary canvas. Collector demand can move sharply.'},
{id:'sculpture',name:'Form in Bronze',kind:'Art',price:75000,drift:.002,vol:.045,icon:'art',desc:'A limited-edition sculpture; conservation preserves its condition.'},
{id:'condo',name:'Skyline condominium',kind:'Property',price:350000,drift:.002,vol:.018,icon:'house',rent:1800,desc:'A one-unit city property. Use it privately or offer a residential lease.'},
{id:'villa',name:'Hillside residence',kind:'Property',price:2500000,drift:.0015,vol:.03,icon:'house',rent:11000,desc:'A luxury home with higher upkeep and a smaller pool of qualified tenants.'},
{id:'duplex',name:'Courtyard duplex',kind:'Property',price:620000,drift:.002,vol:.02,icon:'house',rent:3400,desc:'Two residences managed under one combined lease in this version.'},
{id:'block',name:'Twelve-unit building',kind:'Property',price:3200000,drift:.002,vol:.025,icon:'house',rent:22000,desc:'A multifamily investment using an aggregate building tenancy and occupancy rate.'},
{id:'index',name:'Broad-market shares',kind:'Stocks',price:100,drift:.004,vol:.06,icon:'stock',yield:.0015,desc:'A fictional diversified stock holding with variable monthly returns and distributions.'},
{id:'growth',name:'NextWave technology',kind:'Stocks',price:250,drift:.005,vol:.12,icon:'stock',yield:0,desc:'A volatile growth company. High potential comes with large drawdowns.'},
{id:'bond',name:'Treasury-style bond fund',kind:'Bonds',price:1000,drift:0,vol:.008,icon:'bond',yield:.003,desc:'A fictional bond fund. Monthly distributions; market value can still fall.'},
{id:'coin',name:'Orbit coin',kind:'Crypto',price:200,drift:0,vol:.25,icon:'coin',yield:0,desc:'A fictional cryptocurrency with wide price swings and no guaranteed return.'}
];
function assetIcon(kind){const shapes={car:'M7 23l4-9h18l5 9v10H7z M11 23h19 M12 34v3 M29 34v3',gem:'M6 16l7-7h14l7 7-14 21z M6 16h28 M13 9l7 28 7-28',watch:'M14 5h12v7H14z M14 32h12v7H14z M20 13a10 10 0 1 0 0 20 10 10 0 1 0 0-20 M20 16v7l5 3',art:'M7 6h26v30H7z M11 29l7-12 5 7 5-5 M14 12h1',house:'M5 19L20 6l15 13 M9 17v20h22V17 M16 37V25h8v12',stock:'M7 6v30h29 M11 28l7-8 7 3 9-13',bond:'M8 6h25v31H8z M13 13h15 M13 19h15 M13 25h8',coin:'M20 5a15 15 0 1 0 0 30 15 15 0 1 0 0-30 M25 13h-8v14h8 M13 20h11'};return `<svg class="asset-icon" viewBox="0 0 40 42" aria-hidden="true"><path d="${shapes[kind]||shapes.bond}" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>`}
function migrateEmpire(){if(!s.empire)s.empire={assets:[],nextId:1,month:Math.floor((s.week-1)*12/52),transactions:[],staff:{},staffWeek:0,threat:null,rights:[],catalogHistory:[],fileSeen:null,merch:[],media:[],lastSettled:0};migrateSocial();migrateCalendar();}
function moneyEvent(text,amount){s.empire.transactions.unshift({week:s.week,text,amount});s.empire.transactions=s.empire.transactions.slice(0,80)}
let wealthCategory='All';
function wealthInventory(){const e=s.empire,owned=e.assets.reduce((n,a)=>n+a.value,0);return metricRail([['Cash',money(s.cash)],['Assets',money(owned)],['Catalog estimate',money(catalogValue())],['Estimated wealth',money(s.cash+owned+catalogOwnedValue())]])+`<div class="chips">${['All','Cars','Jewelry','Art','Property','Stocks','Bonds','Crypto'].map(k=>`<button class="${wealthCategory===k?'selected':''}" onclick="wealthCategory='${k}';render()">${k}</button>`).join('')}</div><div class="wealth-grid">${wealthItems.filter(x=>wealthCategory==='All'||x.kind===wealthCategory).map(x=>`<button class="asset-tile" onclick="assetDetail('${x.id}')">${assetPhoto(x)}<small>${x.kind}</small><h2>${x.name}</h2><p>${x.desc}</p><strong>${money(x.price)}${['Stocks','Bonds','Crypto'].includes(x.kind)?' per unit':''}</strong><span class="fine">Inspect & buy →</span></button>`).join('')}</div><section class="card"><h2>Your holdings</h2><div class="controls"><button class="secondary" onclick="maintainAssets(false)">Maintain all physical assets</button><button class="secondary" onclick="renovateProperties(false)">Renovate all properties</button></div>${e.assets.map(a=>`<div class="project-row"><div><strong>${esc(a.name)}</strong><small>${a.qty} units · ${money(a.value)} · ${a.condition===null?'Market investment':'Condition '+Math.round(a.condition)+'%'} · Cost basis ${money(a.basis)}</small></div><button class="secondary" onclick="holdingDetail(${a.id})">Manage</button></div>`).join('')||'<p>No assets yet.</p>'}</section><section class="card"><h2>Taxes & ownership</h2><p>Fictional game rules: personal goods carry 8% purchase tax, property 2% transfer tax, securities none. Purchase price and tax become cost basis. Realized gains, distributions and rental profit enter your existing progressive income-tax calculation. Unrealized appreciation is not taxed. Property tax is 1% of value annually, collected monthly. Personal upkeep is not deductible.</p><p>Values can rise or fall; ownership never guarantees profit. Investments are fictional and use simulated monthly returns.</p>${e.transactions.slice(0,12).map(x=>`<div class="row"><span>${esc(x.text)}</span><strong>${money(x.amount)}</strong></div>`).join('')}</section>`}
function assetDetail(id){if(marketInstrument(id)){tradeForm(id);return;}const x=wealthItems.find(x=>x.id===id);if(!x)return;const tax=x.kind==='Property'?.02:['Stocks','Bonds','Crypto'].includes(x.kind)?0:.08;modal(`${assetPhoto(x)}<h2>${x.name}</h2><p>${x.desc}</p>${profileRows([['Price per unit',money(x.price)],['Purchase tax',tax*100+'%'],['Monthly distribution',((x.yield||0)*100).toFixed(2)+'%'],['Market variation','Up to ±'+Math.round(x.vol*100)+'% monthly, plus trend']])}<form class="form" onsubmit="reviewAssetBuy(event,'${id}')"><label>Quantity<input name="qty" type="number" min="1" max="1000000" step="1" value="1" required></label><button class="primary">Review purchase</button></form>`)}
let pendingAsset=null;
function reviewAssetBuy(event,id){event.preventDefault();const x=wealthItems.find(x=>x.id===id),qty=Number(new FormData(event.target).get('qty'));if(!labelActive()||!x||!Number.isInteger(qty)||qty<1||qty>1000000)return;const subtotal=x.price*qty,tax=subtotal*(x.kind==='Property'?.02:['Stocks','Bonds','Crypto'].includes(x.kind)?0:.08);pendingAsset={id,qty,subtotal,tax,total:cents(subtotal+tax)};modal(`<h2>Confirm purchase</h2><p>${qty} × ${x.name}</p>${profileRows([['Purchase',money(subtotal)],['Tax',money(tax)],['Total',money(subtotal+tax)]])}<p>5 energy. This is an asset purchase, not a deductible career expense.</p><button class="primary" onclick="confirmAssetBuy()">Pay & acquire</button>`)}
function confirmAssetBuy(){const p=pendingAsset;if(!labelActive()||!p)return;if(s.cash<p.total){toast('Not enough spendable cash.');return}if(!spend(5))return;const x=wealthItems.find(x=>x.id===p.id);changeCash(-p.total);s.empire.assets.push({id:s.empire.nextId++,item:p.id,name:x.name,kind:x.kind,city:x.kind==='Property'?s.scene.city:null,qty:p.qty,basis:p.total,value:p.subtotal,condition:['Stocks','Bonds','Crypto'].includes(x.kind)?null:100,tenant:null,rent:(x.rent||0)*p.qty,arrears:0,renovated:0});moneyEvent('Purchased '+x.name,-p.total);pendingAsset=null;$('modal').close();render()}
function holdingDetail(id){const a=s.empire.assets.find(x=>x.id===id);if(!a)return;modal(`${assetPhoto(wealthItems.find(x=>x.id===a.item))}<h2>${esc(a.name)}</h2>${profileRows([['Market value',money(a.value)],['Cost basis',money(a.basis)],['Unrealized change',money(a.value-a.basis)],['Condition',a.condition===null?'Market security':Math.round(a.condition)+'%'],...(a.kind==='Property'?[['City',a.city?careerWorldMarket(a.city).city:'Unassigned legacy property']]:[])])}<p>Selling incurs a 2% transaction fee. Only the realized gain or loss enters income taxes. An occupied property must finish its lease before sale.</p><div class="controls"><button class="primary" ${a.tenant?'disabled':''} onclick="sellAsset(${id})">Review sale</button>${a.kind==='Property'?`<button class="secondary" onclick="propertyDetail(${id})">Rental management</button>`:''}</div>`)}
function sellAsset(id,confirmed=false){const a=s.empire.assets.find(x=>x.id===id);if(!labelActive()||!a||a.tenant)return;if(marketInstrument(a.item)){tradeForm(a.item,"sell");return}const proceeds=cents(a.value*.98),gain=cents(proceeds-a.basis);if(!confirmed){modal(`<h2>Sell ${esc(a.name)}?</h2>${profileRows([['Proceeds after 2% fee',money(proceeds)],['Taxable gain / loss',money(gain)]])}<p>5 energy. Taxes settle at the next financial close.</p><button class="primary" onclick="sellAsset(${id},true)">Confirm sale</button>`);return}if(!spend(5))return;changeCash(proceeds);s.finance.week.investment=cents((s.finance.week.investment||0)+gain);s.empire.assets=s.empire.assets.filter(x=>x.id!==id);moneyEvent('Sold '+a.name,proceeds);$('modal').close();render()}
function maintainAssets(confirmed=false){const targets=s.empire.assets.filter(a=>a.condition!==null&&a.condition<100),cost=cents(targets.reduce((n,a)=>n+a.value*(100-a.condition)*.0003,0));if(!labelActive()||!targets.length){toast('Everything is already maintained.');return}if(!confirmed){modal(`<h2>Maintain ${targets.length} assets?</h2><p>${money(cost)} total · 10 energy. Restores condition to 100. Personal upkeep is not deductible; rented-property upkeep is.</p><button class="primary" onclick="maintainAssets(true)">Confirm maintenance</button>`);return}if(s.cash<cost||!spend(10)){toast('You need enough cash and energy.');return}changeCash(-cost);for(const a of targets){if(a.kind==='Property'&&a.tenant)s.finance.week.expenses+=a.value*(100-a.condition)*.0003;a.condition=100}moneyEvent('Bulk maintenance',-cost);$('modal').close();render()}
function renovateProperties(confirmed=false){const targets=s.empire.assets.filter(a=>a.kind==='Property'&&a.renovated<3),cost=cents(targets.reduce((n,a)=>n+a.value*.08,0));if(!labelActive()||!targets.length){toast('No properties eligible for renovation.');return}if(!confirmed){modal(`<h2>Renovate all ${targets.length} properties?</h2><p>${money(cost)} total · 20 energy. Adds 5% estimated value and 8% asking rent; existing leases keep their agreed rent. Condition returns to 100. Three renovation tiers maximum. Cost is added to basis, not immediately deducted.</p><button class="primary" onclick="renovateProperties(true)">Confirm all renovations</button>`);return}if(s.cash<cost||!spend(20)){toast('You need enough cash and energy.');return}changeCash(-cost);for(const a of targets){a.basis+=a.value*.08;a.value*=1.05;a.rent=Math.round(a.rent*1.08);a.condition=100;a.renovated++}moneyEvent('Renovated all properties',-cost);$('modal').close();render()}
function propertyInventory(){return `<div class="controls"><button class="primary" onclick="wealthCategory='Property';careerTab='Wealth';render()">Property market</button><button class="secondary" onclick="renovateProperties()">Renovate all</button><button class="secondary" onclick="maintainAssets()">Maintain assets</button></div>${s.empire.assets.filter(a=>a.kind==='Property').map(a=>`<section class="card">${assetPhoto(wealthItems.find(x=>x.id===a.item))}<h2>${esc(a.name)}</h2>${profileRows([['Value',money(a.value)],['Monthly rent',money(a.tenant?.rent||a.rent)],['Tenant',a.tenant?.name||'Vacant / personal use'],['Condition',Math.round(a.condition)+'%'],['Arrears',money(a.arrears)]])}<button class="primary" onclick="propertyDetail(${a.id})">Manage property</button></section>`).join('')||'<section class="card"><p>Buy your first property in Wealth to manage rentals here.</p></section>'}`}
function propertyDetail(id){const a=s.empire.assets.find(x=>x.id===id&&x.kind==='Property');if(!a)return;modal(`<h2>${esc(a.name)}</h2>${a.tenant?`${profileRows([['Tenant',a.tenant.name],['Agreed monthly rent',money(a.tenant.rent)],['Reliability',a.tenant.reliability+'/100'],['Months remaining',a.tenant.remaining],['Missed rent',money(a.arrears)],['Occupancy',a.tenant.occupancy+'%']])}<p>Lease expires automatically. Missed rent remains recorded as arrears; recovery is uncertain. Renovations do not change rent mid-lease.</p><button class="secondary" onclick="collectArrears(${id})">Request arrears payment · 5 energy</button>`:`<form class="form" onsubmit="screenTenants(event,${id})"><label>Monthly asking rent<input type="number" name="rent" min="1" max="${Math.floor(a.rent*3)}" step="1" value="${Math.round(a.rent)}" required></label><label>Lease length (months)<input name="months" type="number" min="1" max="24" value="6" required></label><p>Screening costs $100 and 5 energy. Higher-than-market rent lowers occupancy. Buildings use one aggregate tenant profile in this version.</p><button class="primary">Screen tenants</button></form>${a.arrears?`<button class="secondary" onclick="collectArrears(${id})">Recover old arrears · 5 energy</button>`:''}`}`)}
let tenantApplications=null;
function screenTenants(e,id){e.preventDefault();const a=s.empire.assets.find(x=>x.id===id&&!x.tenant),f=new FormData(e.target),rent=Number(f.get('rent')),months=Number(f.get('months'));if(!labelActive()||!a||!Number.isSafeInteger(rent)||rent<1||rent>a.rent*3||!Number.isInteger(months)||months<1||months>24||!spend(5,100))return;tenantApplications={id,rent,months,list:[0,1,2].map((_,i)=>({name:generate('artist'),reliability:Math.round(rand(45+i*12,65+i*12)),occupancy:Math.round(clamp(Math.pow(a.rent/rent,2)*.95,0,1)*100)}))};modal(`<h2>Tenant applications</h2>${tenantApplications.list.map((t,i)=>`<section class="card"><h3>${esc(t.name)}</h3><p>Reliability ${t.reliability}/100 · Projected occupancy ${t.occupancy}% · ${money(rent)} monthly · ${months} months</p><button class="primary" onclick="signTenant(${i})">Sign this lease</button></section>`).join('')}`)}
function signTenant(i){const p=tenantApplications,a=p&&s.empire.assets.find(x=>x.id===p.id&&!x.tenant);if(!labelActive()||!a||!p.list[i])return;a.tenant={...p.list[i],rent:p.rent,remaining:p.months};tenantApplications=null;$('modal').close();render()}
function collectArrears(id){const a=s.empire.assets.find(x=>x.id===id);if(!a||!a.arrears||!spend(5))return;const got=Math.round(a.arrears*rand(.1,.5));a.arrears-=got;changeCash(got);s.finance.week.investment=(s.finance.week.investment||0)+got;moneyEvent('Recovered rental arrears',got);render();propertyDetail(id)}
function settleAssets(){for(const a of s.empire.assets){const x=wealthItems.find(x=>x.id===a.item);if(!marketInstrument(a.item))a.value=Math.max(.01,cents(a.value*(1+x.drift+rand(-x.vol,x.vol)*(1-(['Stocks','Bonds','Crypto'].includes(x.kind)?teamEffect('Financial adviser')*.004:0)))));if(a.condition!==null){a.condition=Math.max(0,a.condition-rand(.5,2));a.value*=1-(100-a.condition)*.00005}const payout=cents(a.value*(x.yield||0));if(payout){changeCash(payout);s.finance.week.investment=(s.finance.week.investment||0)+payout;moneyEvent(a.name+' distribution',payout)}if(a.kind==='Property'){const propertyTax=cents(a.value*.01/12),upkeep=cents(a.value*.0005);changeCash(-propertyTax-upkeep);if(a.tenant){s.finance.week.expenses+=propertyTax+upkeep;const due=Math.round(a.tenant.rent*a.tenant.occupancy/100),paid=Math.random()<a.tenant.reliability/100?due:Math.round(due*.4);a.arrears+=due-paid;changeCash(paid);s.finance.week.investment=(s.finance.week.investment||0)+paid;moneyEvent(a.name+' rent received',paid);a.tenant.remaining--;if(a.tenant.remaining<=0){addBriefing('lease:'+a.id+':'+s.week,'News','Lease completed',a.name+' is vacant. Review new applicants in Properties.');a.tenant=null}}moneyEvent(a.name+' tax & upkeep',-propertyTax-upkeep)}}}
